google_theme:
  styles:
    card:
      - height: 100%
    state:
      - font-size: 0.9rem
      - color: var(--secondary-text-color)
    label:
      - font-size: 0.9rem
      - color: var(--secondary-text-color)
      - margin-bottom: 20px

afvalbeheer:
  template: google_theme
  show_entity_picture: true
  show_label: true
  label: >-
    [[[
      if (entity.state.includes(","))
        return entity.state.split(",")[0];
      else 
        return entity.state;
    ]]]
  styles:
    label:
      - margin-bottom: 0px
  
air_purifier:
  template: google_theme
  hold_action:
    action: more-info
  show_state: true
  show_label: true
  label: >-
    [[[
      return "Kwaliteit: " + states["sensor.air_purifier_air_quality"].state
    ]]]

zonnescherm:
  entity: cover.zonnescherm
  template: google_theme
  show_state: false
  show_label: true
  label: >-
    [[[
      if (states["binary_sensor.zonnescherm_contact_contact"].state == "on")
        return "Open"
      else 
        return "Gesloten";
    ]]]
  styles:
    icon:
      - color: >-
          [[[
            if (states["binary_sensor.zonnescherm_contact_contact"].state == "on")
              return "var(--paper-item-icon-active-color)"
            else 
              return "var(--paper-item-icon-color)";
          ]]]
