homeassistant:
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

automation: !include_dir_merge_list automations
script: !include scripts.yaml
