swipe_nav:
  wrap: true
  animate: swipe
  prevent_default: false
  swipe_amount: 15

views:
  - !include lovelace/view_welkom.yaml
  - !include lovelace/view_woonkamer.yaml
  - !include lovelace/view_keuken.yaml
  - !include lovelace/view_toilet.yaml
  - !include lovelace/view_meterkast.yaml
