swipe_nav: !include lovelace/config/swipe_nav.yaml
button_card_templates: !include lovelace/config/button_card_templates.yaml

views:
  - !include lovelace/views/welkom.yaml
  - !include lovelace/views/woonkamer.yaml
  - !include lovelace/views/keuken.yaml
  - !include lovelace/views/toilet.yaml
  - !include lovelace/views/meterkast.yaml
