custom_header:
  compact_mode: true
  chevrons: false
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)

swipe_nav:
  wrap: true
  animate: swipe
  prevent_default: false
  swipe_amount: 15

views:
  - !include lovelace/view_welkom.yaml
  - !include lovelace/view_woonkamer.yaml
  - !include lovelace/view_keuken.yaml
  - !include lovelace/view_toilet.yaml
  - !include lovelace/view_meterkast.yaml
