ios:
  actions:
    - name: Alles uit
      background_color: "#ff0000"
      label:
        text: Alles uit
        color: "#ffffff"
      icon:
        icon: power
        color: "#ffffff"
      show_in_carplay: true
      show_in_watch: true

automation:
  - id: ios_action_going_to_sleep
    alias: iOS action - Alles uit
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: Alles uit
    action:
      - alias: Now turn everything off
        service: script.everything_off

  - id: check_devices_left_on
    alias: iOS action - Apparaten aangelaten
    mode: single
    trigger:
      - platform: state
        entity_id: group.residents
        to: not_home
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.count_inside_lights_on
            above: 0
          - condition: numeric_state
            entity_id: sensor.count_speakers_on
            above: 0
          - condition: numeric_state
            entity_id: sensor.count_tvs_on
            above: 0
    action:
      - alias: Set up variables for the actions
        variables:
          # Including an id in the action allows us to identify this script run and not accidentally trigger for other notification actions.
          action_all_off: "{{ 'ALL_OFF_' ~ context.id }}"

      - alias: Message everyone
        service: notify.all_phones
        data:
          title: Niemand meer thuis
          message: >-
            Dit staat nog aan:
            {% if states("sensor.count_inside_lights_on") not in ["unknown", "0"] %}{{ states("sensor.count_inside_lights_on") }}💡 {% endif %}
            {% if states("sensor.count_tvs_on") not in ["unknown", "0"] %}{{ states("sensor.count_tvs_on") }}📺  {% endif %}
            {% if states("sensor.count_speakers_on") not in ["unknown", "0"] %}{{ states("sensor.count_speakers_on") }}🔊 {% endif %}
          data:
            tag: devices_left_on
            url: /lovelace/welkom
            actions:
              - action: "{{ action_all_off }}"
                title: Zet alles uit

      - alias: Wait for a response
        wait_for_trigger:
          - platform: event
            event_type: mobile_app_notification_action
            event_data:
              action: "{{ action_all_off }}"

      - alias: Perform the action
        choose:
          - conditions: "{{ wait.trigger.event.data.action == action_all_off }}"
            sequence:
              - service: script.everything_off

      - alias: Clear this notification on all devices
        service: notify.all_phones
        data:
          message: clear_notification
          data:
            tag: devices_left_on
