ios:
  actions:
    - name: ALARM_OFF
      background_color: "#000000"
      label:
        text: Wekker uit
        color: "#ff0000"
      icon:
        icon: alarm-off
        color: "#ff0000"

    - name: ALARM_SNOOZE
      background_color: "#000000"
      label:
        text: Wekker gesnoozed
        color: "#ff0000"
      icon:
        icon: alarm-snooze
        color: "#ff0000"

automation:
  - id: ios_action_alarm_off
    alias: iOS action - alarm uit
    initial_state: on
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: ALARM_OFF
    action:
      - variables:
          user_id: "{{ trigger.event.context.user_id }}"

      - choose:
        - conditions:
            - "{{ is_state_attr('person.sander', 'user_id', user_id) }}"
          sequence: []

  - id: ios_action_alarm_snooze
    alias: iOS action - alarm gesnoozed
    initial_state: on
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: ALARM_SNOOZE
    action:
      - variables:
          user_id: "{{ trigger.event.context.user_id }}"

      - choose:
        - conditions:
            - "{{ is_state_attr('person.sander', 'user_id', user_id) }}"
            - "{{ is_state('person.sander', 'home') }}"
          sequence:
            service: cover.set_cover_position
            data:
              entity_id: cover.slaapkamer
              position: 12
