ios:
  actions:
    - name: GOING_TO_BED
      background_color: "#4c00ff"
      label:
        text: Naar bed
        color: "#ffffff"
      icon:
        icon: bed
        color: "#ffffff"

    - name: GOING_TO_SLEEP
      background_color: "#4c00ff"
      label:
        text: Gaan slapen
        color: "#ffffff"
      icon:
        icon: sleep
        color: "#ffffff"

automation:
  - id: ios_action_going_to_bed
    alias: iOS action - Naar bed
    initial_state: on
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: GOING_TO_BED
    action:
      - service: script.everything_off
        data:
          exclude_entity_ids:
            - light.woonkamer_groot_1
            - light.woonkamer_groot_2
            - light.woonkamer_klein

      - service: light.turn_off
        data:
          entity_id: light.woonkamer
          transition: 30

      - service: light.turn_on
        entity_id: light.bedlampen

  - id: ios_action_going_to_sleep
    alias: iOS action - Gaan slapen
    initial_state: on
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: GOING_TO_SLEEP
    action:
      - service: script.everything_off
