ios:
  actions:
    - name: Naar bed
      background_color: "#4c00ff"
      label:
        text: Naar bed
        color: "#ffffff"
      icon:
        icon: bed
        color: "#ffffff"

    - name: Gaan slapen
      background_color: "#4c00ff"
      label:
        text: Gaan slapen
        color: "#ffffff"
      icon:
        icon: sleep
        color: "#ffffff"

automation:
  - id: ios_action_going_to_bed
    alias: iOS action - Naar bed
    initial_state: on
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: Naar bed
    action:
      - service: script.everything_off
        data:
          exclude_entity_ids:
            - light.woonkamer_groot_1
            - light.woonkamer_groot_2
            - light.overloop_spot_1
            - light.overloop_spot_2
            - light.overloop_spot_3
            - light.gekleurde_licht

      - service: light.turn_off
        data:
          entity_id: light.woonkamer
          transition: 30

      - service: light.turn_on
        data:
          entity_id: light.bedlampen
          profile: nachtlampje

  - id: ios_action_going_to_sleep
    alias: iOS action - Gaan slapen
    initial_state: on
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: Gaan slapen
    action:
      - service: script.everything_off
