ios:
  actions:
    - name: Naar bed
      background_color: "#4c00ff"
      label:
        text: Naar bed
        color: "#ffffff"
      icon:
        icon: bed
        color: "#ffffff"

    - name: Gaan slapen
      background_color: "#4c00ff"
      label:
        text: Gaan slapen
        color: "#ffffff"
      icon:
        icon: sleep
        color: "#ffffff"

automation:
  - id: ios_action_going_to_bed
    alias: iOS action - Naar bed
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: Naar bed
    action:
      - alias: Turn most of the devices off
        service: script.everything_off
        data:
          exclude_entity_ids:
            - light.woonkamer_groot_1
            - light.woonkamer_groot_2
            - light.overloop_spot_1
            - light.overloop_spot_2
            - light.overloop_spot_3
            - light.gekleurde_licht

      - alias: Now turn some lights off with a transition
        service: light.turn_off
        data:
          entity_id: light.woonkamer
          transition: 30

      - choose:  
        - conditions:
            - alias: Is the current time before input_datetime.covers_down time
              condition: template
              value_template: >-
                {{ now() | as_timestamp | timestamp_custom("%H:%M:%S") < states("input_datetime.covers_down")}}
          sequence:
            - alias: Set the covers down time to be in a few seconds, so they all close
              service: input_datetime.set_datetime
              data:
                entity_id: input_datetime.covers_down
                time: >-
                  {{ (now() | as_timestamp + 5) | timestamp_custom("%H:%M:%S") }}

      - choose:  
        - conditions:
            - condition: state
              entity_id: binary_sensor.slaapkamerraam_contact
              state: "on"
          sequence:
            - alias: Wait if the window is closed within a given time
              wait_template: >-
                {{ is_state("binary_sensor.slaapkamerraam_contact", "off") }}
              timeout:
                minutes: 30
              continue_on_timeout: false

      - alias: Turn on the bed lights
        service: scene.turn_on
        data:
          transition: 2
        target:
          entity_id: scene.slaapkamer_bedlampen_nachtlampje

  - id: ios_action_going_to_sleep
    alias: iOS action - Gaan slapen
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: Gaan slapen
    action:
      - alias: Now turn everything off
        service: script.everything_off
