ios:
  actions:
    - name: Naar bed
      background_color: "#4c00ff"
      label:
        text: Naar bed
        color: "#ffffff"
      icon:
        icon: bed
        color: "#ffffff"
      show_in_carplay: false
      show_in_watch: true
      use_custom_colors: true

    - name: Gaan slapen
      background_color: "#4c00ff"
      label:
        text: Gaan slapen
        color: "#ffffff"
      icon:
        icon: sleep
        color: "#ffffff"
      show_in_carplay: false
      show_in_watch: true
      use_custom_colors: true

    - name: Uit bed
      background_color: "#4c00ff"
      label:
        text: Uit bed
        color: "#ffffff"
      icon:
        icon: sleep-off
        color: "#ffffff"
      show_in_carplay: false
      show_in_watch: true
      use_custom_colors: true

automation:
  - id: ios_action_going_to_bed
    alias: iOS action - Naar bed
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: event
        event_type: ios.action_fired
        event_data:
          actionName: Naar bed
    actions:
      - alias: Turn most of the devices off
        action: script.everything_off
        data:
          exclude_entity_ids:
            - light.woonkamer_groot_1
            - light.woonkamer_groot_2
            - light.overloop_spot_1
            - light.overloop_spot_2
            - light.overloop_spot_3
            - switch.gekleurde_licht

      - alias: Now turn some lights off with a transition
        action: light.turn_off
        data:
          entity_id: light.woonkamer
          transition: 30

      - choose:
          - conditions:
              - alias: If any of the covers is still open
                condition: template
                value_template: >-
                  {{
                    is_state("cover.slaapkamer", "open") or
                    is_state("cover.kledingkamer", "open") or
                    is_state("cover.logeerkamer", "open")
                  }}
            sequence:
              - alias: Set the covers down time to be in a few seconds, so they all close
                action: input_datetime.set_datetime
                data:
                  entity_id: input_datetime.covers_down
                  time: >-
                    {{ (now() | as_timestamp + 5) | timestamp_custom("%H:%M:%S") }}

      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.slaapkamerraam_contact
                state: "on"
            sequence:
              - alias: Wait if the window is closed within a given time
                wait_template: >-
                  {{ is_state("binary_sensor.slaapkamerraam_contact", "off") }}
                timeout:
                  minutes: 60
                continue_on_timeout: false

      - alias: Turn on the bed lights
        action: scene.turn_on
        data:
          transition: 2
        target:
          entity_id: scene.slaapkamer_naar_bed

  - id: ios_action_going_to_sleep
    alias: iOS action - Gaan slapen
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: event
        event_type: ios.action_fired
        event_data:
          actionName: Gaan slapen
    actions:
      - alias: Now turn everything off
        action: script.everything_off

  - id: ios_action_going_out_of_bed
    alias: iOS action - Uit bed
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: event
        event_type: ios.action_fired
        event_data:
          actionName: Uit bed
    actions:
      - alias: Open south facing covers based on temperature
        action: script.open_south_facing_covers_based_on_weather

      - alias: Set curtains to preference position
        action: button.press
        target:
          entity_id:
            - button.logeerkamer_rolgordijn_voorkeurspositie
            - button.keuken_rolgordijn_voorkeurspositie
