ios:
  actions:
    - name: Qmusic
      background_color: "#ed3624"
      label:
        text: Qmusic
        color: "#ffffff"
      icon:
        icon: radio
        color: "#ffffff"
      show_in_carplay: false
      show_in_watch: true
      use_custom_colors: true

    - name: Ziggo
      background_color: "#ffffff"
      label:
        text: Ziggo
        color: "#f48c00"
      icon:
        icon: television-classic
        color: "#f48c00"
      show_in_carplay: false
      show_in_watch: true
      use_custom_colors: true

automation:
  - id: ios_action_radio_qmusic
    alias: iOS action - Qmusic
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: Qmusic
    action:
      - service: script.play_livingroom_radio
        data:
          stream: https://stream.qmusic.nl/qmusic/mp3

  - id: ios_action_tv_ziggo
    alias: iOS action - Ziggo
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: Ziggo
    action:
      - choose:
          # Turn on.
          - conditions:
              - condition: state
                entity_id: media_player.mediabox
                state: "off"
            sequence:
              - service: script.lg_c9_source_ziggo
        # Turn off.
        default:
          - service: media_player.turn_off
            entity_id: media_player.mediabox
