ios:
  actions:
    - name: Qmusic
      background_color: "#ed3624"
      label:
        text: Qmusic
        color: "#ffffff"
      icon:
        icon: radio
        color: "#ffffff"
      show_in_carplay: false
      show_in_watch: true
      use_custom_colors: true

    - name: Odido
      background_color: "#ffffff"
      label:
        text: Odido
        color: "#1b5ee4"
      icon:
        icon: television-classic
        color: "#1b5ee4"
      show_in_carplay: false
      show_in_watch: true
      use_custom_colors: true

automation:
  - id: ios_action_radio_qmusic
    alias: iOS action - Qmusic
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: event
        event_type: ios.action_fired
        event_data:
          actionName: Qmusic
    actions:
      - action: script.play_livingroom_radio
        data:
          stream: https://stream.qmusic.nl/qmusic/mp3

  - id: ios_action_tv_odido
    alias: iOS action - Odido
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: event
        event_type: ios.action_fired
        event_data:
          actionName: Odido
    actions:
      - choose:
          # Turn on.
          - conditions:
              - condition: state
                entity_id: media_player.4k_tv_box_2
                state: "off"
            sequence:
              - action: media_player.turn_on
                entity_id: media_player.4k_tv_box_2
        # Turn off.
        default:
          - action: media_player.turn_off
            entity_id: media_player.4k_tv_box_2
