ios:
  actions:
    - name: Wekker uit
      background_color: "#000000"
      label:
        text: Wekker uit
        color: "#ff0000"
      icon:
        icon: alarm-off
        color: "#ff0000"

    - name: Wekker gesnoozed
      background_color: "#000000"
      label:
        text: Wekker gesnoozed
        color: "#ff0000"
      icon:
        icon: alarm-snooze
        color: "#ff0000"

automation:
  - id: ios_action_alarm_clock_off
    alias: iOS action - Wekker uit
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: Wekker uit
    action:
      - variables:
          user_id: "{{ trigger.event.context.user_id }}"

      - choose:
          # It should come from Sander and he should be home.
          - conditions:
              - "{{ is_state_attr('person.sander', 'user_id', user_id) }}"
              - "{{ is_state('person.sander', 'home') }}"
            sequence: []

  - id: ios_action_alarm_clock_snooze
    alias: iOS action - Wekker gesnoozed
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: Wekker gesnoozed
    action:
      - variables:
          user_id: "{{ trigger.event.context.user_id }}"

      - choose:
          # Temperature should be higher than a certain amount.
          - conditions:
              - "{{ state_attr('weather.knmi_purmerend', 'temperature') > -2 }}"
            sequence:
              - choose:
                  # It should come from Sander and he should be home.
                  - conditions:
                      - "{{ is_state_attr('person.sander', 'user_id', user_id) }}"
                      - "{{ is_state('person.sander', 'home') }}"
                    sequence:
                      service: cover.set_cover_position
                      data:
                        entity_id: cover.slaapkamer
                        position: 12
