ios:
  actions:
    - name: Wekker uit
      background_color: "#000000"
      label:
        text: Wekker uit
        color: "#ff0000"
      icon:
        icon: alarm-off
        color: "#ff0000"
      show_in_carplay: false
      show_in_watch: true
      use_custom_colors: true

    - name: Wekker gesnoozed
      background_color: "#000000"
      label:
        text: Wekker gesnoozed
        color: "#ff0000"
      icon:
        icon: alarm-snooze
        color: "#ff0000"
      show_in_carplay: false
      show_in_watch: true
      use_custom_colors: true

automation:
  - id: ios_action_alarm_clock_off
    alias: iOS action - Wekker uit
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: event
        event_type: ios.action_fired
        event_data:
          actionName: Wekker uit
    actions:
      - variables:
          user_id: "{{ trigger.event.context.user_id }}"

      - choose:
          - conditions:
              - alias: Should be triggered by Sander
                condition: template
                value_template: "{{ is_state_attr('person.sander', 'user_id', user_id) }}"
              - alias: Sander should be home
                condition: state
                entity_id: person.sander
                state: home
            sequence: []

  - id: ios_action_alarm_clock_snooze
    alias: iOS action - Wekker gesnoozed
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: event
        event_type: ios.action_fired
        event_data:
          actionName: Wekker gesnoozed
    actions:
      - variables:
          user_id: "{{ trigger.event.context.user_id }}"

      - choose:
          - conditions:
              - alias: Temperature should be higher than a certain value.
                condition: numeric_state
                entity_id: sensor.knmi_temperatuur
                above: -2
              - alias: Should be triggered by Sander
                condition: template
                value_template: "{{ is_state_attr('person.sander', 'user_id', user_id) }}"
              - alias: Sander should be home
                condition: state
                entity_id: person.sander
                state: home
            sequence:
              - choose:
                  - conditions:
                      - alias: Slaapkamer should be closed.
                        condition: state
                        entity_id: cover.slaapkamer
                        state: closed
                    sequence:
                      - alias: Set slaapkamer to the preference position
                        action: button.press
                        target:
                          entity_id: button.slaapkamer_my_position
              - choose:
                  - conditions:
                      - alias: Kledingkamer should be closed.
                        condition: state
                        entity_id: cover.kledingkamer
                        state: closed
                    sequence:
                      - alias: Set kledingkamer to the preference position
                        action: button.press
                        target:
                          entity_id: button.kledingkamer_my_position
