ios:
  actions:
    - name: Zonnescherm dicht
      background_color: "#ffff00"
      label:
        text: Zonnescherm dicht
        color: "#000000"
      icon:
        icon: arrow-up-box
        color: "#000000"
      use_custom_colors: true

    - name: Zonnescherm open
      background_color: "#ffff00"
      label:
        text: Zonnescherm open
        color: "#000000"
      icon:
        icon: arrow-down-box
        color: "#000000"
      use_custom_colors: true

    - name: Zonnescherm helemaal open
      background_color: "#ffff00"
      label:
        text: Zonnescherm helemaal open
        color: "#000000"
      icon:
        icon: arrow-down-box
        color: "#000000"
      show_in_carplay: false
      show_in_watch: true
      use_custom_colors: true

automation:
  - id: ios_action_awning_command
    alias: iOS action - Zonnescherm
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: event
        event_type: ios.action_fired
        event_data:
          actionName: Zonnescherm dicht
      - trigger: event
        event_type: ios.action_fired
        event_data:
          actionName: Zonnescherm open
      - trigger: event
        event_type: ios.action_fired
        event_data:
          actionName: Zonnescherm helemaal open
    actions:
      - variables:
          action_name: "{{ trigger.event.data.actionName }}"

      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ action_name == "Zonnescherm dicht" }}
            sequence:
              - alias: Close awning
                action: cover.close_cover
                target:
                  entity_id: cover.zonnescherm
          - conditions:
              - condition: template
                value_template: >-
                  {{ action_name == "Zonnescherm open" }}
            sequence:
              - alias: Open awning
                action: button.press
                target:
                  entity_id: button.zonnescherm_my_position
          - conditions:
              - condition: template
                value_template: >-
                  {{ action_name == "Zonnescherm  helemaal open" }}
            sequence:
              - alias: My position for awning
                action: cover.open_cover
                target:
                  entity_id: cover.zonnescherm

  - id: auto_close_awning
    alias: Zonnescherm automatisch sluiten
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: state
        entity_id: sensor.zon_positie
        from: Achter
        to: Voor
      - trigger: state
        entity_id: sun.sun
        to: below_horizon
      - trigger: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 7
    conditions:
      - condition: state
        entity_id: binary_sensor.zonnescherm_contact_contact
        state: "on"
    actions:
      - alias: Close the awning
        action: cover.close_cover
        target:
          entity_id: cover.zonnescherm

  - id: ios_action_awning_can_be_opened
    alias: iOS action - Zonnescherm kan open
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: numeric_state
        entity_id: sensor.achtertuin_sensor_1_licht
        above: 3800
      - trigger: state
        entity_id: sensor.zon_positie
        from: Voor
        to: Achter
    conditions:
      - condition: numeric_state
        entity_id: sensor.achtertuin_sensor_1_licht
        above: 3800
      - condition: state
        entity_id: sensor.zon_positie
        state: Achter
      - condition: numeric_state
        entity_id: sensor.knmi_max_temperatuur_vandaag
        above: 19
      - condition: numeric_state
        entity_id: sensor.knmi_neerslag_vandaag
        below: 10
      - condition: state
        entity_id: binary_sensor.zonnescherm_contact_contact
        state: "off"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    actions:
      - alias: Set up variables for the actions
        variables:
          # Including an id in the action allows us to identify this script run and not accidentally trigger for other notification actions.
          action_open: "{{ 'OPEN_' ~ context.id }}"

      - alias: Ask to close the awning
        action: notify.all_phones
        data:
          message: De zon is achter, wil je het zonnescherm openen?
          data:
            tag: sun
            actions:
              - action: "{{ action_open }}"
                title: Ja, open

      - alias: Wait for a response
        wait_for_trigger:
          - trigger: event
            event_type: mobile_app_notification_action
            event_data:
              action: "{{ action_open }}"

      - alias: Perform the action
        choose:
          - conditions: "{{ wait.trigger.event.data.action == action_open }}"
            sequence:
              - action: button.press
                target:
                  entity_id: button.zonnescherm_my_position

              - alias: Clear this notification on all devices
                action: notify.all_phones
                data:
                  message: clear_notification
                  data:
                    tag: sun
