media_player:
  - platform: universal
    name: Woonkamer
    children:
      - media_player.4k_tv_box_2 # The Android TV
      - media_player.4k_tv_box # The Chromecast from the Android TV
      - media_player.lg_c9 # The TV
    active_child_template: >-
      {% set source = state_attr("media_player.lg_c9", "source") %}
      {% set tv_box_2_app_id = state_attr("media_player.4k_tv_box_2", "app_id") %}
      {% if source == "Odido" %}
        {% if tv_box_2_app_id in ["com.google.android.youtube.tv", "org.jellyfin.androidtv"] %}
          media_player.4k_tv_box
        {% else %}
          media_player.4k_tv_box_2
        {% endif %}
      {% else %}
        media_player.lg_c9
      {% endif %}
    commands:
      turn_on:
        action: media_player.turn_on
        target:
          entity_id:
            - media_player.4k_tv_box_2
      turn_off:
        action: media_player.turn_off
        target:
          entity_id:
            - media_player.4k_tv_box_2
      volume_up:
        action: media_player.volume_up
        target:
          entity_id: media_player.lg_c9
      volume_down:
        action: media_player.volume_down
        target:
          entity_id: media_player.lg_c9
      volume_mute:
        action: media_player.volume_mute
        data:
          is_volume_muted: >-
            {{ not state_attr("media_player.lg_c9", "is_volume_muted") }}
        target:
          entity_id: media_player.lg_c9
    attributes:
      is_volume_muted: media_player.lg_c9|is_volume_muted

automation:
  - id: lgc9_turn_on_wol
    alias: LG C9 - Turn on via Wake-On-LAN
    mode: single
    triggers:
      - trigger: webostv.turn_on
        entity_id: media_player.lg_c9
    actions:
      - action: wake_on_lan.send_magic_packet
        data:
          mac: !secret webostv_mac
          broadcast_address: !secret webostv_ip

script:
  lg_c9_source_odido:
    alias: Speel Odido op LG C9
    icon: mdi:television
    mode: restart
    sequence:
      - if:
          - condition: or
            conditions:
              - condition: state
                entity_id: media_player.lg_c9
                state: "off"
              - condition: state
                entity_id: media_player.4k_tv_box_2
                state: "off"
        then:
          - alias: Turn on the tv box
            action: media_player.turn_on
            data:
              entity_id: media_player.4k_tv_box_2

      - alias: Set the source of the tv to odido
        action: script.play_tv_with_source
        data:
          media_player: media_player.lg_c9
          source: Odido
