media_player:
  - platform: universal
    name: Woonkamer
    children:
      - media_player.plex_plex_for_lg_lg_oled65c9pla
      - media_player.mediabox
      - media_player.lg_c9
    commands:
      volume_up:
        service: media_player.volume_up
        target:
          entity_id: media_player.lg_c9
      volume_down:
        service: media_player.volume_down
        target:
          entity_id: media_player.lg_c9
      volume_mute:
        service: media_player.volume_mute
        data:
          is_volume_muted: >-
            {{ not state_attr("media_player.lg_c9", "is_volume_muted") }}
        target:
          entity_id: media_player.lg_c9
    attributes:
      is_volume_muted: media_player.lg_c9|is_volume_muted


automation:
  - id: lgc9_turn_on_wol
    alias: LG C9 - Turn on via Wake-On-LAN
    mode: single
    trigger:
      - platform: webostv.turn_on
        entity_id: media_player.lg_c9
    action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: !secret webostv_mac
          broadcast_address: !secret webostv_ip

script:
  lg_c9_source_ziggo:
    alias: Speel Ziggo op LG C9
    icon: mdi:television
    mode: restart
    sequence:
      - if:
          - condition: state
            entity_id: media_player.lg_c9
            state: "off"
        then:
          - alias: Turn on the mediabox
            service: media_player.turn_on
            data:
              entity_id: media_player.mediabox

      - alias: Set the source of the tv to ziggo
        service: script.play_tv_with_source
        data:
          media_player: media_player.lg_c9
          source: Ziggo
