blueprint:
  name: Door or Window Climate Control Automation
  description: |
    Automate HVAC control based on the state of doors or windows (or other binary sensors).
    - When a door/window is **open** (binary_sensor is `on`), the HVAC mode is set to **off**.
    - When a door/window is **closed** (binary_sensor is `off`), the HVAC mode is set to **auto**.

    You can specify a delay to prevent the HVAC from turning off immediately when the door/window is briefly opened.
  domain: automation
  author: golles
  source_url: https://raw.githubusercontent.com/golles/Home-Assistant-Config/main/blueprints/automation/golles/door-window-climate-control.yaml
  input:
    door_entity:
      name: Door/Window Sensor
      description: Select a binary sensor for a door, window, or similar entity.
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: door
            - domain: binary_sensor
              device_class: window
    climate_entity:
      name: Climate Device
      description: Select the climate entity to control.
      selector:
        entity:
          domain: climate
    turn_off_delay:
      name: Delay Before Turning Off
      description: Time (in seconds) to wait before turning off the HVAC when the door/window is opened.
      default: 120
      selector:
        number:
          min: 0
          max: 600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input door_entity
    from: "off"
    to: "on"
  - trigger: state
    entity_id: !input door_entity
    from: "on"
    to: "off"

actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input door_entity
            state: "on"
        sequence:
          - alias: Wait before turning off climate.
            delay: !input turn_off_delay

          - alias: Set climate to off.
            action: climate.set_hvac_mode
            entity_id: !input climate_entity
            data:
              hvac_mode: "off"

    default:
      - alias: Set climate to auto.
        action: climate.set_hvac_mode
        entity_id: !input climate_entity
        data:
          hvac_mode: auto
