blueprint:
  name: Motion-activated scenes based on time and light level and with a grace period.
  description: |
    This motion-activated blueprint allows you to setup automatic light switching like the Philips Hue motion
    sensors do. When motion is detected, the light will be turned on, when the motion is no longer detected,
    the lights will go to another state for a given amount of seconds before switching off.
    This allows anyone to not be left in the dark, you will be warned before the light switches off.
    This automation should work with any lights, motion sensors and illuminance sensors.
  domain: automation
  author: golles
  source_url: https://raw.githubusercontent.com/golles/Home-Assistant-Config/main/blueprints/automation/golles/motion-activated_scenes.yaml
  input:
    motion_entity:
      name: Motion sensor
      selector:
        entity:
          device_class: motion
    cool_down:
      name: Cool down period
      description: Number of seconds before dimming the brightness when motion is no longer detected.
      default: 0
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: seconds
          mode: slider
    no_motion_wait:
      name: Wait time
      description: Number of seconds to leave the light on with turning off scene.
      default: 15
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: seconds
          mode: slider
    light_entity:
      name: Light
      selector:
        entity:
          domain: light
    illuminance_entity:
      name: Illuminance sensor
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    illuminance_below:
      name: Minimum illuminance
      description: The light will only switch on when the illuminance is bellow this value.
      default: 10
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: lx
          mode: box
    illuminance_above:
      name: Illuminance turn off
      description: The light will switch off when the illuminance is above this value.
      default: 40
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: lx
          mode: box
    day_start_time:
      name: Day start time
      description: From this time the day scene will be used to switch on the light.
      default: "07:00"
      selector:
        time:
    day_end_time:
      name: Day end time
      description: Till this time the day scene will be used to switch on the light.
      default: "23:00"
      selector:
        time:
    day_scene:
      name: Day time scene name when turning on
      selector:
        entity:
          domain: scene
    day_scene_before_off:
      name: Day time scene name before turning off
      selector:
        entity:
          domain: scene
    night_scene:
      name: Night time scene name when turning on
      selector:
        entity:
          domain: scene
    night_scene_before_off:
      name: Night time scene name before turning off
      selector:
        entity:
          domain: scene

# If motion is detected within the delay, we restart the script.
# If there is no motion, the brightness drops before turning off.
mode: restart
max_exceeded: silent

trigger:
  - trigger: state
    id: motion_on
    entity_id: !input motion_entity
    to: "on"
  - trigger: state
    id: motion_off
    entity_id: !input motion_entity
    to: "off"
    for: !input cool_down
  - trigger: numeric_state
    id: illuminance_low
    entity_id: !input illuminance_entity
    below: !input illuminance_below
    for:
      minutes: 5
  - trigger: numeric_state
    id: illuminance_high
    entity_id: !input illuminance_entity
    above: !input illuminance_above
    for:
      minutes: 5

actions:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id: motion_on
                  - condition: or
                    conditions:
                      - condition: numeric_state
                        entity_id: !input illuminance_entity
                        below: !input illuminance_below
                      - condition: state
                        entity_id: !input light_entity
                        state: "on"
              - condition: and
                conditions:
                  - condition: trigger
                    id: illuminance_low
                  - condition: state
                    entity_id: !input motion_entity
                    state: "on"
                  - condition: state
                    entity_id: !input light_entity
                    state: "off"
        sequence:
          - if:
              - condition: time
                after: !input day_start_time
                before: !input day_end_time
            then:
              # Day time.
              - alias: Turn on light with day scene
                action: scene.turn_on
                data:
                  transition: 1
                target:
                  entity_id: !input day_scene
            else:
              # Other times
              - alias: Turn on light with night scene
                action: scene.turn_on
                data:
                  transition: 1
                target:
                  entity_id: !input night_scene

      - conditions:
          - condition: trigger
            id: motion_off
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - if:
              - condition: time
                after: !input day_start_time
                before: !input day_end_time
            then:
              # Day time.
              - alias: Turn on light with day before off scene
                action: scene.turn_on
                data:
                  transition: 1
                target:
                  entity_id: !input day_scene_before_off
            else:
              # Other times
              - alias: Turn on light with night before off scene
                action: scene.turn_on
                data:
                  transition: 1
                target:
                  entity_id: !input night_scene_before_off

          - alias: Wait for the no motion wait delay
            delay: !input no_motion_wait

          - alias: Turn off the light
            action: light.turn_off
            data:
              transition: 1
            target:
              entity_id: !input light_entity

      - conditions:
          - condition: trigger
            id: illuminance_high
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - alias: Turn off the light, illuminance is high enough
            action: light.turn_off
            data:
              transition: 1
            target:
              entity_id: !input light_entity
