blueprint:
  name: Motion-Activated Scenes with Time and Light-Level Control
  description: |
    Automate lighting based on motion, time of day, and ambient light levels.
    - Lights turn **on** when motion is detected and stay on based on conditions.
    - When no motion is detected, lights transition to a dimmed state before turning **off**.
    - Day and night scenes can be customized for different times of day.
    - Includes options to prevent turning on lights in bright conditions or turning off when light levels are high.

    Ideal for use with motion sensors, illuminance sensors, and smart lighting systems.
  domain: automation
  author: golles
  source_url: https://raw.githubusercontent.com/golles/Home-Assistant-Config/main/blueprints/automation/golles/motion-activated_scenes.yaml
  input:
    motion_entity:
      name: Motion Sensor
      description: The motion sensor to use for triggering actions.
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: occupancy
            - domain: binary_sensor
              device_class: motion
    cool_down:
      name: Cooldown Period
      description: Time (in seconds) before dimming brightness after motion stops.
      default: 0
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: seconds
          mode: slider
    no_motion_wait:
      name: Wait Time Before Turning Off
      description: Time (in seconds) to leave the light on before turning it off completely.
      default: 15
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: seconds
          mode: slider
    light_entity:
      name: Light Entity
      description: The light to control.
      selector:
        entity:
          domain: light
    illuminance_entity:
      name: Illuminance Sensor
      description: The sensor measuring ambient light levels.
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    illuminance_below:
      name: Minimum Illuminance to Turn On
      description: Lights will only turn on when illuminance falls below this value (in lux).
      default: 10
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: lx
          mode: box
    illuminance_above:
      name: Maximum Illuminance to Turn Off
      description: Lights will turn off when illuminance rises above this value (in lux).
      default: 40
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: lx
          mode: box
    day_start_time:
      name: Day Start Time
      description: Time from which the "day scene" will be applied.
      default: "07:00"
      selector:
        time:
    day_end_time:
      name: Day End Time
      description: Time until which the "day scene" will be applied.
      default: "23:00"
      selector:
        time:
    day_scene:
      name: Day Scene
      description: Scene to activate during the day when turning on the light.
      selector:
        entity:
          domain: scene
    day_scene_before_off:
      name: Day Scene Before Turning Off
      description: Scene to activate during the day before lights turn off.
      selector:
        entity:
          domain: scene
    night_scene:
      name: Night Scene
      description: Scene to activate during the night when turning on the light.
      selector:
        entity:
          domain: scene
    night_scene_before_off:
      name: Night Scene Before Turning Off
      description: Scene to activate during the night before lights turn off.
      selector:
        entity:
          domain: scene

# Restart mode ensures the automation reacts to subsequent motion.
mode: restart
max_exceeded: silent

trigger:
  - trigger: state
    id: motion_on
    entity_id: !input motion_entity
    to: "on"
  - trigger: state
    id: motion_off
    entity_id: !input motion_entity
    to: "off"
    for: !input cool_down
  - trigger: numeric_state
    id: illuminance_low
    entity_id: !input illuminance_entity
    below: !input illuminance_below
    for:
      minutes: 5
  - trigger: numeric_state
    id: illuminance_high
    entity_id: !input illuminance_entity
    above: !input illuminance_above
    for:
      minutes: 5

actions:
  - choose:
      # Handle motion detected and light-level conditions
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id: motion_on
                  - condition: or
                    conditions:
                      - condition: numeric_state
                        entity_id: !input illuminance_entity
                        below: !input illuminance_below
                      - condition: state
                        entity_id: !input light_entity
                        state: "on"
              - condition: and
                conditions:
                  - condition: trigger
                    id: illuminance_low
                  - condition: state
                    entity_id: !input motion_entity
                    state: "on"
                  - condition: state
                    entity_id: !input light_entity
                    state: "off"
        sequence:
          - if:
              - condition: time
                after: !input day_start_time
                before: !input day_end_time
            then:
              - alias: Activate Day Scene
                action: scene.turn_on
                data:
                  transition: 1
                target:
                  entity_id: !input day_scene
            else:
              - alias: Activate Night Scene
                action: scene.turn_on
                data:
                  transition: 1
                target:
                  entity_id: !input night_scene

      # Handle motion stopped
      - conditions:
          - condition: trigger
            id: motion_off
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - if:
              - condition: time
                after: !input day_start_time
                before: !input day_end_time
            then:
              - alias: Activate Day Scene Before Turning Off
                action: scene.turn_on
                data:
                  transition: 1
                target:
                  entity_id: !input day_scene_before_off
            else:
              - alias: Activate Night Scene Before Turning Off
                action: scene.turn_on
                data:
                  transition: 1
                target:
                  entity_id: !input night_scene_before_off

          - alias: Wait Before Turning Off
            delay: !input no_motion_wait

          - alias: Turn Off Light
            action: light.turn_off
            data:
              transition: 1
            target:
              entity_id: !input light_entity

      # Handle illuminance too high
      - conditions:
          - condition: trigger
            id: illuminance_high
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - alias: Turn Off Light Due to High Illuminance
            action: light.turn_off
            data:
              transition: 1
            target:
              entity_id: !input light_entity
