blueprint:
  name: Zigbee2MQTT - Hue smart button - press and hold actions for a bed light button
  description: |
    Automate actions for a Philips Hue smart button connected via Zigbee2MQTT to control bedside and ceiling lights.
    - **Single Press:** Toggles the bedside light on or off.
    - **Hold:** Toggles the ceiling light on or off.

    This automation uses light profiles for color, brightness, and transition settings. To simplify configuration and centralize light state management, set up light profiles. Learn more in the [Home Assistant Light Profile documentation](https://www.home-assistant.io/integrations/light/).

    **Note:** Works exclusively with the Philips Hue smart button (8718699693985) integrated via Zigbee2MQTT.
  domain: automation
  author: golles
  source_url: https://raw.githubusercontent.com/golles/Home-Assistant-Config/main/blueprints/automation/golles/zigbee2mqtt_hue_smart_button_bed_light_button.yaml
  input:
    smart_button:
      name: Hue Smart Button Device
      description: The Hue smart button device connected via Zigbee2MQTT.
      selector:
        device:
          integration: mqtt
          manufacturer: Philips
          model: Hue smart button
    light_entity_bed:
      name: Bedside Light
      description: The light entity for the bedside lamp.
      selector:
        entity:
          domain: light
    light_entity_ceiling:
      name: Ceiling Light
      description: The light entity for the ceiling lamp.
      selector:
        entity:
          domain: light
    day_start_time:
      name: Start Time for Day Profile
      description: The time after which the day profile will be used for lighting.
      default: "08:00"
      selector:
        time:
    day_end_time:
      name: End Time for Day Profile
      description: The time before which the day profile will be used for lighting.
      default: "23:00"
      selector:
        time:
    day_profile:
      name: Daytime Light Profile
      description: Light profile to use during the day. Defaults to "reading."
      default: reading
    night_profile:
      name: Nighttime Light Profile
      description: Light profile to use at night. Defaults to "energize."
      default: energize

mode: single
max_exceeded: silent

triggers:
  - trigger: device
    domain: mqtt
    device_id: !input smart_button
    type: action
    subtype: "on"
  - trigger: device
    domain: mqtt
    device_id: !input smart_button
    type: action
    subtype: "off"
  - trigger: device
    domain: mqtt
    device_id: !input smart_button
    type: action
    subtype: hold

actions:
  - choose:
      # Button is being pressed.
      - conditions:
          - "{{ trigger.payload in ['on', 'off'] }}"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input light_entity_bed
                    state: "off"
                sequence:
                  - choose:
                      - conditions:
                          - condition: time
                            after: !input day_start_time
                            before: !input day_end_time
                        sequence:
                          - action: light.turn_on
                            data:
                              entity_id: !input light_entity_bed
                              profile: !input day_profile
                    default:
                      - action: light.turn_on
                        data:
                          entity_id: !input light_entity_bed
                          profile: !input night_profile
            default:
              - action: light.turn_off
                entity_id: !input light_entity_bed

      # Button is being hold.
      - conditions:
          - "{{ trigger.payload == 'hold' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input light_entity_ceiling
                    state: "off"
                sequence:
                  - choose:
                      - conditions:
                          - condition: time
                            after: !input day_start_time
                            before: !input day_end_time
                        sequence:
                          - action: light.turn_on
                            data:
                              entity_id: !input light_entity_ceiling
                              profile: !input day_profile
                    default:
                      - action: light.turn_on
                        data:
                          entity_id: !input light_entity_ceiling
                          profile: !input night_profile
            default:
              - action: light.turn_off
                data:
                  entity_id: !input light_entity_ceiling
          - delay:
              seconds: 5
