blueprint:
  name: Zigbee2MQTT - Aqara Magic Cube (MFKZQ01LM)
  description: |
    Create automations for the Aqara Magic Cube (MFKZQ01LM) using Zigbee2MQTT.
    Supports actions like flips, rotations, slides, taps, drops, and shakes with side-specific triggers.

    **Limitations:**
    - Flip actions (90° or 180°) cannot be distinguished; only the final side is tracked.
    - Falling actions do not track the side due to randomness.
    - Shake actions do not track the side due to unclear orientation.
  domain: automation
  author: golles
  source_url: https://raw.githubusercontent.com/golles/Home-Assistant-Config/main/blueprints/automation/golles/zigbee2mqtt_aqara_magic_cube.yaml
  input:
    cube:
      name: Magic Cube Device
      selector:
        device:
          integration: mqtt
          manufacturer: Aqara
          model: Cube
    side:
      name: Cube Side Entity
      description: Entity representing the current side of the cube (_side suffix).
      selector:
        entity:
          integration: mqtt
          domain: sensor

    fall:
      name: Action for Cube Drop
      description: Actions to execute when the cube is dropped.
      default: []
      selector:
        action: {}

    flip_side_0:
      name: Action for Flip to Side 0
      description: Actions to execute when the cube is flipped to side 0.
      default: []
      selector:
        action: {}
    flip_side_1:
      name: Action for Flip to Side 1
      description: Actions to execute when the cube is flipped to side 1.
      default: []
      selector:
        action: {}
    flip_side_2:
      name: Action for Flip to Side 2
      description: Actions to execute when the cube is flipped to side 2.
      default: []
      selector:
        action: {}
    flip_side_3:
      name: Action for Flip to Side 3
      description: Actions to execute when the cube is flipped to side 3.
      default: []
      selector:
        action: {}
    flip_side_4:
      name: Action for Flip to Side 4
      description: Actions to execute when the cube is flipped to side 4.
      default: []
      selector:
        action: {}
    flip_side_5:
      name: Action for Flip to Side 5
      description: Actions to execute when the cube is flipped to side 5.
      default: []
      selector:
        action: {}

    rotate_left_side_0:
      name: Rotate Left with Side 0 Up
      description: Actions to execute when the cube rotates left with side 0 facing up.
      default: []
      selector:
        action: {}
    rotate_left_side_1:
      name: Rotate Left with Side 1 Up
      description: Actions to execute when the cube rotates left with side 1 facing up.
      default: []
      selector:
        action: {}
    rotate_left_side_2:
      name: Rotate Left with Side 2 Up
      description: Actions to execute when the cube rotates left with side 2 facing up.
      default: []
      selector:
        action: {}
    rotate_left_side_3:
      name: Rotate Left with Side 3 Up
      description: Actions to execute when the cube rotates left with side 3 facing up.
      default: []
      selector:
        action: {}
    rotate_left_side_4:
      name: Rotate Left with Side 4 Up
      description: Actions to execute when the cube rotates left with side 4 facing up.
      default: []
      selector:
        action: {}
    rotate_left_side_5:
      name: Rotate Left with Side 5 Up
      description: Actions to execute when the cube rotates left with side 5 facing up.
      default: []
      selector:
        action: {}

    rotate_right_side_0:
      name: Rotate Right with Side 0 Up
      description: Actions to execute when the cube rotates right with side 0 facing up.
      default: []
      selector:
        action: {}
    rotate_right_side_1:
      name: Rotate Right with Side 1 Up
      description: Actions to execute when the cube rotates right with side 1 facing up.
      default: []
      selector:
        action: {}
    rotate_right_side_2:
      name: Rotate Right with Side 2 Up
      description: Actions to execute when the cube rotates right with side 2 facing up.
      default: []
      selector:
        action: {}
    rotate_right_side_3:
      name: Rotate Right with Side 3 Up
      description: Actions to execute when the cube rotates right with side 3 facing up.
      default: []
      selector:
        action: {}
    rotate_right_side_4:
      name: Rotate Right with Side 4 Up
      description: Actions to execute when the cube rotates right with side 4 facing up.
      default: []
      selector:
        action: {}
    rotate_right_side_5:
      name: Rotate Right with Side 5 Up
      description: Actions to execute when the cube rotates right with side 5 facing up.
      default: []
      selector:
        action: {}

    shake:
      name: Shake Action
      description: Actions to execute when the cube is shaken.
      default: []
      selector:
        action: {}

    slide_side_0:
      name: Slide with Side 0 Up
      description: Actions to execute when the cube slides with side 0 facing up.
      default: []
      selector:
        action: {}
    slide_side_1:
      name: Slide with Side 1 Up
      description: Actions to execute when the cube slides with side 1 facing up.
      default: []
      selector:
        action: {}
    slide_side_2:
      name: Slide with Side 2 Up
      description: Actions to execute when the cube slides with side 2 facing up.
      default: []
      selector:
        action: {}
    slide_side_3:
      name: Slide with Side 3 Up
      description: Actions to execute when the cube slides with side 3 facing up.
      default: []
      selector:
        action: {}
    slide_side_4:
      name: Slide with Side 4 Up
      description: Actions to execute when the cube slides with side 4 facing up.
      default: []
      selector:
        action: {}
    slide_side_5:
      name: Slide with Side 5 Up
      description: Actions to execute when the cube slides with side 5 facing up.
      default: []
      selector:
        action: {}

    tap_side_0:
      name: Tap with Side 0 Up
      description: Actions to execute when the cube is tapped with side 0 facing up.
      default: []
      selector:
        action: {}
    tap_side_1:
      name: Tap with Side 1 Up
      description: Actions to execute when the cube is tapped with side 1 facing up.
      default: []
      selector:
        action: {}
    tap_side_2:
      name: Tap with Side 2 Up
      description: Actions to execute when the cube is tapped with side 2 facing up.
      default: []
      selector:
        action: {}
    tap_side_3:
      name: Tap with Side 3 Up
      description: Actions to execute when the cube is tapped with side 3 facing up.
      default: []
      selector:
        action: {}
    tap_side_4:
      name: Tap with Side 4 Up
      description: Actions to execute when the cube is tapped with side 4 facing up.
      default: []
      selector:
        action: {}
    tap_side_5:
      name: Tap with Side 5 Up
      description: Actions to execute when the cube is tapped with side 5 facing up.
      default: []
      selector:
        action: {}

mode: queued
max: 5
max_exceeded: silent

triggers:
  - trigger: device
    domain: mqtt
    device_id: !input cube
    type: action
    subtype: fall
  - trigger: device
    domain: mqtt
    device_id: !input cube
    type: action
    subtype: flip180
  - trigger: device
    domain: mqtt
    device_id: !input cube
    type: action
    subtype: flip90
  - trigger: device
    domain: mqtt
    device_id: !input cube
    type: action
    subtype: rotate_left
  - trigger: device
    domain: mqtt
    device_id: !input cube
    type: action
    subtype: rotate_right
  - trigger: device
    domain: mqtt
    device_id: !input cube
    type: action
    subtype: shake
  - trigger: device
    domain: mqtt
    device_id: !input cube
    type: action
    subtype: slide
  - trigger: device
    domain: mqtt
    device_id: !input cube
    type: action
    subtype: tap

actions:
  - variables:
      payload: "{{ trigger.payload }}"
      side_entity: !input side
      side: "{{ states(side_entity) }}"

  - choose:
      - conditions: >-
          {{ payload == "fall" }}
        sequence: !input fall

      - conditions: >-
          {{ payload == "flip180" or payload == "flip90" }}
        sequence:
          - choose:
              - conditions: "{{ side == 0 }}"
                sequence: !input flip_side_0
              - conditions: "{{ side == 1 }}"
                sequence: !input flip_side_1
              - conditions: "{{ side == 2 }}"
                sequence: !input flip_side_2
              - conditions: "{{ side == 3 }}"
                sequence: !input flip_side_3
              - conditions: "{{ side == 4 }}"
                sequence: !input flip_side_4
              - conditions: "{{ side == 5 }}"
                sequence: !input flip_side_5

      - conditions: >-
          {{ payload == "rotate_left" }}
        sequence:
          - choose:
              - conditions: "{{ side == 0 }}"
                sequence: !input rotate_left_side_0
              - conditions: "{{ side == 1 }}"
                sequence: !input rotate_left_side_1
              - conditions: "{{ side == 2 }}"
                sequence: !input rotate_left_side_2
              - conditions: "{{ side == 3 }}"
                sequence: !input rotate_left_side_3
              - conditions: "{{ side == 4 }}"
                sequence: !input rotate_left_side_4
              - conditions: "{{ side == 5 }}"
                sequence: !input rotate_left_side_5

      - conditions: >-
          {{ payload == "rotate_right" }}
        sequence:
          - choose:
              - conditions: "{{ side == 0 }}"
                sequence: !input rotate_right_side_0
              - conditions: "{{ side == 1 }}"
                sequence: !input rotate_right_side_1
              - conditions: "{{ side == 2 }}"
                sequence: !input rotate_right_side_2
              - conditions: "{{ side == 3 }}"
                sequence: !input rotate_right_side_3
              - conditions: "{{ side == 4 }}"
                sequence: !input rotate_right_side_4
              - conditions: "{{ side == 5 }}"
                sequence: !input rotate_right_side_5

      - conditions: >-
          {{ payload == "shake" }}
        sequence: !input shake

      - conditions: >-
          {{ payload == "slide" }}
        sequence:
          - choose:
              - conditions: "{{ side == 0 }}"
                sequence: !input slide_side_0
              - conditions: "{{ side == 1 }}"
                sequence: !input slide_side_1
              - conditions: "{{ side == 2 }}"
                sequence: !input slide_side_2
              - conditions: "{{ side == 3 }}"
                sequence: !input slide_side_3
              - conditions: "{{ side == 4 }}"
                sequence: !input slide_side_4
              - conditions: "{{ side == 5 }}"
                sequence: !input slide_side_5

      - conditions: >-
          {{ payload == "tap" }}
        sequence:
          - choose:
              - conditions: "{{ side == 0 }}"
                sequence: !input tap_side_0
              - conditions: "{{ side == 1 }}"
                sequence: !input tap_side_1
              - conditions: "{{ side == 2 }}"
                sequence: !input tap_side_2
              - conditions: "{{ side == 3 }}"
                sequence: !input tap_side_3
              - conditions: "{{ side == 4 }}"
                sequence: !input tap_side_4
              - conditions: "{{ side == 5 }}"
                sequence: !input tap_side_5
