blueprint:
  name: Zigbee2MQTT - Xiaomi Aqara switch (WXKG11LM)
  description: |
    This button blueprint allows you to setup automatic for a bed light button, clicking the button will turn on/off
    the bed led, holding the button will turn on/off the ceiling light.
    This automation does require to setup light profiles, a light profile contains the color (in xy), birghtness 
    and a transition time. This makes the automation much simpler plus it allows you to maintain these states in a 
    general place. For more information about light profiles, you could check the documentation 
    https://www.home-assistant.io/integrations/light/
    This automation should work with any lights, but only with Philips Hue smart button connected throught Zigbee2MQTT.
  domain: automation
  source_url: https://raw.githubusercontent.com/golles/Home-Assistant-Blueprints/main/zigbee2mqtt_xiaomi_aqara_switch_WXKG11LM.yaml
  input:
    switch:
      name: Aqara switch
      description: Aqara switch to use (pick the sensor that end with _action).
      selector:
        entity:
          integration: mqtt
          domain: sensor
    single:
      name: Single press action
      description: Action to run on single press
      default: []
      selector:
        action: {}
    double:
      name: Double press action
      description: Action to run on double press
      default: []
      selector:
        action: {}
    triple:
      name: Triple press action
      description: Action to run on triple press
      default: []
      selector:
        action: {}
    quadruple:
      name: Quadruple press action
      description: Action to run on quadruple press
      default: []
      selector:
        action: {}
    hold:
      name: Hold action
      description: Action to run on hold
      default: []
      selector:
        action: {}

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input switch
    to:
      - "single"
      - "double"
      - "triple"
      - "quadruple"
      - "hold"
    
action:
  - variables:
      to_state: "{{ trigger.to_state.state }}"

  - choose:
    - conditions: "{{ to_state == 'single' }}"
      sequence: !input single

    - conditions: "{{ to_state == 'double' }}"
      sequence: !input double

    - conditions: "{{ to_state == 'triple' }}"
      sequence: !input triple

    - conditions: "{{ to_state == 'quadruple' }}"
      sequence: !input quadruple

    - conditions: "{{ to_state == 'hold' }}"
      sequence:
        repeat:
          sequence: 
            - choose:
              - conditions:
                  - "{{ true }}"
                sequence: !input hold
            - delay:
                seconds: 1
          until:
            - condition: state
              entity_id: !input switch
              state: "release"
