name: Question
description: You have a question related to my configuration
labels: [question]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Your question
      description: >-
        Describe your question, what you were trying to do and what happened.
        Provide a clear and concise description of what the problem is. What did you expect to happen?

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: If you have any additional information for us, use the field below. Please note, you can attach screenshots or screen recordings here, by dragging and dropping files in the field below.

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
