influxdb:
  host: influxdb
  port: 8086
  database: homeassistant
  include:
    domains:
      - climate
      - weather
    entity_globs:
      - sensor.*_illuminance # Xiaomi RTCGQ11LM
      - sensor.*_illuminance_lux # Xiaomi RTCGQ11LM
      - sensor.*_light_level # Hue motion
      - sensor.*_humidity # Xiaomi WSDCGQ11LM
      - sensor.*_pressure # Xiaomi WSDCGQ11LM
      - sensor.*_temperature # Xiaomi WSDCGQ11LM
      - sensor.dsmr_*
      - sensor.kamstrup_403_*
      - sensor.knmi_*
      - sensor.speedtest_*
      - sensor.watermeter_*

sensor:
  - platform: influxdb
    host: influxdb
    queries:
      - name: InfluxDb size
        unit_of_measurement: MB
        value_template: "{{ (value | float(0.0) / 1024 /1024) | round(1) }}"
        group_function: sum
        measurement: '"monitor"."shard"'
        database: _internal
        where: "time > now() - 10s"
        field: diskBytes
