recorder:
  db_url: !secret mariadb_connection
  purge_keep_days: 5
  exclude: 
    !include ../../db_excludes.yaml

sensor:
  - platform: sql
    db_url: !secret mariadb_connection
    queries:
      - name: MariaDB size
        query: >
          SELECT 
            table_schema, 
            ROUND(SUM(data_length + index_length) / 1024 / 1024, 0) AS "size" 
          FROM information_schema.TABLES
          WHERE table_schema="homeassistant"
          GROUP BY table_schema
        column: 'size'
        unit_of_measurement: MB
