automation:
  - id: notification_knmi
    alias: "Notificatie: KNMI waarschuwing"
    triggers:
      trigger: state
      entity_id: binary_sensor.knmi_waarschuwing
      from: "off"
      to: "on"
    actions:
      - if:
          - condition: state
            entity_id: media_player.lg_c9
            state: "on"
        then:
          - alias: Sent a notification to the tv
            action: notify.lg_c9
            data:
              message: >-
                {{state_attr("binary_sensor.knmi_waarschuwing", "title")}}
                {{state_attr("binary_sensor.knmi_waarschuwing", "description")}}

      - alias: Send the notification
        action: notify.discord
        data:
          message: ""
          target: !secret discord_weer
          data:
            embed:
              author:
                name: KNMI
                icon_url: https://brands.home-assistant.io/knmi/icon.png
              color: >-
                {% set state = state_attr("binary_sensor.knmi_waarschuwing", "code") %}
                {% if state == "groen" %} 3066993
                {% elif state == "geel" %} 16776960
                {% elif state == "oranje" %} 16753920
                {% elif state == "rood" %} 15158332
                {% else %} 16777215
                {% endif %}
              title: >-
                ⚠️ {{state_attr("binary_sensor.knmi_waarschuwing", "title")}}
              description: |
                {{state_attr("binary_sensor.knmi_waarschuwing", "description")}}

                https://www.knmi.nl/nederland-nu/weer/waarschuwingen/noord-holland
