sensor:
  - platform: rest
    name: Lokaal weer en verkeer
    scan_interval: 3600 # 60 * 60
    resource: https://ditisdesupercooleappapi.nhnieuws.nl/api/init/web
    value_template: OK
    json_attributes:
      - airQuality
      - timestamp
      - traffic
      - weatherDescription
      - weather
