binary_sensor:
  - platform: meteoalarm
    country: netherlands
    language: nl-NL
    province: Noord-Holland

automation:
  - id: notification_meteoalarm
    alias: "Notificatie: MeteoAlarm waarschuwing"
    triggers:
      trigger: state
      entity_id: binary_sensor.meteoalarm
      from: "off"
      to: "on"
    conditions:
      - "{{ state_attr('binary_sensor.meteoalarm', 'headline') != None }}"
      - "{{ state_attr('binary_sensor.meteoalarm', 'description') != None }}"
      - "{{ state_attr('binary_sensor.meteoalarm', 'instruction') != None }}"
    actions:
      - if:
          - condition: state
            entity_id: media_player.lg_c9
            state: "on"
        then:
          - alias: Sent a notification to the tv
            action: notify.lg_c9
            data:
              message: >-
                {{state_attr("binary_sensor.meteoalarm", "description")}}
                {{state_attr("binary_sensor.meteoalarm", "instruction")}}

      - alias: Send the notification
        action: notify.discord
        data:
          message: ""
          target: !secret discord_weer
          data:
            embed:
              author:
                name: MeteoAlarm
                icon_url: https://brands.home-assistant.io/meteoalarm/icon.png
              color: >-
                {% set state = state_attr("binary_sensor.meteoalarm", "code") %}
                {% if state == "2; yellow; Moderate" %} 16776960
                {% elif state == "3; orange; Severe" %} 16753920
                {% elif state == "4; red; High" %} 15158332
                {% else %} 3066993
                {% endif %}
              title: >-
                ⚠️ {{state_attr("binary_sensor.meteoalarm", "headline")}}
              description: |
                {{state_attr("binary_sensor.meteoalarm", "description")}}
                {{state_attr("binary_sensor.meteoalarm", "instruction")}}

                https://meteoalarm.org/nl/live/region/NL
