binary_sensor:
  - platform: meteoalarm
    country: netherlands
    language: nl-NL
    province: Noord-Holland

automation:
  - id: notification_meteoalarm
    alias: "Notificatie: MeteoAlarm waarschuwing"
    triggers:
      trigger: state
      entity_id: binary_sensor.meteoalarm
      from: "off"
      to: "on"
    conditions:
      - "{{ state_attr('binary_sensor.meteoalarm', 'headline') != None }}"
      - "{{ state_attr('binary_sensor.meteoalarm', 'description') != None }}"
      - "{{ state_attr('binary_sensor.meteoalarm', 'instruction') != None }}"
    actions:
      - alias: Send a notification
        action: >-
          {% if is_state("media_player.lg_c9", "on") %}
            notify.all_phones_and_tv
          {% else %}
            notify.all_phones
          {% endif %}
        data:
          title: >-
            ⚠️ {{state_attr("binary_sensor.meteoalarm", "headline")}}
          message: >-
            {{state_attr("binary_sensor.meteoalarm", "description")}}
            {{state_attr("binary_sensor.meteoalarm", "instruction")}}
          data:
            group: weather
