binary_sensor:
  - platform: meteoalarm
    country: netherlands
    language: nl-NL
    province: Noord-Holland

automation:
  - id: notification_meteoalarm
    alias: "Notificatie: MeteoAlarm waarschuwing"
    trigger:
      platform: state
      entity_id: binary_sensor.meteoalarm
      from: "off"
      to: "on"
    condition:
      - "{{ state_attr('binary_sensor.meteoalarm', 'headline') != None }}"
      - "{{ state_attr('binary_sensor.meteoalarm', 'description') != None }}"
      - "{{ state_attr('binary_sensor.meteoalarm', 'instruction') != None }}"
    action:
      - service: notify.all_phones_and_tv
        data:
          title: >-
            ⚠️ {{state_attr("binary_sensor.meteoalarm", "headline")}}
          message: >-
            {{state_attr("binary_sensor.meteoalarm", "description")}}
            {{state_attr("binary_sensor.meteoalarm", "instruction")}}
          data:
            group: weather
