sun:

sensor:
  - platform: template
    sensors:
      sun_sunrise:
        friendly_name: Zonsopkomst
        icon_template: mdi:weather-sunset-up
        value_template: >-
          {{ as_timestamp(state_attr('sun.sun', 'next_rising')) | timestamp_custom('%H:%M:%S') }}

      sun_sunset:
        friendly_name: Zonsondergang
        icon_template: mdi:weather-sunset-down
        value_template: >-
          {{ as_timestamp(state_attr('sun.sun', 'next_setting')) | timestamp_custom('%H:%M:%S') }}

      sun_position_house:
        friendly_name: Zon positie
        icon_template: mdi:weather-sunny-alert
        value_template: >-
          {% if state_attr('sun.sun', 'azimuth') > 105 and state_attr('sun.sun', 'azimuth') < 285 -%}
            Achter
          {%- else -%}
            Voor
          {%- endif %}
