# My default theme.
#
# This theme is extending Mushroom Shadow, to make the Mushroom cards make look more similar to standard cards, like the tile card.

Standaard:
  # Home Assistant override
  ha-card-box-shadow: 0px 2px 4px 0px rgba(0,0,0,0.16)
  ha-card-border-width: 0
  # Card override
  mush-card-primary-font-size: 14px
  mush-card-secondary-font-size: 12px
  mush-card-primary-font-weight: 500
  mush-card-secondary-font-weight: 400
  modes:
      light: {}
      dark: {}