#!/usr/bin/env bash

set -e

# Make the parent dir, the working directory.
cd "$(dirname "$0")/.."

echo -n > secrets.yaml

grep "\!secret " -r -i --include \*.yaml --include \*.yaml --exclude-dir=.github --exclude-dir=.vscode . | while read -r line ; do
    secret=$(echo ${line} | awk '{if(/secret/) print $4}')
    value="value0123"
    if [[ $secret == *_ip ]]
    then
        value="10.0.0.12"
    elif [[ $secret == *_mac ]]
    then
        value="00:00:00:00:00:00"
    elif [[ $secret == *_url ]]
    then
        value="https://foo.bar"
    elif [[ $secret == network_subnet ]]
    then
        value="10.0.0.0/8"
    elif [[ $secret == fan_token ]]
    then
        value="12345678901234567890123456789012"
    elif [[ $secret == telegram_bot_api_key ]]
    then
        value="abcdefghijklmnopqrstuvwxyz"
    elif [[ $secret == telegram_* ]]
    then
        value="1234567890"
    fi

    if [[ ! $(grep -R "${secret}" secrets.yaml) ]]
    then
        echo "${secret}: ${value}" >> secrets.yaml
    fi
done
