automation:
  - id: adguardhome_protection_switches
    alias: "AdGuard Home: Bescherming schakelaars"
    mode: single
    trigger:
      - platform: state
        entity_id: switch.adguard_home_primary_bescherming
        to:
          - "on"
          - "off"
    action:
      - if:
          - condition: state
            entity_id: switch.adguard_home_primary_bescherming
            state: "on"
        then:
          - alias: Turn the 2nd instance on
            service: switch.turn_on
            target:
              entity_id: switch.adguard_home_secondary_bescherming
        else:
          - alias: Turn the 2nd instance off
            service: switch.turn_off
            target:
              entity_id: switch.adguard_home_secondary_bescherming
