sensor:
  - platform: afvalbeheer
    wastecollector: !secret wastecollector
    resources:
      - restafval
      - gft
      - papier
    postcode: !secret postcode
    streetnumber: !secret streetnumber
    dutch: 1
    disableicons: 1

homeassistant:
  customize:
    sensor.purmerend_restafval:
      friendly_name: Restafval
      entity_picture: /local/afval/purmerend_restafval.jpg
    sensor.purmerend_papier:
      friendly_name: Papier
      entity_picture: /local/afval/purmerend_papier.jpg
    sensor.purmerend_gft:
      friendly_name: GFT
      entity_picture: /local/afval/purmerend_gft.jpg
    
automation:
  - id: notification_afval
    alias: "Notificatie: Afval wordt morgen opgehaald"
    initial_state: on
    mode: single
    variables:
      entity: >-
        {{ 
          states.sensor 
            | selectattr("attributes.Wastecollector", "defined")
            | selectattr("attributes.Days_until", "eq", 1)
            | map(attribute="entity_id")
            | first
            | default("none")
        }}
    trigger:
      platform: time
      at: "19:30:00"
    condition:
      - condition: template
        value_template: >-
          {{ entity != "none" }}
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - variables:
          external_url: !secret external_url

      - service: notify.sander
        data:
          title: Afval
          message: >-
            Morgen wordt de {{ state_attr(entity, "friendly_name") | upper }} container geleegd.
          data:
            group: afval
            image: >-
              {{ external_url }}{{ state_attr(entity, "entity_picture") }}
            url: /dashboard-buiten/buurt
