sensor:
  - platform: afvalbeheer
    wastecollector: !secret wastecollector
    resources:
      - restafval
      - gft
      - papier
    postcode: !secret postcode
    streetnumber: !secret streetnumber
    dutch: 1
    disableicons: 1

homeassistant:
  customize:
    sensor.purmerend_restafval:
      friendly_name: "Restafval"
      entity_picture: "/local/afval/purmerend_restafval.jpg"
    sensor.purmerend_papier:
      friendly_name: "Papier"
      entity_picture: "/local/afval/purmerend_papier.jpg"
    sensor.purmerend_gft:
      friendly_name: "GFT"
      entity_picture: "/local/afval/purmerend_gft.jpg"
    
automation:
  - id: afval_notification
    alias: Melding voor afval
    initial_state: on
    trigger:
      platform: time
      at: "19:30:00"
    condition:
      condition: or
      conditions:
        - condition: template
          value_template: '{{ is_state_attr("sensor.purmerend_papier", "Days-until", 1) }}'
        - condition: template
          value_template: '{{ is_state_attr("sensor.purmerend_gft", "Days-until", 1) }}'
        - condition: template
          value_template: '{{ is_state_attr("sensor.purmerend_restafval", "Days-until", 1) }}'
    action:
      - service: notify.sander
        data:
          title: Afval
          message: >
            {% if is_state_attr("sensor.purmerend_papier", "Days-until", 1) %}
            Morgen wordt de PAPIER container (groen) geleegd
            {% elif is_state_attr("sensor.purmerend_gft", "Days-until", 1)%}
            Morgen wordt de GFT container (bruin) geleegd
            {% elif is_state_attr("sensor.purmerend_restafval", "Days-until", 1) %}
            Morgen wordt de RESTAFVAL container (grijs) geleegd
            {% endif %}
