alarm_control_panel:
  - platform: manual
    name: Huis alarm
    arming_time: 30
    delay_time: 30
    trigger_time: 300
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

automation:
  - id: alarm_auto_on_off
    alias: Alarm - Automatisch aan/uit bij aanwezigheid
    mode: single
    trigger:
      - platform: state
        entity_id: group.residents
        to: 
          - home
          - not_home
    action:
      - choose:
        - conditions:
            - condition: state
              entity_id: group.residents
              state: not_home
          sequence:
            - alias: Set the alarm to arm away
              service: alarm_control_panel.alarm_arm_away
              entity_id: alarm_control_panel.huis_alarm
        default:
          - alias: Disarm the alarm
            service: alarm_control_panel.alarm_disarm
            entity_id: alarm_control_panel.huis_alarm


  - id: alarm_attic_stairs
    alias: Alarm - Zoldertrap sensor uitzetten als de balkondeur open is
    description: |
      Als de balkondeur open is, mag de zoldertrap sensor het alarm niet triggeren.
      Dit gebeurt bijvoorbeeld als er was aan het drogen is (op het dak).
    mode: single
    trigger:
      - platform: state
        entity_id: alarm_control_panel.huis_alarm
        to:
          - armed_away
          - disarmed
    action:
      - choose:
        - conditions:
            - condition: state
              entity_id: alarm_control_panel.huis_alarm
              state: armed_away
            - condition: state
              entity_id: binary_sensor.balkondeur_contact
              state: "on"
          sequence:
            - alias: Disable the motion sensor
              service: switch.turn_off
              entity_id: switch.zoldertrap_sensor_motion
        default:
          - alias: Enable the motion sensor
            service: switch.turn_n
            entity_id: switch.zoldertrap_sensor_motion

  # - id: alarm_trigger_lights
  #   alias: Alarm - Melding in huis
  #   mode: single
  #   trigger:
  #     - platform: state
  #       entity_id: alarm_control_panel.huis_alarm
  #       from: pending
  #       to: triggered
  #   action:
  #     - alias: Set up variables for the actions
  #       variables:
  #         # lights_flash: "light.keuken, light.tv"
  #         lights_flash: >-
  #           {{
  #             states.light 
  #             | selectattr("attributes.is_hue_group", "equalto", true)
  #             | selectattr("attributes.supported_color_modes", "equalto", ["color_temp", "hs"]) 
  #             | map(attribute='entity_id')
  #             | join(', ')
  #           }}

  #     - alias: Store the current light state
  #       service: scene.create
  #       data:
  #         scene_id: before_alarm_trigger
  #         snapshot_entities: "{{ lights_flash }}"

  #     - alias: Turn on lights
  #       service: light.turn_on
  #       target:
  #         entity_id: "{{ lights_flash }}"

  #     - alias: Wait 1 second before we start flashing
  #       delay: 1

  #     - alias: Flash lights
  #       service: light.turn_on
  #       data:
  #         brightness: 255
  #         rgb_color: [255, 0, 0]
  #         flash: long
  #       target:
  #         entity_id: "{{ lights_flash }}"
      
  #     - alias: Wait untill the alarm is no longer triggered
  #       wait_for_trigger:
  #         platform: state
  #         entity_id: alarm_control_panel.huis_alarm
  #         from: triggered

  #     - alias: Restore lights to previous state
  #       service: scene.turn_on
  #       data:
  #         entity_id: scene.before_alarm_trigger

  - id: alarm_system
    alias: Alarm - Melding bij beweging
    description: |
      Alarm systeem
      Deze automation triggert bewust vele notificaties, namelijk voor alle deuren en ramen die open gaan
      en ook voor alle bewegingssensoren die beweging detecteren.
    mode: restart
    trigger:
      - platform: state
        entity_id:
          # Deur/raam sensoren:
          # Begaande grond.
          - binary_sensor.achterdeur_contact
          - binary_sensor.achterraam_contact
          - binary_sensor.keukenraam_contact
          - binary_sensor.voordeur_contact
          - binary_sensor.voorraadkastdeur_contact
          # Eerste verdieping.
          - binary_sensor.slaapkamerraam_contact
          - binary_sensor.kledingkamerraam_contact
          - binary_sensor.badkamerraam_contact
          - binary_sensor.logeerkamerraam_contact
          # Tweede verdieping.
          - binary_sensor.balkondeur_contact
          - binary_sensor.zolderraam_contact

          # Bewegingssensoren:
          # Begaande grond.
          - binary_sensor.woonkamer_beweging_1_occupancy
          - binary_sensor.woonkamer_beweging_2_occupancy
          - binary_sensor.hal_sensor_motion
          - binary_sensor.toilet_beweging_occupancy
          - binary_sensor.overloop_sensor_1_motion
          # Eerste verdieping.
          - binary_sensor.overloop_sensor_2_motion
          - binary_sensor.kledingkamer_beweging_motion
          - binary_sensor.badkamer_beweging_motion
          - binary_sensor.logeerkamer_beweging_occupancy
          - binary_sensor.slaapkamer_beweging_occupancy
          # Tweede verdieping.
          - binary_sensor.zoldertrap_beweging_motion
          - binary_sensor.zolder_beweging_1_occupancy
          - binary_sensor.zolder_beweging_2_occupancy
        to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.huis_alarm
        state: 
          - armed_away
          - pending
          - triggered
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - alias: Set up variables for the actions
        variables:
          # Including an id in the action allows us to identify this script run and not accidentally trigger for other notification actions.
          action_disarm_alarm: >-
            {{ "DISARM_ALARM_" ~ context.id }}
          area_name : >-
            {{ area_name(trigger.entity_id) }}
          trigger_friendly_name: >-
            {{ 
              state_attr(trigger.entity_id, "friendly_name")
              | replace(" occupancy", "")
              | replace(" motion", "")
              | replace(" contact", "")
              | replace(" beweging", " bewegingssensor")
              | replace(" sensor", " bewegingssensor")
            }}
          trigger_device_class: >-
            {{ state_attr(trigger.entity_id, "device_class") }}
          message: >-
            Beweging in de {{ area_name }},
            {% if trigger_device_class == "door" %}
              {{ trigger_friendly_name }} is geopend
            {% elif trigger_device_class == "window" %}
              {{ trigger_friendly_name }} is geopend
            {% elif trigger_device_class == "motion" %}
              {{ trigger_friendly_name }} heeft beweging gedetecteerd 
            {% endif %}

      - alias: Trigger the alarm
        service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.huis_alarm

      - alias: Notify user and ask to disarm
        service: notify.all_phones
        data:
          title: 🚨🚨🚨 Alarm
          message: >-
            {{ message }}
          data:
            actions:
              - action: "{{ action_disarm_alarm }}"
                title: Zet alarm uit
            url: /dashboard-status/alarm
            push:
              interruption-level: critical
              sound: alarm.caf

      - alias: Wait for a response
        wait_for_trigger:
          - platform: event
            event_type: mobile_app_notification_action
            event_data:
              action: "{{ action_disarm_alarm }}"

      - alias: Perform the action
        choose:
          - conditions: "{{ wait.trigger.event.data.action == action_disarm_alarm }}"
            sequence:
              - service: alarm_control_panel.alarm_disarm
                entity_id: alarm_control_panel.huis_alarm
