template:
  - binary_sensor:
      - name: Aquarium status
        icon: mdi:fishbowl-outline
        state: >
          {{ is_state("light.aquarium_licht", "on") }}
        attributes:
          modus: >
            {% set translations = {
              "manual": "Handmatig",
              "automatic": "Automatisch",
              "dynamic": "Dynamisch"
            } %}
            {{ translations.get(state_attr("light.aquarium_licht", "light_mode"), state_attr("light.aquarium_licht", "light_mode")) }}
          temperatuur: >
            {{ states("sensor.aquarium_watertemperatuur") }} °C
        availability: >
          {{ states("light.aquarium_licht") not in ("unknown", "unavailable") }}

  - button:
      - name: Aquarium schema
        press:
          action: ori.set_schedule
          data:
            device_id: 753a24aab6441d1d21381fa051beb10e
            schedule:
              - 8,59,0,0,0,0,0 # Nacht
              - 9,0,20,20,20,25,25 # Zachte zonsopkomst
              - 10,0,50,35,35,40,55 # Snellere opbouw
              - 12,0,85,50,45,55,85 # Duidelijke piek
              - 15,0,85,50,45,55,85 # Piek vasthouden
              - 16,0,70,40,40,45,70 # Afbouw start
              - 17,0,50,30,30,35,50 # Avondlicht
              - 18,0,30,20,20,25,30 # Schemer
              - 19,0,0,0,0,0,0 # Nacht

      - name: Aquarium schema met maanlicht
        press:
          action: ori.set_schedule
          data:
            device_id: 753a24aab6441d1d21381fa051beb10e
            schedule:
              - 8,59,0,0,0,0,0 # Nacht
              - 9,0,20,20,20,25,25 # Zachte zonsopkomst
              - 10,0,50,35,35,40,55 # Snellere opbouw
              - 12,0,85,50,45,55,85 # Duidelijke piek
              - 15,0,85,50,45,55,85 # Piek vasthouden
              - 16,0,70,40,40,45,70 # Afbouw start
              - 17,0,50,30,30,35,50 # Avondlicht
              - 18,0,30,20,20,25,30 # Schemer
              - 19,0,0,0,0,0,0 # Nacht
              - 20,0,10,0,0,10,0 # Maanlicht
              - 23,0,0,0,0,0,0 # Nacht

automation:
  - id: aquarium_monitoring_alert
    alias: "Notificatie: Aquarium monitoring"
    mode: parallel
    triggers:
      - trigger: numeric_state
        entity_id: sensor.aquarium_watertemperatuur
        above: 30
        for:
          minutes: 5
        variables:
          alert_message: Watertemperatuur is te hoog, -STATE-°C
      - trigger: numeric_state
        entity_id: sensor.aquarium_watertemperatuur
        below: 22
        for:
          minutes: 5
        variables:
          alert_message: Watertemperatuur is te laag, -STATE-°C
      - trigger: state
        entity_id: switch.aquarium_verlichting_plug
        to: "off"
        for:
          minutes: 60
        variables:
          alert_message: Verlichting is al een tijd uit
      - trigger: state
        entity_id: switch.aquarium_pomp_plug
        to: "off"
        for:
          minutes: 60
        variables:
          alert_message: Filter is al een tijd uit
      - trigger: state
        entity_id: switch.aquarium_verwarming_plug
        to: "off"
        for:
          minutes: 60
        variables:
          alert_message: Verwarming is al een tijd uit
      - trigger: state
        entity_id: switch.aquarium_skimmer_plug
        to: "off"
        for:
          minutes: 60
        variables:
          alert_message: Skimmer is al een tijd uit
      - trigger: state
        entity_id: binary_sensor.aquarium_pomp_lekkage_water_leak
        to: "on"
        variables:
          alert_message: Lekkage bij het filter gedetecteerd
      - trigger: state
        entity_id: light.aquarium_licht
        attribute: effect
        not_to: automatic
        for:
          minutes: 120
        variables:
          alert_message: Verlichting staat niet op automatisch
    actions:
      - alias: Send the notification
        action: notify.sander
        data:
          title: 🐠 Aquarium
          message: |
            {{ alert_message | replace('-STATE-', states(trigger.entity_id)) }}
          data:
            group: aquarium
            url: /dashboard-status/aquarium
            push:
              interruption-level: critical

  - id: aquarium_buttons
    alias: Aquarium - Knoppen
    mode: single
    triggers:
      - trigger: device
        domain: mqtt
        device_id: bec06935fe26cb7ae7140f1ed8ac9eb2
        type: action
        subtype: on_press
      - trigger: device
        domain: mqtt
        device_id: bec06935fe26cb7ae7140f1ed8ac9eb2
        type: action
        subtype: off_press
      - trigger: device
        domain: mqtt
        device_id: bec06935fe26cb7ae7140f1ed8ac9eb2
        type: action
        subtype: down_press
      - trigger: device
        domain: mqtt
        device_id: bec06935fe26cb7ae7140f1ed8ac9eb2
        type: action
        subtype: up_press
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.payload == 'on_press' }}"
            sequence:
              - if:
                  - condition: state
                    entity_id: light.aquarium_licht
                    attribute: effect
                    state: automatic
                then:
                  - alias: Set the light to manual mode
                    action: light.turn_on
                    target:
                      entity_id: light.aquarium_licht
                    data:
                      effect: manual
                  - alias: Set the light bright for maintenance
                    action: light.turn_on
                    target:
                      entity_id: light.aquarium_licht
                    data:
                      brightness: 255
                      rgbw_color: [255, 255, 255, 255]
                else:
                  - alias: Set the light to automatic mode
                    action: light.turn_on
                    target:
                      entity_id: light.aquarium_licht
                    data:
                      effect: automatic

          - conditions:
              - condition: template
                value_template: "{{ trigger.payload == 'off_press' }}"
            sequence:
              - if:
                  - condition: state
                    entity_id: switch.aquarium_pomp_plug
                    state: "on"
                then:
                  - alias: Turn off the heater and pump
                    action: switch.turn_off
                    target:
                      entity_id:
                        - switch.aquarium_verwarming_plug
                        - switch.aquarium_pomp_plug
                else:
                  - alias: Turn on the heater and pump
                    action: switch.turn_on
                    target:
                      entity_id:
                        - switch.aquarium_pomp_plug
                        - switch.aquarium_verwarming_plug

          - conditions:
              - condition: template
                value_template: "{{ trigger.payload == 'up_press' }}"
            sequence:
              - if:
                  - condition: state
                    entity_id: switch.aquarium_luchtpomp_plug
                    state: "on"
                then:
                  - alias: Turn off air pump
                    action: switch.turn_off
                    target:
                      entity_id:
                        - switch.aquarium_luchtpomp_plug
                else:
                  - alias: Turn on air pump
                    action: switch.turn_on
                    target:
                      entity_id:
                        - switch.aquarium_luchtpomp_plug

          - conditions:
              - condition: template
                value_template: "{{ trigger.payload == 'down_press' }}"
            sequence:
              - if:
                  - condition: state
                    entity_id: switch.aquarium_skimmer_plug
                    state: "on"
                then:
                  - alias: Turn off skimmer
                    action: switch.turn_off
                    target:
                      entity_id:
                        - switch.aquarium_skimmer_plug
                else:
                  - alias: Turn on skimmer
                    action: switch.turn_on
                    target:
                      entity_id:
                        - switch.aquarium_skimmer_plug

  - id: garnalen_bak_verlichting
    alias: Aquarium - Garnalen bak verlichting
    mode: single
    triggers:
      - trigger: time
        at: "09:00:00"
        id: aan
      - trigger: time
        at: "19:00:00"
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id: aan
            sequence:
              - alias: Turn on garnalen bak verlichting
                action: switch.turn_on
                entity_id: switch.garnalenbak_verlichting
        default:
          - alias: Turn off garnalen bak verlichting
            action: switch.turn_off
            entity_id: switch.garnalenbak_verlichting
