input_text:
  borg:
    name: Borg backup status
    initial: Backup and Prune finished successfully
    icon: mdi:cloud-upload

automation:
  - id: borg_webhook
    alias: Borg backup webhook
    mode: restart
    triggers:
      - trigger: webhook
        webhook_id: borg
        allowed_methods:
          - POST
        local_only: true
    actions:
      - action: input_text.set_value
        data_template:
          entity_id: input_text.borg
          value: "{{ trigger.json.status }}"

  - id: notification_borg_warning
    alias: "Notificatie: Borg backup waarschuwing"
    mode: restart
    triggers:
      - trigger: state
        entity_id: input_text.borg
        for:
          minutes: 30
    conditions:
      - "{{ states('input_text.borg') == 'Backup and/or Prune finished with errors' }}"
    actions:
      - alias: Send the notification
        action: notify.discord
        data:
          message: ""
          target: !secret discord_monitoring
          data:
            embed:
              color: 15158332 # Red
              title: Borg backup
              description: |
                Backup is niet goed gegaan.
                Laatste status: `{{ states('input_text.borg') }}`
