camera:
  - platform: mjpeg
    name: dlink
    mjpeg_url: !secret dlink_camera_mjpeg_url
    still_image_url: !secret dlink_camera_still_image_url
    username: !secret dlink_camera_username
    password: !secret dlink_camera_password

automation:
- id: dlink_auto_day_night_mode # TODO: this should happen based on light in that place.
  alias: Automatisch Dlink camera in day of night mode zetten
  initial_state: on
  trigger:
    - platform: homeassistant
      event: start
    - platform: sun
      event: sunrise
    - platform: sun
      event: sunset
  action:
    - choose:
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: 'below_horizon'
        sequence:
          - service: shell_command.dlink_set_night_mode
            data:
              host: !secret dlink_camera_host
              username: !secret dlink_camera_username
              password: !secret dlink_camera_password
      default:
        - service: shell_command.dlink_set_day_mode
          data:
            host: !secret dlink_camera_host
            username: !secret dlink_camera_username
            password: !secret dlink_camera_password

shell_command:
  dlink_set_day_mode: '/config/custom_scripts/dlink_day_night.sh "{{ host }}" "{{ username }}" "{{ password }}" day'
  dlink_set_night_mode: '/config/custom_scripts/dlink_day_night.sh "{{ host }}" "{{ username }}" "{{ password }}" night'