automation:
  - id: dlink_auto_day_night_mode
    alias: Automatisch Dlink camera in day of night mode zetten
    mode: single
    triggers:
      - trigger: numeric_state
        entity_id: sensor.epl_eettafel_illuminance
        below: 2.2
        for:
          minutes: 10
      - trigger: numeric_state
        entity_id: sensor.epl_eettafel_illuminance
        above: 3
        for:
          minutes: 10
    actions:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.epl_eettafel_illuminance
                below: 2.2
            sequence:
              - action: shell_command.dlink_set_night_mode
                data:
                  host: !secret dlink_camera_host
                  username: !secret dlink_camera_username
                  password: !secret dlink_camera_password
        default:
          - action: shell_command.dlink_set_day_mode
            data:
              host: !secret dlink_camera_host
              username: !secret dlink_camera_username
              password: !secret dlink_camera_password

shell_command:
  dlink_set_day_mode: '/config/custom_scripts/dlink_day_night.sh "{{ host }}" "{{ username }}" "{{ password }}" day'
  dlink_set_night_mode: '/config/custom_scripts/dlink_day_night.sh "{{ host }}" "{{ username }}" "{{ password }}" night'
