binary_sensor:
  - platform: car_wash
    name: Auto wassen
    weather: weather.knmi_purmerend

command_line:
  - sensor:
      name: CarwashPlus Saldo
      unique_id: carwashplus_saldo
      icon: mdi:currency-eur
      scan_interval: 10800
      command: !secret carwashplus_command # "python custom_scripts/carwashplus.py 'email' 'password'"
      command_timeout: 120
      value_template: "{{ value_json.saldo }}"
      json_attributes:
        - Pasnummer
      unit_of_measurement: €
      device_class: monetary
  - sensor:
      name: CarwashPlus Laatste bezoek
      unique_id: carwashplus_laatste_bezoek
      icon: mdi:car-wash
      scan_interval: 10800
      command: !secret carwashplus_command # "python custom_scripts/carwashplus.py 'email' 'password'"
      command_timeout: 120
      value_template: "{{ value_json.laatste_bezoek }}"
      json_attributes:
        - vestiging
        - product
        - bedrag
      device_class: timestamp
