climate:
  - platform: generic_thermostat
    name: Elektrische kachel
    heater: switch.elektrische_kachel_plug
    target_sensor: sensor.logeerkamer_temperature
    min_temp: 5
    max_temp: 25
    initial_hvac_mode: "off"
    away_temp: 5
    home_temp: 19
    precision: 0.5

template:
  - button:
      - name: Woonkamer opwarmen
        icon: mdi:radiator
        press:
          - action: tado_ce.set_climate_timer
            data:
              time_period: "00:15:00"
              temperature: 25
            target:
              entity_id: climate.woonkamer

      - name: Slaapkamer opwarmen
        icon: mdi:radiator
        press:
          - action: tado_ce.set_climate_timer
            data:
              time_period: "00:15:00"
              temperature: 25
            target:
              entity_id: climate.slaapkamer

      - name: Kledingkamer opwarmen
        icon: mdi:radiator
        press:
          - action: tado_ce.set_climate_timer
            data:
              time_period: "00:15:00"
              temperature: 25
            target:
              entity_id: climate.kledingkamer

      - name: Logeerkamer opwarmen
        icon: mdi:radiator
        press:
          - action: tado_ce.set_climate_timer
            data:
              time_period: "00:15:00"
              temperature: 25
            target:
              entity_id: climate.logeerkamer

      - name: Badkamer opwarmen
        icon: mdi:radiator
        press:
          - action: tado_ce.set_climate_timer
            data:
              time_period: "00:15:00"
              temperature: 25
            target:
              entity_id: climate.badkamer

      - name: Zolder opwarmen
        icon: mdi:radiator
        press:
          - action: tado_ce.set_climate_timer
            data:
              time_period: "00:15:00"
              temperature: 25
            target:
              entity_id: climate.zolder

  - sensor:
      - name: Binnen temperatuur
        icon: mdi:thermometer
        state: >-
          {%
            set temps = states.climate
            | rejectattr("state", "in", ["unavailable", "unknown"])
            | rejectattr("attributes.current_temperature", "none")
            | map(attribute="attributes.current_temperature")
            | sort
          %}
          {% if -1 < temps[0] - temps[-1] < 1 %}
            {{ temps[-1] ~ " °C" }}
          {% else %}
            {{ temps[0] ~ " - " ~ temps[-1] ~ " °C" }}
          {% endif %}
        availability: >-
          {%
            set temps = states.climate
            | rejectattr("state", "in", ["unavailable", "unknown"])
            | rejectattr("attributes.current_temperature", "none")
            | map(attribute="attributes.current_temperature")
            | sort
          %}
          {{ temps | count > 2 }}

  - switch:
      - name: Tado thuismodus
        icon: >
          {% if is_state("select.tado_ce_presence_mode", "Home") %}
            mdi:radiator
          {% else %}
            mdi:radiator-off
          {% endif %}
        state: >
          {{ is_state("select.tado_ce_presence_mode", "Home") }}
        turn_on:
          action: select.select_option
          data:
            option: Home
          target:
            entity_id: select.tado_ce_presence_mode
        turn_off:
          action: select.select_option
          data:
            option: Away
          target:
            entity_id: select.tado_ce_presence_mode

automation:
  - id: tado_auto_home_and_away_mode
    alias: Tado - Automatisch home en away mode activeren
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: state
        entity_id: group.residents
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: group.residents
                state: not_home
            sequence:
              - alias: Set climate preset mode to away
                action: select.select_option
                data:
                  option: Away
                target:
                  entity_id: select.tado_ce_presence_mode

              - alias: Turn electric heater off
                action: climate.turn_off
                target:
                  entity_id: climate.elektrische_kachel
        default:
          - alias: Set climate preset mode to home
            action: select.select_option
            data:
              option: Home
            target:
              entity_id: select.tado_ce_presence_mode

  - id: tado_preheat_going_home_cold_day
    alias: Tado - Huis opwarmen op een koude dag naar huis gaan
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: numeric_state
        entity_id: sensor.huis_nearest_distance
        below: 10
    conditions:
      - condition: state
        entity_id: group.residents
        state: not_home
      - condition: state
        entity_id: sensor.huis_nearest_direction_of_travel
        state: towards
      - condition: numeric_state
        entity_id: climate.woonkamer
        attribute: current_temperature
        below: 18
    actions:
      - alias: Send the notification
        action: notify.discord
        data:
          message: ""
          target: !secret discord_algemeen
          data:
            embed:
              title: Verwarming
              description: |
                Ik zie dat {{ states("sensor.huis_nearest_device") }} bijna thuis is
                Het is hier nu nog koud, dus ik verwarm de woonkamer alvast

      - alias: Heat up the living room for a short time
        action: tado_ce.set_climate_timer
        data:
          time_period: "00:15:00"
          temperature: 25
        target:
          entity_id: climate.woonkamer
