homeassistant:
  customize:
    "binary_sensor.ru1141249024_battery_state":
      friendly_name: Thermostaat batterij
    "binary_sensor.ru1141249024_connection_state":
      friendly_name: Thermostaat verbinding
    "binary_sensor.va1805654016_battery_state":
      friendly_name: Woonkamer batterij
    "binary_sensor.va1805654016_connection_state":
      friendly_name: Woonkamer verbinding
    "binary_sensor.va1923094528_battery_state":
      friendly_name: Woonkamer batterij
    "binary_sensor.vva1923094528_connection_state":
      friendly_name: Woonkamer verbinding
    "binary_sensor.va3030325248_battery_state":
      friendly_name: Woonkamer batterij
    "binary_sensor.va3030325248_connection_state":
      friendly_name: Woonkamer verbinding
    "binary_sensor.va2677479424_battery_state":
      friendly_name: Slaapkamer batterij
    "binary_sensor.va2677479424_connection_state":
      friendly_name: Slaapkamer verbinding
    "binary_sensor.va3382122496_battery_state":
      friendly_name: Kledingkamer batterij
    "binary_sensor.va3382122496_connection_state":
      friendly_name: Kledingkamer verbinding
    "binary_sensor.va4103542784_battery_state":
      friendly_name: Logeerkamer batterij
    "binary_sensor.va4103542784_connection_state":
      friendly_name: Logeerkamer verbinding
    "binary_sensor.va1788876800_battery_state":
      friendly_name: Badkamer batterij
    "binary_sensor.va1788876800_connection_state":
      friendly_name: Badkamer verbinding
    "binary_sensor.va2979272704_battery_state":
      friendly_name: Zolder batterij
    "binary_sensor.va2979272704_connection_state":
      friendly_name: Zolder verbinding

switch:
  - platform: template
    switches:
      tado_home_mode:
        friendly_name: Tado thuismodus
        icon_template: >
          {% if is_state_attr('climate.woonkamer', 'preset_mode', 'home') %}
            mdi:radiator
          {% else %}
            mdi:radiator-off
          {% endif %}
        value_template: >
          {{ is_state_attr('climate.woonkamer', 'preset_mode', 'home') }}
        turn_on:
          service: climate.set_preset_mode
          data:
            entity_id: climate.woonkamer
            preset_mode: home
        turn_off:
          service: climate.set_preset_mode
          data:
            entity_id: climate.woonkamer
            preset_mode: away
  
automation:
  - id: tado_auto_home_and_away_mode
    alias: Tado automatisch home en away mode activeren
    initial_state: on
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: group.residents
    action:
      - choose:
        - conditions:
            - condition: state
              entity_id: group.residents
              state: not_home
          sequence:
            - service: switch.turn_off
              entity_id: switch.tado_home_mode
        default:
          - service: switch.turn_on
            entity_id: switch.tado_home_mode
