homeassistant:
  customize:
    "binary_sensor.ru1141249024_batterij":
      friendly_name: Thermostaat batterij
    "binary_sensor.ru1141249024_connectiestatus":
      friendly_name: Thermostaat verbinding
    "binary_sensor.va1805654016_batterij":
      friendly_name: Woonkamer batterij
    "binary_sensor.va1805654016_connectiestatus":
      friendly_name: Woonkamer verbinding
    "binary_sensor.va1923094528_batterij":
      friendly_name: Woonkamer batterij
    "binary_sensor.va1923094528_connectiestatus":
      friendly_name: Woonkamer verbinding
    "binary_sensor.va3030325248_batterij":
      friendly_name: Woonkamer batterij
    "binary_sensor.va3030325248_connectiestatus":
      friendly_name: Woonkamer verbinding
    "binary_sensor.va2677479424_batterij":
      friendly_name: Slaapkamer batterij
    "binary_sensor.va2677479424_connectiestatus":
      friendly_name: Slaapkamer verbinding
    "binary_sensor.va3382122496_batterij":
      friendly_name: Kledingkamer batterij
    "binary_sensor.va3382122496_connectiestatus":
      friendly_name: Kledingkamer verbinding
    "binary_sensor.va4103542784_batterij":
      friendly_name: Logeerkamer batterij
    "binary_sensor.va4103542784_connectiestatus":
      friendly_name: Logeerkamer verbinding
    "binary_sensor.va1788876800_batterij":
      friendly_name: Badkamer batterij
    "binary_sensor.va1788876800_connectiestatus":
      friendly_name: Badkamer verbinding
    "binary_sensor.va2979272704_batterij":
      friendly_name: Zolder batterij
    "binary_sensor.va2979272704_connectiestatus":
      friendly_name: Zolder verbinding

climate:
  - platform: generic_thermostat
    name: Elektrische kachel
    heater: switch.elektrische_kachel_plug
    target_sensor: sensor.logeerkamer_temperatuur
    min_temp: 5
    max_temp: 25
    initial_hvac_mode: "off"
    away_temp: 5
    home_temp: 19
    precision: 0.5

switch:
  - platform: template
    switches:
      tado_home_mode:
        friendly_name: Tado thuismodus
        icon_template: >
          {% if is_state_attr("climate.woonkamer", "preset_mode", "home") %}
            mdi:radiator
          {% else %}
            mdi:radiator-off
          {% endif %}
        value_template: >
          {{ is_state_attr("climate.woonkamer", "preset_mode", "home") }}
        turn_on:
          action: climate.set_preset_mode
          data:
            preset_mode: home
          target:
            entity_id: climate.woonkamer
        turn_off:
          action: climate.set_preset_mode
          data:
            preset_mode: away
          target:
            entity_id: climate.woonkamer

template:
  - button:
      - name: Woonkamer opwarmen
        icon: mdi:radiator
        press:
          - action: tado.set_climate_timer
            data:
              time_period: "00:15:00"
              temperature: 25
            target:
              entity_id: climate.woonkamer

      - name: Slaapkamer opwarmen
        icon: mdi:radiator
        press:
          - action: tado.set_climate_timer
            data:
              time_period: "00:15:00"
              temperature: 25
            target:
              entity_id: climate.slaapkamer

      - name: Kledingkamer opwarmen
        icon: mdi:radiator
        press:
          - action: tado.set_climate_timer
            data:
              time_period: "00:15:00"
              temperature: 25
            target:
              entity_id: climate.kledingkamer

      - name: Logeerkamer opwarmen
        icon: mdi:radiator
        press:
          - action: tado.set_climate_timer
            data:
              time_period: "00:15:00"
              temperature: 25
            target:
              entity_id: climate.logeerkamer

      - name: Badkamer opwarmen
        icon: mdi:radiator
        press:
          - action: tado.set_climate_timer
            data:
              time_period: "00:15:00"
              temperature: 25
            target:
              entity_id: climate.badkamer

      - name: Zolder opwarmen
        icon: mdi:radiator
        press:
          - action: tado.set_climate_timer
            data:
              time_period: "00:15:00"
              temperature: 25
            target:
              entity_id: climate.zolder

  - sensor:
      - name: Binnen temperatuur
        icon: mdi:thermometer
        state: >-
          {%
            set temps = states.climate
            | rejectattr("state", "in", ["unavailable", "unknown"])
            | rejectattr("attributes.current_temperature", "none")
            | map(attribute="attributes.current_temperature")
            | sort
          %}
          {% if -1 < temps[0] - temps[-1] < 1 %}
            {{ temps[-1] ~ " °C" }}
          {% else %}
            {{ temps[0] ~ " - " ~ temps[-1] ~ " °C" }}
          {% endif %}
        availability: >-
          {%
            set temps = states.climate
            | rejectattr("state", "in", ["unavailable", "unknown"])
            | rejectattr("attributes.current_temperature", "none")
            | map(attribute="attributes.current_temperature")
            | sort
          %}
          {{ temps | count > 2 }}

automation:
  - id: tado_auto_home_and_away_mode
    alias: Tado - Automatisch home en away mode activeren
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: state
        entity_id: group.residents
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: group.residents
                state: not_home
            sequence:
              - alias: Set climate preset mode to home
                action: climate.set_preset_mode
                data:
                  preset_mode: away
                target:
                  entity_id: climate.woonkamer

              - alias: Turn electric heater off
                action: climate.turn_off
                target:
                  entity_id: climate.elektrische_kachel
        default:
          - alias: Set climate preset mode to home
            action: climate.set_preset_mode
            data:
              preset_mode: home
            target:
              entity_id: climate.woonkamer

  - id: tado_preheat_going_home_cold_day
    alias: Tado - Huis opwarmen op een koude dag naar huis gaan
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: numeric_state
        entity_id: sensor.huis_nearest_distance
        below: 10
    conditions:
      - condition: state
        entity_id: group.residents
        state: not_home
      - condition: state
        entity_id: sensor.huis_nearest_direction_of_travel
        state: towards
      - condition: numeric_state
        entity_id: climate.woonkamer
        attribute: current_temperature
        below: 18
    actions:
      - action: notify.telegram_huisgroep
        data:
          title: Tado
          message: |
            Ik zie dat {{ states("sensor.huis_nearest_device") }} bijna thuis is.
            Het is hier nu nog koud, dus ik verwarm de woonkamer alvast.

      - alias: Heat up the living room for a short time
        action: tado.set_climate_timer
        data:
          time_period: "00:15:00"
          temperature: 25
        target:
          entity_id: climate.woonkamer
