homeassistant:
  customize:
    sensor.count_lights_on:
      friendly_name: Lichten aan
    sensor.count_doors_open:
      friendly_name: Deuren open
    sensor.count_windows_open:
      friendly_name: Ramen open
    sensor.count_media_players_on:
      friendly_name: Media spelers aan
    sensor.count_tvs_on:
      friendly_name: TV's aan
    sensor.count_speakers_on:
      friendly_name: Speakers aan

template:
  - sensor:
      - name: Count lights on
        icon: mdi:lightbulb
        state: >-
          {{
            states.light
            | selectattr("state", "eq", "on")
            | rejectattr("attributes.is_hue_group", "defined")
            | rejectattr("attributes.entity_id", "defined")
            | list
            | count
          }}

      - name: Count doors open
        icon: >-
          {{ iif(this.state == "0", "mdi:door-closed", "mdi:door-open") }}
        state: >-
          {{
            states.binary_sensor
            | selectattr("state", "eq", "on")
            | selectattr("attributes.device_class", "==", "door")
            | rejectattr("entity_id", "in", [
              "binary_sensor.vaatwasser_door",
              "binary_sensor.wasmachine_door",
            ])
            | list
            | count
          }}

      - name: Count windows open
        icon: >-
          {{ iif(this.state == "0", "mdi:window-closed", "mdi:window-open") }}
        state: >-
          {{
            states.binary_sensor
            | selectattr("state", "eq", "on")
            | selectattr("attributes.device_class", "==", "window")
            | list
            | count
          }}

      - name: Count media players on
        icon: mdi:cast-connected
        state: >-
          {{
            states.media_player
            | rejectattr("state", "in", ["idle", "off", "unavailable", "unknown"])
            | list
            | count
          }}

      - name: Count tvs on
        icon: mdi:television
        state: >-
          {{
            states.media_player
            | selectattr("entity_id", "in", ["media_player.lg_c9", "media_player.zolder"])
            | rejectattr("state", "in", ["idle", "off", "unavailable", "unknown"])
            | list
            | count
          }}

      - name: Count speakers on
        icon: mdi:speaker
        state: >-
          {{
            states.media_player
            | selectattr("entity_id", "in", ["media_player.lg_soundbar", "media_player.googlehome6234"])
            | rejectattr("state", "in", ["idle", "off", "unavailable", "unknown"])
            | list
            | count
          }}
