homeassistant:
  customize:
    binary_sensor.zonnescherm_contact_contact:
      device_class: awning # This shouldn't be a door.
    cover.zonnescherm:
      icon: mdi:storefront-outline

input_datetime:
  covers_down:
    name: Rolluiken dicht
    has_date: false
    has_time: true

cover:
  - platform: template
    covers:
      zonnescherm_template:
        device_class: awning
        friendly_name: Zonnescherm
        icon_template: mdi:storefront-outline
        value_template: >-
          {{ iif(states("binary_sensor.zonnescherm_contact_contact") == "on", "open", "closed") }}
        availability_template: >-
          {{ states("cover.zonnescherm") != "unavailable" }}
        position_template: >-
          {{ iif(states("binary_sensor.zonnescherm_contact_contact") == "on", 50, 0) }}
        open_cover:
          service: cover.open_cover
          target:
            entity_id: cover.zonnescherm
        close_cover:
          service: cover.close_cover
          target:
            entity_id: cover.zonnescherm
        stop_cover:
          service: cover.stop_cover
          target:
            entity_id: cover.zonnescherm

template:
  - button:
      - name: Logeerkamer rolgordijn voorkeurspositie
        icon: mdi:star
        press:
          - service: cover.set_cover_position
            data:
              position: 85
            target:
              entity_id: cover.logeerkamer

      - name: Keuken rolgordijn voorkeurspositie
        icon: mdi:star
        press:
          - service: cover.set_cover_position
            data:
              position: 76
            target:
              entity_id: cover.keuken

automation:
  - id: covers_down_set_daily_time
    alias: Rolluiken - Tijd voor sluiten dagelijks aanpassen
    mode: single
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        at: "12:00:00"
    action:
      - service: input_datetime.set_datetime
        data:
          entity_id: input_datetime.covers_down
          time: >
            {% set currentDay = now().strftime("%j") | int %}
            {% set middleDay = 183 %}
            {% set longestDayOffsetMinutes = 45 %}
            {% set magicFactor = 2.5 %}
            {% set ofsetMinutes = (-((currentDay-middleDay) | abs) / magicFactor--longestDayOffsetMinutes) | round(0) %}

            {{ as_local((state_attr("sun.sun", "next_setting")) | as_datetime + timedelta(minutes = ofsetMinutes)).strftime("%H:%M:%S") }}

  # The next automation is make sure we reload the ingration once it's unavailble.
  # Copied from: https://github.com/iMicknl/ha-tahoma/issues/599#issuecomment-994596289
  - id: covers_overkiz_reload_integration
    alias: Rolluiken - Overkiz integratie herladen bij probleem
    mode: single
    trigger:
      - platform: state
        entity_id: cover.slaapkamer
        to: unavailable
        for:
          minutes: 5 # Quick action.
      - platform: state
        entity_id: cover.slaapkamer
        to: unavailable
        for:
          minutes: 60 # Habdle longer outages.
    action:
      - alias: Reload Overkiz integration
        service: homeassistant.reload_config_entry
        target:
          entity_id: cover.slaapkamer

      - alias: Clear the notification
        service: persistent_notification.dismiss
        data:
          notification_id: config_entry_reconfigure
