homeassistant:
  customize:
    binary_sensor.zonnescherm_contact_contact:
      device_class: awning # This shouldn't be a door.
    cover.zonnescherm:
      icon: mdi:storefront-outline

template:
  - cover:
      - name: Zonnescherm template
        device_class: awning
        icon: mdi:storefront-outline
        state: >-
          {{ iif(states("binary_sensor.zonnescherm_contact_contact") == "on", "open", "closed") }}
        availability: >-
          {{ states("cover.zonnescherm") != "unavailable" }}
        position: >-
          {{ iif(states("binary_sensor.zonnescherm_contact_contact") == "on", 50, 0) }}
        open_cover:
          action: cover.open_cover
          target:
            entity_id: cover.zonnescherm
        close_cover:
          action: cover.close_cover
          target:
            entity_id: cover.zonnescherm
        stop_cover:
          action: cover.stop_cover
          target:
            entity_id: cover.zonnescherm

  - button:
      - name: Logeerkamer rolgordijn voorkeurspositie
        icon: mdi:star
        press:
          - action: cover.set_cover_position
            data:
              position: 85
            target:
              entity_id: cover.logeerkamer

      - name: Keuken rolgordijn voorkeurspositie
        icon: mdi:star
        press:
          - action: cover.set_cover_position
            data:
              position: 80
            target:
              entity_id: cover.keuken

automation:
  - id: auto_close_awning
    alias: Zonnescherm automatisch sluiten
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: state
        entity_id: sensor.zon_positie
        from: Achter
        to: Voor
      - trigger: state
        entity_id: sun.sun
        to: below_horizon
      - trigger: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 7
    conditions:
      - condition: state
        entity_id: binary_sensor.zonnescherm_contact_contact
        state: "on"
    actions:
      - alias: Close the awning
        action: cover.close_cover
        target:
          entity_id: cover.zonnescherm

  - id: awning_can_be_opened
    alias: Zonnescherm kan open
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: numeric_state
        entity_id: sensor.achtertuin_sensor_1_licht
        above: 3800
      - trigger: state
        entity_id: sensor.zon_positie
        from: Voor
        to: Achter
    conditions:
      - condition: numeric_state
        entity_id: sensor.achtertuin_sensor_1_licht
        above: 3800
      - condition: state
        entity_id: sensor.zon_positie
        state: Achter
      - condition: numeric_state
        entity_id: sensor.knmi_max_temperatuur_vandaag
        above: 19
      - condition: numeric_state
        entity_id: sensor.knmi_neerslag_vandaag
        below: 10
      - condition: state
        entity_id: binary_sensor.zonnescherm_contact_contact
        state: "off"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    actions:
      - alias: Set up variables for the actions
        variables:
          # Including an id in the action allows us to identify this script run and not accidentally trigger for other notification actions.
          action_open: "{{ 'OPEN_' ~ context.id }}"

      - alias: Ask to close the awning
        action: notify.all_phones
        data:
          message: De zon is achter, wil je het zonnescherm openen?
          data:
            tag: sun
            actions:
              - action: "{{ action_open }}"
                title: Ja, open

      - alias: Wait for a response
        wait_for_trigger:
          - trigger: event
            event_type: mobile_app_notification_action
            event_data:
              action: "{{ action_open }}"

      - alias: Perform the action
        choose:
          - conditions: "{{ wait.trigger.event.data.action == action_open }}"
            sequence:
              - action: button.press
                target:
                  entity_id: button.zonnescherm_my_position

              - alias: Clear this notification on all devices
                action: notify.all_phones
                data:
                  message: clear_notification
                  data:
                    tag: sun

  # The next automation is to make sure we reload the ingration once it's unavailble.
  # Copied from: https://github.com/iMicknl/ha-tahoma/issues/599#issuecomment-994596289
  - id: covers_overkiz_reload_integration
    alias: Rolluiken - Overkiz integratie herladen bij probleem
    mode: single
    triggers:
      - trigger: state
        entity_id: cover.slaapkamer
        to: unavailable
        for:
          minutes: 5 # Quick action.
      - trigger: state
        entity_id: cover.slaapkamer
        to: unavailable
        for:
          minutes: 60 # Handle longer outages.
    actions:
      - alias: Reload Overkiz integration
        action: homeassistant.reload_config_entry
        target:
          entity_id: cover.slaapkamer

      - alias: Clear the notification
        action: persistent_notification.dismiss
        data:
          notification_id: config_entry_reconfigure

script:
  zonnescherm_dicht:
    alias: Zonnescherm dicht
    icon: mdi:arrow-up-box
    mode: single
    sequence:
      - alias: Close awning
        action: cover.close_cover
        target:
          entity_id: cover.zonnescherm

  zonnescherm_open:
    alias: Zonnescherm open
    icon: mdi:arrow-down-box
    mode: single
    sequence:
      - alias: Open awning to preference position
        action: button.press
        target:
          entity_id: button.zonnescherm_my_position

  zonnescherm_helemaal_open:
    alias: Zonnescherm helemaal open
    icon: mdi:arrow-down-box
    mode: single
    sequence:
      - alias: Fully open awning
        action: cover.open_cover
        target:
          entity_id: cover.zonnescherm

  open_south_facing_covers_based_on_weather:
    alias: Open south facing covers based on weather
    mode: parallel
    sequence:
      - alias: Act based on predicted temperature
        if:
          - condition: numeric_state
            entity_id: sensor.knmi_max_temperatuur_vandaag
            above: 25
        then:
          - alias: It will be warm today, set south facing covers to their preference position
            action: button.press
            target:
              entity_id:
                - button.kledingkamer_my_position
                - button.slaapkamer_my_position
          - alias: Notify user as this might be unexpected
            action: notify.sander
            data:
              title: Rolluiken
              message: Het wordt vandaag warm, de rolluiken gaan niet helemaal open
        else:
          - alias: Open south facing covers
            action: cover.open_cover
            target:
              entity_id:
                - cover.kledingkamer
                - cover.slaapkamer

      - alias: Set curtains to preference position
        action: button.press
        target:
          entity_id:
            - button.logeerkamer_rolgordijn_voorkeurspositie
            - button.keuken_rolgordijn_voorkeurspositie

  close_cover_window_state:
    alias: Close cover, depending on window state
    mode: parallel
    fields:
      cover_entity:
        name: Cover entity
        description: Cover entity
        required: true
        selector:
          entity:
            filter:
              domain: cover
      window_entity:
        name: Door/window entity
        description: This should be closed (off) to make the cover close.
        required: true
        selector:
          entity:
            filter:
              - domain: binary_sensor
                device_class: door
              - domain: binary_sensor
                device_class: window
      wait_minutes:
        name: Wait period
        description: In case the window entity is open (true) at the moment of trigger, the cover will still be closed when the window is closed within this wait period.
        default: 120
        selector:
          number:
            min: 0
            max: 600
            unit_of_measurement: minutes
    sequence:
      - choose:
          - conditions:
              - "{{ is_state(window_entity, 'off') }}"
              - "{{ not is_state(cover_entity, 'closed') }}"
            sequence:
              - alias: Close the cover
                action: cover.close_cover
                target:
                  entity_id: "{{ cover_entity }}"

          - conditions:
              - "{{ is_state(window_entity, 'on') }}"
              - "{{ not is_state(cover_entity, 'closed') }}"
            sequence:
              - alias: Wait if the window is closed within a given time.
                wait_template: "{{ is_state(window_entity, 'off') }}"
                timeout:
                  minutes: "{{ wait_minutes }}"
                continue_on_timeout: false

              - alias: Wait a little to make sure it's really closed
                delay:
                  seconds: 5

              - alias: Close the cover now
                action: cover.close_cover
                target:
                  entity_id: "{{ cover_entity }}"
