homeassistant:
  customize:
    binary_sensor.slaapkamerraam_contact:
      device_class: window

    binary_sensor.kledingkamerraam_contact:
      device_class: window
    
    binary_sensor.keukenraam_contact:
      device_class: window

    binary_sensor.badkamerraam_contact:
      device_class: window

    binary_sensor.logeerkamerraam_contact:
      device_class: window

    binary_sensor.zolderraam_contact:
      device_class: window

