homeassistant:
  customize:
    binary_sensor.slaapkamerraam_contact:
      device_class: window

    binary_sensor.kledingkamerraam_contact:
      device_class: window
    
    binary_sensor.0x00158d00044585bf_contact:
      device_class: window