homeassistant:
  customize_glob:
    "group.*kamer_motion":
      device_class: motion

    "binary_sensor.*beweging*occupancy":
      icon: mdi:motion-sensor

  customize:
    # Remove door suffix from doors.
    binary_sensor.achterdeur_contact:
      friendly_name: Achterdeur
    binary_sensor.balkondeur_contact:
      friendly_name: Balkondeur
    binary_sensor.poortdeur_contact:
      friendly_name: Poort
    binary_sensor.voordeur_contact:
      friendly_name: Voordeur
    binary_sensor.trapkastdeur_contact:
      friendly_name: Trapkastdeur

    # Remove door suffix from windows and set proper device class.
    binary_sensor.achterraam_contact:
      device_class: window
      friendly_name: Achterraam
    binary_sensor.badkamerraam_contact:
      device_class: window
      friendly_name: Badkamerraam
    binary_sensor.keukenraam_contact:
      device_class: window
      friendly_name: Keukenraam
    binary_sensor.kledingkamerraam_contact:
      device_class: window
      friendly_name: Kledingkamerraam
    binary_sensor.logeerkamerraam_contact:
      device_class: window
      friendly_name: Logeerkamerraam
    binary_sensor.slaapkamerraam_contact:
      device_class: window
      friendly_name: Slaapkamerraam
    binary_sensor.zolderraam_contact:
      device_class: window
      friendly_name: Zolderraam

    binary_sensor.aurora_visibility_visibility_alert:
      friendly_name: Noorderlicht
      icon: mdi:aurora

    light.badkamer:
      icon: mdi:ceiling-light
    light.bedlampje_links:
      icon: mdi:desk-lamp
    light.bedlampje_rechts:
      icon: mdi:desk-lamp
    light.achtertuin_groep:
      icon: mdi:coach-lamp
    light.eettafel:
      icon: mdi:vanity-light
    light.hal:
      icon: mdi:ceiling-light
    light.kerstboom:
      icon: mdi:pine-tree
    light.keuken:
      icon: mdi:ceiling-light
    light.kledingkamer:
      icon: mdi:ceiling-light
    light.logeerkamer:
      icon: mdi:ceiling-light
    light.overloop:
      icon: mdi:ceiling-light
    light.skull:
      friendly_name: Skull
      icon: mdi:skull
    light.slaapkamer_plafond_groep:
      icon: mdi:ceiling-light
    light.toilet:
      icon: mdi:ceiling-light
    light.tv:
      icon: mdi:television-ambient-light
    light.voortuin:
      icon: mdi:coach-lamp
    light.woonkamer:
      icon: mdi:lamps
    light.zolder:
      icon: mdi:ceiling-light

    scene.slaapkamer_helder:
      friendly_name: Helder
      icon: mdi:lightbulb-on
    scene.slaapkamer_gedimd:
      friendly_name: Gedimd
      icon: mdi:lightbulb-on-50
    scene.slaapkamer_love:
      friendly_name: Love
      icon: mdi:heart-half-full
    scene.slaapkamer_naar_bed:
      friendly_name: Naar bed
      icon: mdi:weather-night
    scene.wooneet_avond:
      friendly_name: Avond
      icon: mdi:weather-sunset
    scene.wooneet_eten:
      friendly_name: Eten
      icon: mdi:food-turkey
    scene.wooneet_film:
      friendly_name: Film
      icon: mdi:movie-open
    scene.wooneet_nacht:
      friendly_name: Nacht
      icon: mdi:weather-night
