homeassistant:
  customize_glob:
    "binary_sensor.*raam_contact":
      device_class: window
    "group.*kamer_motion":
      device_class: motion

    "binary_sensor.*beweging*occupancy":
      icon: mdi:motion-sensor

  customize:
    light.wled_skull:
      friendly_name: Skull
      icon: mdi:skull
