homeassistant:
  customize:
    sensor.tango_purmerend:
      icon: mdi:gas-station
    sensor.tango_winschoten:
      icon: mdi:gas-station
      
sensor:
  - platform: scrape
    resource: https://www.tango.nl/stations/tango-purmerend
    name: Tango Purmerend
    select: "#euro95 > div.pump_price > span.price"
    unit_of_measurement: €
    scan_interval: 3600
    device_class: monetary
    state_class: measurement

  - platform: scrape
    resource: https://www.tango.nl/stations/tango-winschoten
    name: Tango Winschoten
    select: "#euro95 > div.pump_price > span.price"
    unit_of_measurement: €
    scan_interval: 3600
    device_class: monetary
    state_class: measurement
