homeassistant:
  customize:
    sensor.tango_purmerend:
      icon: mdi:gas-station
    sensor.tango_winschoten:
      icon: mdi:gas-station
    sensor.tango_hoogezand:
      icon: mdi:gas-station
    sensor.freie_tankstelle_husers:
      icon: mdi:gas-station

scrape:
  - resource: https://www.tango.nl/stations/tango-purmerend
    scan_interval: 3600
    sensor:
      - name: Tango Purmerend
        select: "#euro95 > div.pump_price > span.price"
        unit_of_measurement: €
        device_class: monetary
        state_class: total

  - resource: https://www.tango.nl/stations/tango-winschoten
    scan_interval: 3600
    sensor:
      - name: Tango Winschoten
        select: "#euro95 > div.pump_price > span.price"
        unit_of_measurement: €
        device_class: monetary
        state_class: total

  - resource: https://www.tango.nl/stations/tango-hoogezand-hoofdstraat
    scan_interval: 3600
    sensor:
      - name: Tango Hoogezand
        select: "#euro95 > div.pump_price > span.price"
        unit_of_measurement: €
        device_class: monetary
        state_class: total

  - resource: https://www.mehr-tanken.de/regional-tanken/niedersachsen/ruetenbrock/49733/tankstelle/freie-tankstelle-huesers-6ca71ccf2/
    scan_interval: 3600
    sensor:
      - name: Freie Tankstelle Hüsers
        select: "#maincol_article > div > div:nth-of-type(3) > div:nth-of-type(2) > div:nth-of-type(1)"
        unit_of_measurement: €
        device_class: monetary
        state_class: total
