homeassistant:
  customize:
    sensor.tango_purmerend:
      icon: mdi:gas-station
    sensor.tango_winschoten:
      icon: mdi:gas-station
      
sensor:
  - platform: scrape
    resource: https://www.tango.nl/stations/tango-purmerend
    name: Tango Purmerend
    select: "#euro95 > div.pump_price > span.price"
    unit_of_measurement: €
    scan_interval: 3600
    device_class: monetary
    state_class: measurement

  - platform: scrape
    resource: https://www.tango.nl/stations/tango-winschoten
    name: Tango Winschoten
    select: "#euro95 > div.pump_price > span.price"
    unit_of_measurement: €
    scan_interval: 3600
    device_class: monetary
    state_class: measurement

  - platform: scrape
    resource: https://www.tango.nl/stations/tango-hoogezand-hoofdstraat
    name: Tango Hoogezand
    select: "#euro95 > div.pump_price > span.price"
    unit_of_measurement: €
    scan_interval: 3600
    device_class: monetary
    state_class: measurement

  - platform: scrape
    resource: https://mehr-tanken.de/tankstelle/6ca71ccf2/freie-tankstelle-husers-burgermeister-esders-str-1-49733-rutenbrock
    name: Freie Tankstelle Hüsers
    select: "a[href$='#s95_e5'] > div > div.col-sm-3"
    value_template: "{{ value.replace(' ', '').replace('\n', '') }}"
    unit_of_measurement: €
    scan_interval: 3600
    device_class: monetary
    state_class: measurement
