homeassistant:
  customize:
    sensor.tango_purmerend:
      icon: mdi:gas-station
    sensor.tango_winschoten:
      icon: mdi:gas-station
    sensor.tango_hoogezand:
      icon: mdi:gas-station
    sensor.freie_tankstelle_husers:
      icon: mdi:gas-station
    sensor.avia_rutenbrock:
      icon: mdi:gas-station

scrape:
  - resource: https://www.tango.nl/stations/tango-purmerend
    scan_interval: 3600
    sensor:
      - name: Tango Purmerend
        select: "div[data-testid='elStationDetailsProducts'] > div:nth-child(2) dd"
        unit_of_measurement: €
        value_template: >-
          {{ value.split(" ")[0] }}
        device_class: monetary
        state_class: total

  - resource: https://www.tango.nl/stations/tango-winschoten
    scan_interval: 3600
    sensor:
      - name: Tango Winschoten
        select: "div[data-testid='elStationDetailsProducts'] > div:nth-child(2) dd"
        unit_of_measurement: €
        value_template: >-
          {{ value.split(" ")[0] }}
        device_class: monetary
        state_class: total

  - resource: https://www.tango.nl/stations/tango-hoogezand-hoofdstraat
    scan_interval: 3600
    sensor:
      - name: Tango Hoogezand
        select: "div[data-testid='elStationDetailsProducts'] > div:nth-child(2) dd"
        unit_of_measurement: €
        value_template: >-
          {{ value.split(" ")[0] }}
        device_class: monetary
        state_class: total

sensor:
  - platform: rest
    name: Freie Tankstelle Hüsers
    scan_interval: 3600
    unit_of_measurement: €
    device_class: monetary
    state_class: total
    resource: https://page-api.auto-motor-und-sport.de/mt/poi-detail/
    method: POST
    headers:
      Content-Type: application/json; charset=utf-8
    payload: >-
      { "serviceStationId": "6ca71ccf2", "updateDB": false, "includeServiceImages": false }
    value_template: >-
      {% set price = namespace(value = "unavailable") %}
      {% for product in value_json.station.prices %}
        {% if product["name"] == "Super (E10)" %}
          {% set price.value = product["price"] %}
        {% endif %}
      {% endfor %}
      {{ price.value }}

  - platform: rest
    name: AVIA Rutenbrock
    scan_interval: 3600
    unit_of_measurement: €
    device_class: monetary
    state_class: total
    resource: https://page-api.auto-motor-und-sport.de/mt/poi-detail/
    method: POST
    headers:
      Content-Type: application/json; charset=utf-8
    payload: >-
      { "serviceStationId": "dcef7d45", "updateDB": false, "includeServiceImages": false }
    value_template: >-
      {% set price = namespace(value = "unavailable") %}
      {% for product in value_json.station.prices %}
        {% if product["name"] == "Super (E10)" %}
          {% set price.value = product["price"] %}
        {% endif %}
      {% endfor %}
      {{ price.value }}
