# This feature requires running an mDNS forwarder on your Docker host, e.g., avahi-daemon in reflector mode.
#
# In /etc/avahi/avahi-daemon.conf update the reflector section like bellow, make sure those 3 lines are not commented out.
#
# [reflector]
# enable-reflector=yes
# reflect-ipv=no

# Restart the Avahi daemon to reload config:
# sudo service avahi-daemon restart

homekit:
  auto_start: false
  advertise_ip: !secret host_ip
  filter:
    include_entities:
      - fan.air_purifier
      - light.wled_skull
      - switch.keukenkastje_lamp_switch
      - switch.voorraadkastlamp_switch
      - switch.ziggo_decoder
  entity_config:
    light.wled_skull:
      name: Skull
    switch.keukenkastje_lamp_switch:
      name: Keukenkastje
    switch.voorraadkastlamp_switch:
      name: Voorraadkast
    switch.ziggo_decoder:
      name: Ziggo decoder

automation:
  - id: homekit_delayed_start
    alias: HomeKit uitgestelde start
    initial_state: on
    mode: single
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: 00:03
      - service: homekit.start
