input_boolean:
  guest_mode:
    name: Gastmodus
    initial: false
    icon: mdi:account-check
  vacation_mode:
    name: Vakantiemodus
    initial: false
    icon: mdi:beach

group:
  residents:
    name: Bewoners
    icon: mdi:human-greeting
    entities:
      - person.sander

automation:
  - id: vacation_mode
    alias: Vakantie modus - automatisch activeren en deactiveren
    mode: single
    trigger:
      - platform: state
        entity_id: group.residents
        to: not_home
        for: "24:00:00"
        id: aan
      - platform: state
        entity_id: group.residents
        to: home
    action:
      - if:
          - condition: trigger
            id: aan
          - condition: state
            entity_id: input_boolean.guest_mode
            state: "off"
        then:
          - alias: Turn on vacation mode
            service: input_boolean.turn_on
            entity_id: input_boolean.vacation_mode
        else:
          - alias: Turn off vacation mode
            service: input_boolean.turn_off
            entity_id: input_boolean.vacation_mode

  - id: vacation_mode_presence
    alias: Vakantie modus - aanwezigheid nabootsen
    mode: parallel
    trigger:
      - platform: numeric_state
        entity_id: sensor.epo1_illuminance
        below: 1
        for:
          minutes: 30
        id: woonkamer_avond
      - platform: time
        at: "23:30:00"
        id: tanden_poetsen
      - platform: time
        at: "00:45:00"
        id: nacht_toilet
      - platform: time
        at: "00:00:00"
        id: alles_uit
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: woonkamer_avond
            sequence:
              - alias: Wait a little to randomize the behavior
                delay:
                  minutes: "{{ range(0, 15) | random }}"
              - alias: Turn on the light
                service: light.turn_on
                data:
                  xy_color: [0.459, 0.408] # Helder
                  brightness: 1
                target:
                  entity_id: light.woonkamer_groot_2
              - alias: Wait till a certain time
                wait_for_trigger:
                  - platform: time
                    at: "22:00:00"
              - alias: Wait a little to randomize the behavior
                delay:
                  minutes: "{{ range(0, 30) | random }}"
              - alias: Turn off the light
                service: light.turn_off
                target:
                  entity_id: light.woonkamer_groot_2

          - conditions:
              - condition: trigger
                id: tanden_poetsen
            sequence:
              - alias: Wait a little to randomize the behavior
                delay:
                  minutes: "{{ range(0, 30) | random }}"

              - alias: Turn on the light
                service: scene.turn_on
                target:
                  entity_id: scene.badkamer_helder
              - alias: Wait a little to randomize the behavior
                delay:
                  minutes: "{{ range(3, 5) | random }}"
              - alias: Turn off the light
                service: light.turn_off
                target:
                  entity_id: light.badkamer

          - conditions:
              - condition: trigger
                id: nacht_toilet
            sequence:
              - alias: Wait a little to randomize the behavior
                delay:
                  minutes: "{{ range(0, 30) | random }}"
              - alias: Turn on the light
                service: scene.turn_on
                target:
                  entity_id: scene.badkamer_ontspannen
              - alias: Wait a little to randomize the behavior
                delay:
                  minutes: "{{ range(1, 3) | random }}"
              - alias: Turn off the light
                service: light.turn_off
                target:
                  entity_id: light.badkamer

          - conditions:
              - condition: trigger
                id: alles_uit
            sequence:
              - alias: Make sure everything is off
                service: script.everything_off
