input_datetime:
  dishwasher_daily_start:
    name: Vaatwasser start
    has_date: false
    has_time: true

template:
  - sensor:
      - name: Wasmachine programma
        icon: mdi:washing-machine
        state: >-
          {% from "home_connect.jinja" import program_translation %}
          {% set prefix = "Wasmachine Program " %}
          {% set translations = {"Auto40": "Auto 40°C", "Cotton": "Katoen", "DelicatesSilk": "Fijne was/zijde", "EasyCare": "Kreukherstellend", "Mix": "Mix/Snel", "Sensitive": "Sensitive", "SportFitness": "Sport", "Wool": "Wol"} %}
          {{ program_translation(prefix, translations) }}

      - name: Vaatwasser programma
        icon: mdi:dishwasher
        state: >-
          {% from "home_connect.jinja" import program_translation %}
          {% set prefix = "Vaatwasser Program " %}
          {% set translations = {"Auto2": "Auto 45-65°C", "Eco50": "Eco 50°C", "Glas40": "Glas 40°C", "Intensiv70": "Intensief 70°C", "Kurz60": "Kort 60°C", "MachineCare": "Machineverzorging", "NightWash": "Nachtprogramma", "PreRinse": "Voorspoelen", "Quick45": "Snel programma 45°C"} %}
          {{ program_translation(prefix, translations) }}

      - name: Wasmachine resterende minuten
        icon: mdi:clock
        state: >-
          {% from "home_connect.jinja" import remaining_time %}
          {{ remaining_time("sensor.wasmachine_remaining_program_time", "switch.wasmachine_power") }}

      - name: Vaatwasser resterende minuten
        icon: mdi:clock
        state: >-
          {% from "home_connect.jinja" import remaining_time %}
          {{ remaining_time("sensor.vaatwasser_remaining_program_time", "switch.vaatwasser_power") }}

      - name: Wasmachine status
        icon: mdi:washing-machine
        state: >-
          {% if states("binary_sensor.wasmachine_door") == "on" -%}
            Deur open
          {% elif states("sensor.wasmachine_operation_state") == "Finished" -%}
            Klaar
          {% elif states("sensor.wasmachine_operation_state") == "Run" -%}
            {{ states("sensor.wasmachine_resterende_minuten") }}
          {% elif states("binary_sensor.wasmachine_remote_start") == "on" -%}
            Uitgestelde start
          {%- else -%}
            {{ states("switch.wasmachine_power") }}
          {%- endif %}

      - name: Vaatwasser status
        icon: mdi:dishwasher
        state: >-
          {% if states("binary_sensor.vaatwasser_door") == "on" -%}
            Deur open
          {% elif states("sensor.vaatwasser_operation_state") == "Finished" -%}
            Klaar
          {% elif states("sensor.vaatwasser_operation_state") == "Run" -%}
            {{ states("sensor.vaatwasser_resterende_minuten") }}
          {% elif states("binary_sensor.vaatwasser_remote_start") == "on" -%}
            Uitgestelde start
          {%- else -%}
            {{ states("switch.vaatwasser_power") }}
          {%- endif %}

automation:
  - id: dishwasher_auto_daily_start
    alias: Vaatwasser dagelijks starten
    mode: single
    trigger:
      platform: time
      at: input_datetime.dishwasher_daily_start
    condition:
      - condition: state
        entity_id: binary_sensor.vaatwasser_remote_start
        state: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.vaatwasser_program_auto2

  - id: dishwasher_set_daily_start_time
    alias: Vaatwasser tijd dagelijks aanpassen
    mode: single
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        at: "12:00:00"
    action:
      - variables:
          weekday_time: "04:30"
          weekend_time: "07:30"
          schedule_time: >
            {% set weekday = now().isoweekday() %}
            {% set hour = now().hour %}

            {% if hour < 4 %}
              {% if weekday in [6, 7] %}
                {{ weekend_time }}
              {% else %}
                {{ weekday_time }}
              {% endif %}
            {% else %}
              {% if weekday in [5, 6] %}
                {{ weekend_time }}
              {% else %}
                {{ weekday_time }}
              {% endif %}
            {% endif %}

      - service: input_datetime.set_datetime
        data:
          entity_id: input_datetime.dishwasher_daily_start
          time: "{{ schedule_time }}"

  # The washing machine remains sometimes unavailable. Reloading the integration to "fix" this
  # Issue: https://github.com/home-assistant/core/issues/66063
  - id: reload_home_connect
    alias: Wasmachine - Herlaad Home Connect integratie
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.zolder_power
        above: 2
        for:
          minutes: 2
      - platform: numeric_state
        entity_id: sensor.zolder_power
        below: 2
        for:
          minutes: 2
    condition:
      # Should be a little higher than the minutes in the triggers, to deal with restarts.
      - "{{ now() | as_timestamp(0) - states('sensor.uptime') | as_timestamp(0) > 200 }}"
    action:
      - alias: Reload Home Connect integration
        service: homeassistant.reload_config_entry
        target:
          entity_id: switch.wasmachine_power
