home_connect:
  client_id: !secret home_connect_client_id
  client_secret: !secret home_connect_client_secret

input_datetime:
  dishwasher_daily_start:
    name: Vaatwasser start
    has_date: false
    has_time: true

sensor:
  - platform: template
    sensors:
      wasmachine_active_program:
        friendly_name: Wasmachine programma
        icon_template: mdi:washing-machine
        value_template: >
          {% set prefix = 'Wasmachine Program ' %}
          {% set program = namespace(name = 'Niet beschikbaar') %}
          {% for switch in states.switch -%}
            {%- if switch.name.startswith(prefix) and switch.state == 'on' %}
              {% set program.name = switch.name.split(prefix)[1] %}
            {%- endif %}
          {%- endfor %}
          {{ program.name }}

      vaatwasser_active_program:
        friendly_name: Vaatwasser programma
        icon_template: mdi:dishwasher
        value_template: >
          {% set prefix = 'Vaatwasser Program ' %}
          {% set program = namespace(name = 'Niet beschikbaar') %}
          {% for switch in states.switch -%}
            {%- if switch.name.startswith(prefix) and switch.state == 'on' %}
              {% set program.name = switch.name.split(prefix)[1] %}
            {%- endif %}
          {%- endfor %}
          {{ program.name }}

      wasmachine_remaining_relative_local:
        friendly_name: Resterende tijd
        icon_template: mdi:clock
        value_template: >
          {% if is_state('sensor.wasmachine_remaining_program_time', 'unavailable') or is_state('switch.wasmachine_power', 'off') -%}
            Niet beschikbaar
          {%- else -%}
            {% set seconds = as_timestamp(states('sensor.wasmachine_remaining_program_time')) - as_timestamp(utcnow()) | int  %}
            {% set minutes = ((seconds % 3600) / 60) | int %}
            {% set hours = (seconds / 3600) | int %}

            {%- if seconds <= 0 -%}
              Klaar
            {%- elif seconds < 60 -%}
              {{ seconds }} seconden
            {%- else -%}
              {%- if hours > 0 -%}
                {%- if hours == 1 -%}
                  1 uur
                {%- else -%}
                  {{ hours }} uur
                {%- endif -%}
              {%- endif -%}
              {%- if minutes > 0 -%}
                {%- if hours > 0 -%}
                  {{ ', ' }}
                {%- endif -%}
                {%- if minutes == 1 -%}
                  1 minuut
                {%- else -%}
                  {{ minutes }} minuten
                {%- endif -%}
              {%- endif -%}
            {%- endif -%}
          {%- endif %}

      wasmachine_remaining_seconds:
        friendly_name: Resterende tijd
        icon_template: mdi:clock
        value_template: >
          {%- if is_state('sensor.wasmachine_remaining_program_time', 'unavailable') or is_state('switch.wasmachine_power', 'off') -%}
            0
          {%- else -%}
          {% set seconds = (as_timestamp(states('sensor.wasmachine_remaining_program_time')) - as_timestamp(utcnow())) | int  %}
          {%- if seconds <= 0 -%}
              0
            {%- else -%}
              {{ seconds }}
            {%- endif -%}
          {%- endif -%}

      vaatwasser_remaining_relative_local:
        friendly_name: Resterende tijd
        icon_template: mdi:clock
        value_template: >
          {% if is_state('sensor.vaatwasser_remaining_program_time', 'unavailable') or is_state('switch.vaatwasser_power', 'off') -%}
            Niet beschikbaar
          {%- else -%}
            {% set seconds = as_timestamp(states('sensor.vaatwasser_remaining_program_time')) - as_timestamp(utcnow()) | int  %}
            {% set minutes = ((seconds % 3600) / 60) | int %}
            {% set hours = (seconds / 3600) | int %}

            {%- if seconds <= 0 -%}
              Klaar
            {%- elif seconds < 60 -%}
              {{ seconds }} seconden
            {%- else -%}
              {%- if hours > 0 -%}
                {%- if hours == 1 -%}
                  1 uur
                {%- else -%}
                  {{ hours }} uur
                {%- endif -%}
              {%- endif -%}
              {%- if minutes > 0 -%}
                {%- if hours > 0 -%}
                  {{ ', ' }}
                {%- endif -%}
                {%- if minutes == 1 -%}
                  1 minuut
                {%- else -%}
                  {{ minutes }} minuten
                {%- endif -%}
              {%- endif -%}
            {%- endif -%}
          {%- endif %}

      vaatwasser_remaining_seconds:
        friendly_name: Resterende tijd
        icon_template: mdi:clock
        value_template: >
          {%- if is_state('sensor.vaatwasser_remaining_program_time', 'unavailable') or is_state('switch.vaatwasser_power', 'off') -%}
            0
          {%- else -%}
            {% set seconds = (as_timestamp(states('sensor.vaatwasser_remaining_program_time')) - as_timestamp(utcnow())) | int  %}
            {%- if seconds <= 0 -%}
              0
            {%- else -%}
              {{ seconds }}
            {%- endif -%}
          {%- endif -%}

automation:
  - id: dishwasher_auto_daily_start
    alias: Vaatwasser dagelijks starten
    initial_state: on
    mode: single
    trigger:
      platform: time
      at:
        - input_datetime.dishwasher_daily_start
    condition:
      - condition: state
        entity_id: switch.vaatwasser_power
        state: 'on'
      - condition: state
        entity_id: binary_sensor.vaatwasser_door
        state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.vaatwasser_program_auto2

  - id: dishwasher_set_daily_start_time
    alias: Vaatwasser tijd dagelijks aanpassen
    initial_state: on
    mode: single
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        at: 
          - '12:00:00'
    action:
      - choose:
        - conditions:
            - condition: template
              value_template: > # Friday - Saturday
                {{ now().isoweekday() in [5, 6] }}
          sequence:
            - service: input_datetime.set_datetime
              data:
                entity_id: input_datetime.dishwasher_daily_start
                time: '07:30'
        default:
          - service: input_datetime.set_datetime
            data:
              entity_id: input_datetime.dishwasher_daily_start
              time: '04:30'
