home_connect:
  client_id: !secret home_connect_client_id
  client_secret: !secret home_connect_client_secret

input_datetime:
  dishwasher_daily_start:
    name: Vaatwasser start
    has_date: false
    has_time: true

automation:
  - id: dishwasher_auto_daily_start
    alias: Vaatwasser dagelijks starten
    initial_state: on
    trigger:
      platform: time
      at:
        - input_datetime.dishwasher_daily_start
    condition:
      - condition: state
        entity_id: switch.vaatwasser_power
        state: 'on'
      - condition: state
        entity_id: binary_sensor.vaatwasser_door
        state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.vaatwasser_program_auto2

  - id: dishwasher_set_daily_start_time
    alias: Vaatwasser tijd dagelijks aanpassen
    initial_state: on
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        at: 
          - '12:00:00'
    action:
      - choose:
        - conditions:
            - condition: template
              value_template: '{{ now().isoweekday() in [5, 6] }}' # Friday - Saturday
          sequence:
            - service: input_datetime.set_datetime
              data:
                entity_id: input_datetime.dishwasher_daily_start
                time: '07:30'
        default:
          - service: input_datetime.set_datetime
            data:
              entity_id: input_datetime.dishwasher_daily_start
              time: '04:30'

# Below is from a custom component I was using previously, keeping here in case I want to switch back.
# Github: https://github.com/cotwild/home_connect
#
# sensor:
#   - platform: home_connect
#     refresh_token: !secret home_connect_refresh_token

# group:
#   vaatwasser:
#     name: Vaatwasser
#     entities:
#       - sensor.bosch_sbv88tx36e_state
#       - sensor.bosch_sbv88tx36e_door
#       - sensor.bosch_sbv88tx36e_program
#       - sensor.bosch_sbv88tx36e_elapsed
#       - sensor.bosch_sbv88tx36e_remaining

#   wasmachine:
#     name: Wasmachine
#     entities:
#       - sensor.bosch_wawh2643nl_state
#       - sensor.bosch_wawh2643nl_door 
#       - sensor.bosch_wawh2643nl_program
#       - sensor.bosch_wawh2643nl_elapsed
#       - sensor.bosch_wawh2643nl_remaining
  