input_datetime:
  dishwasher_daily_start:
    name: Vaatwasser start
    has_date: false
    has_time: true

template:
  - sensor:
      - name: Wasmachine programma
        icon: mdi:washing-machine
        state: >-
          {% set prefix = "Wasmachine Program " %}
          {% set program = namespace(name = "unavailable") %}
          {% for switch in states.switch -%}
            {%- if switch.name.startswith(prefix) and switch.state == "on" %}
              {% set program.name = switch.name.split(prefix)[1] %}
            {%- endif %}
          {%- endfor %}
          
          {% set programTranslation = { "Auto30": "Auto 30°C", "Auto40": "Auto 40°C", "Auto60": "Auto 60°C", "Chiffon": "Zijde", "Cotton": "Katoen", "CottonEco": "Katoen Eco", "Curtains": "Gordijnen", "DarkWash": "Donkeren was", "DelicatesSilk": "Fijne was/zijde", "Dessous": "Ondergoed", "EasyCare": "Kreukherstellend", "Mix": "Mix/Snel", "Monsoon": "Monsoon", "Outdoor": "Outdoor & Extreme Sporten", "PlushToy": "Plushen Speelgoed", "Sensitive": "Sensitive", "ShirtsBlouses": "Overhemden bloezen", "SportFitness": "Sport", "Towels": "Handdoeken", "WaterProof": "Waterbestendig", "Wool": "Wol"} %}
          {% if program.name in programTranslation %}
            {{ programTranslation[program.name] }}
          {% else %}
            {{ program.name }}
          {% endif %}

      - name: Vaatwasser programma
        icon: mdi:dishwasher
        state: >-
          {% set prefix = "Vaatwasser Program " %}
          {% set program = namespace(name = "unavailable") %}
          {% for switch in states.switch -%}
            {%- if switch.name.startswith(prefix) and switch.state == "on" %}
              {% set program.name = switch.name.split(prefix)[1] %}
            {%- endif %}
          {%- endfor %}
          
          {% set programTranslation = {"Auto1": "Auto 1", "Auto2": "Auto 2", "Auto3": "Auto 3", "AutoHalfLoad": "Auto half beladen", "Eco50": "Eco 50°C", "ExpressSparkle65": "Express Sparkle 65°C", "Glas40": "Glas 40°C", "GlassCare": "Glasverzorging", "Intensiv45": "Intensief 45°C", "Intensiv70": "Intensief 70°C", "IntensivPower": "Intensief vermogen", "Kurz60": "Kort 60°C", "MachineCare": "Machineverzorging", "MagicDaily": "Magic Daily", "MaximumCleaning": "Maximale reiniging", "NightWash": "Nachtprogramma", "Normal45": "Normaal 45°C", "Normal65": "Normaal 65°C", "PreRinse": "Voorspoelen", "Quick45": "Snel programma 45°C", "Quick65": "Snel programma 65°C", "SteamFresh": "", "Super60": "Super 60°C"} %}
          {% if program.name in programTranslation %}
            {{ programTranslation[program.name] }}
          {% else %}
            {{ program.name }}
          {% endif %}

      - name: Wasmachine resterende minuten
        icon: mdi:clock
        state: >-
          {% if is_state("sensor.wasmachine_remaining_program_time", "unavailable") or is_state("switch.wasmachine_power", "off") -%}
            unavailable
          {%- else -%}
            {% set seconds = as_timestamp(states("sensor.wasmachine_remaining_program_time")) - as_timestamp(utcnow()) | int  %}
            {% set minutes = (seconds / 60) | round(0, "ceil") %}

            {%- if minutes <= 0 -%}
              Klaar
            {%- elif minutes == 1 -%}
              1 minuut
            {%- else -%}
              {{ minutes }} minuten
            {%- endif -%}
          {%- endif %}

      - name: Vaatwasser resterende minuten
        icon: mdi:clock
        state: >-
          {% if is_state("sensor.vaatwasser_remaining_program_time", "unavailable") or is_state("switch.vaatwasser_power", "off") -%}
            unavailable
          {%- else -%}
            {% set seconds = as_timestamp(states("sensor.vaatwasser_remaining_program_time")) - as_timestamp(utcnow()) | int  %}
            {% set minutes = (seconds / 60) | round(0, "ceil") %}

            {%- if minutes <= 0 -%}
              Klaar
            {%- elif minutes == 1 -%}
              1 minuut
            {%- else -%}
              {{ minutes }} minuten
            {%- endif -%}
          {%- endif %}

      - name: Wasmachine status
        icon: mdi:washing-machine
        state: >-
          {% if states("binary_sensor.wasmachine_door") == "on" -%}
            Deur open
          {% elif states("sensor.wasmachine_operation_state") == "Finished" -%}
            Klaar
          {% elif states("sensor.wasmachine_operation_state") == "Run" -%}
            {{ states("sensor.wasmachine_resterende_minuten") }}
          {% elif states("binary_sensor.wasmachine_remote_start") == "on" -%}
            Uitgestelde start
          {%- else -%}
            {{ states("switch.wasmachine_power") }}
          {%- endif %}

      - name: Vaatwasser status
        icon: mdi:dishwasher
        state: >-
          {% if states("binary_sensor.vaatwasser_door") == "on" -%}
            Deur open
          {% elif states("sensor.vaatwasser_operation_state") == "Finished" -%}
            Klaar
          {% elif states("sensor.vaatwasser_operation_state") == "Run" -%}
            {{ states("sensor.vaatwasser_resterende_minuten") }}
          {% elif states("binary_sensor.vaatwasser_remote_start") == "on" -%}
            Uitgestelde start
          {%- else -%}
            {{ states("switch.vaatwasser_power") }}
          {%- endif %}

automation:
  - id: dishwasher_auto_daily_start
    alias: Vaatwasser dagelijks starten
    mode: single
    trigger:
      platform: time
      at: input_datetime.dishwasher_daily_start
    condition:
      - condition: state
        entity_id: binary_sensor.vaatwasser_remote_start
        state: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.vaatwasser_program_auto2

  - id: dishwasher_set_daily_start_time
    alias: Vaatwasser tijd dagelijks aanpassen
    mode: single
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        at: "12:00:00"
    action:
      - variables:
          weekday_time: "04:30"
          weekend_time: "07:30"
          schedule_time: >
            {% set weekday = now().isoweekday() %}
            {% set hour = now().hour %}
            
            {% if hour < 4 %}
              {% if weekday in [6, 7] %}
                {{ weekend_time }}
              {% else %}
                {{ weekday_time }}
              {% endif %}
            {% else %}
              {% if weekday in [5, 6] %}
                {{ weekend_time }}
              {% else %}
                {{ weekday_time }}
              {% endif %}
            {% endif %}

      - service: input_datetime.set_datetime
        data:
          entity_id: input_datetime.dishwasher_daily_start
          time: "{{ schedule_time }}"

# The washing machine remains sometimes unavailable. Reloading the integration to "fix" this
# Issue: https://github.com/home-assistant/core/issues/66063
  - id: reload_home_connect
    alias: Wasmachine - Herlaad Home Connect integratie
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.zolder_power
        above: 2
        for:
          minutes: 2
      - platform: numeric_state
        entity_id: sensor.zolder_power
        below: 2
        for:
          minutes: 2
    condition:
      # Should be a little higher than the minutes in the triggers, to deal with restarts.
      - "{{ now() | as_timestamp(0) - states('sensor.uptime') | as_timestamp(0) > 200 }}"
    action:
      - alias: Reload Home Connect integration
        service: homeassistant.reload_config_entry
        target:
          entity_id: switch.wasmachine_power
