  
input_boolean:
  guest_mode:
    name: Gastmodus
    initial: off
    icon: mdi:account-check
  vacation_mode:
    name: Vakantiemodus
    initial: off
    icon: mdi:beach

group:
  residents:
    name: Bewoners
    icon: mdi:human-greeting
    entities:
      - person.sander
  
automation:
  - id: vacation_mode_on
    alias: Vakantie modus - automatisch activeren bij afwezigheid
    mode: single
    trigger:
      - platform: state
        entity_id: group.residents
        to: not_home
        for: "24:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.vacation_mode

  - id: vacation_mode_off
    alias: Vakantie modus - automatisch deactiveren bij aanwezigheid
    mode: single
    trigger:
      - platform: state
        entity_id: group.residents
        to: home
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.vacation_mode

  - id: vacation_mode_presence
    alias: Vakantie modus - aanwezigheid nabootsen
    mode: parallel
    trigger:
      - platform: numeric_state
        entity_id: sensor.woonkamer_lichtsterkte_illuminance_lux
        below: 15
        for:
          minutes: 30
        id: woonkamer_avond
      - platform: time
        at: "23:30:00"
        id: tanden_poetsen
      - platform: time
        at: "00:45:00"
        id: nacht_toilet
      - platform: time
        at: "00:00:00"
        id: alles_uit
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: woonkamer_avond
            sequence:
              - delay:
                  minutes: "{{ range(0, 15) | random }}"
              - service: light.turn_on
                data:
                  entity_id: light.woonkamer_groot_2
                  profile: helder
              - wait_for_trigger:
                  - platform: time
                    at: "23:00:00"
              - delay:
                  minutes: "{{ range(0, 30) | random }}"
              - service: light.turn_off
                data:
                  entity_id: light.woonkamer

          - conditions:
              - condition: trigger
                id: tanden_poetsen
            sequence:
              - delay:
                  minutes: "{{ range(0, 30) | random }}"
              - service: light.turn_on
                data:
                  entity_id: light.badkamer
                  profile: helder
              - delay:
                  minutes: "{{ range(3, 5) | random }}"
              - service: light.turn_off
                data:
                  entity_id: light.badkamer

          - conditions:
              - condition: trigger
                id: nacht_toilet
            sequence:
              - delay:
                  minutes: "{{ range(0, 30) | random }}"
              - service: light.turn_on
                data:
                  entity_id: light.badkamer
                  profile: ontspannen
              - delay:
                  minutes: "{{ range(1, 3) | random }}"
              - service: light.turn_off
                data:
                  entity_id: light.badkamer

          - conditions:
              - condition: trigger
                id: alles_uit
            sequence:
              - service: script.everything_off
