template:
  - sensor:
      - name: Wasmachine resterende minuten
        icon: mdi:clock
        state: >-
          {% from "home_connect.jinja" import remaining_time %}
          {{
            remaining_time(
              "sensor.bosch_wawh2643nl_68a40e31630b_bsh_common_option_remainingprogramtime",
              "sensor.bosch_wawh2643nl_68a40e31630b_bsh_common_setting_powerstate"
            )
          }}
        unit_of_measurement: minuten

      - name: Vaatwasser resterende minuten
        icon: mdi:clock
        state: >-
          {% from "home_connect.jinja" import remaining_time %}
          {{
            remaining_time(
              "sensor.bosch_sbv88tx36e_68a40e0cd8f6_bsh_common_option_remainingprogramtime",
              "sensor.bosch_sbv88tx36e_68a40e0cd8f6_bsh_common_setting_powerstate"
            )
          }}
        unit_of_measurement: minuten

      - name: Oven resterende minuten
        icon: mdi:clock
        state: >-
          {% from "home_connect.jinja" import remaining_time %}
          {{
            remaining_time(
              "sensor.384090532720002735_001_bsh_common_option_remainingprogramtime",
              "sensor.384090532720002735_001_bsh_common_setting_powerstate"
            )
          }}
        unit_of_measurement: minuten

      - name: Wasmachine status
        icon: mdi:washing-machine
        state: >-
          {% if states("binary_sensor.bosch_wawh2643nl_68a40e31630b_connected") in ["unavailable", "off"] -%}
            off
          {% elif is_state("binary_sensor.bosch_wawh2643nl_68a40e31630b_bsh_common_status_doorstate", "on") -%}
            Deur open
          {% elif is_state("sensor.bosch_wawh2643nl_68a40e31630b_bsh_common_status_operationstate", "Loopt") -%}
            {% set minuten = states("sensor.wasmachine_resterende_minuten") %}
            {{ minuten ~ " " ~ iif(minuten == "1", "minuut", "minuten") }}
          {% elif is_state("binary_sensor.bosch_wawh2643nl_68a40e31630b_bsh_common_status_remotecontrolstartallowed", "on") -%}
            Uitgestelde start
          {%- else -%}
            {{ states("sensor.bosch_wawh2643nl_68a40e31630b_bsh_common_status_operationstate") }}
          {%- endif %}
        attributes:
          "bedrijfsstatus": >-
            {{ states("sensor.bosch_wawh2643nl_68a40e31630b_bsh_common_status_operationstate") }}
          "deur": >-
            {{
              iif(
                states("binary_sensor.bosch_wawh2643nl_68a40e31630b_bsh_common_status_doorstate") == "on",
                "Open",
                "Gesloten"
              )
            }}
          "programma": >-
            {{ states("sensor.bosch_wawh2643nl_68a40e31630b_active_program") }}
          "Verbonden": >-
            {{
              iif(
                states("binary_sensor.bosch_wawh2643nl_68a40e31630b_connected") == "on",
                "Verbonden",
                "Verbroken"
              )
            }}
          "voortgang": >-
            {{
              iif(
                states("sensor.bosch_wawh2643nl_68a40e31630b_bsh_common_option_programprogress") != "unavailable",
                states("sensor.bosch_wawh2643nl_68a40e31630b_bsh_common_option_programprogress") ~ "%",
                "unavailable"
              )
            }}

      - name: Vaatwasser status
        icon: mdi:dishwasher
        state: >-
          {% if is_state("binary_sensor.bosch_sbv88tx36e_68a40e0cd8f6_connected", "off") -%}
            Verbroken
          {% elif is_state("binary_sensor.bosch_sbv88tx36e_68a40e0cd8f6_bsh_common_status_doorstate", "on") -%}
            Deur open
          {% elif is_state("sensor.bosch_sbv88tx36e_68a40e0cd8f6_bsh_common_status_operationstate", "Loopt") -%}
            {% set minuten = states("sensor.vaatwasser_resterende_minuten") %}
            {{ minuten ~ " " ~ iif(minuten == "1", "minuut", "minuten") }}
          {% elif is_state("binary_sensor.bosch_sbv88tx36e_68a40e0cd8f6_bsh_common_status_remotecontrolstartallowed", "on") -%}
            Uitgestelde start
          {% elif is_state("switch.bosch_sbv88tx36e_68a40e0cd8f6_bsh_common_setting_powerstate", "off") -%}
            off
          {%- else -%}
            {{ states("sensor.bosch_sbv88tx36e_68a40e0cd8f6_bsh_common_status_operationstate") }}
          {%- endif %}
        attributes:
          "bedrijfsstatus": >-
            {{ states("sensor.bosch_sbv88tx36e_68a40e0cd8f6_bsh_common_status_operationstate") }}
          "deur": >-
            {{
              iif(
                states("binary_sensor.bosch_sbv88tx36e_68a40e0cd8f6_bsh_common_status_doorstate") == "on",
                "Open",
                "Gesloten"
              )
            }}
          "programma": >-
            {{ states("sensor.bosch_sbv88tx36e_68a40e0cd8f6_active_program") }}
          "Verbonden": >-
            {{
              iif(
                states("binary_sensor.bosch_sbv88tx36e_68a40e0cd8f6_connected") == "on",
                "Verbonden",
                "Verbroken"
              )
            }}
          "voortgang": >-
            {{
              iif(
                states("sensor.bosch_sbv88tx36e_68a40e0cd8f6_bsh_common_option_programprogress") != "unavailable",
                states("sensor.bosch_sbv88tx36e_68a40e0cd8f6_bsh_common_option_programprogress") ~ "%",
                "unavailable"
              )
            }}

      - name: Oven status
        icon: mdi:stove
        state: >-
          {% if is_state("binary_sensor.384090532720002735_001_connected", "off") -%}
            Verbroken
          {% elif is_state("binary_sensor.384090532720002735_001_bsh_common_status_doorstate", "on") -%}
            Deur open
          {% elif is_state("sensor.384090532720002735_001_bsh_common_status_operationstate", "Loopt") -%}
            {% if is_state("sensor.oven_resterende_minuten", "-1") -%}
              {{ states("sensor.384090532720002735_001_bsh_common_option_programprogress") ~ "%" }}
            {%- else -%}
              {% set minuten = states("sensor.oven_resterende_minuten") %}
              {{ minuten ~ " " ~ iif(minuten == "1", "minuut", "minuten") }}
            {%- endif %}
          {% elif states("sensor.384090532720002735_001_bsh_common_setting_powerstate") != "Aan" -%}
            off
          {%- else -%}
            {{ states("sensor.384090532720002735_001_bsh_common_status_operationstate") }}
          {%- endif %}
        attributes:
          "bedrijfsstatus": >-
            {{ states("sensor.384090532720002735_001_bsh_common_status_operationstate") }}
          "deur": >-
            {{
              iif(
                states("binary_sensor.384090532720002735_001_bsh_common_status_doorstate") == "on",
                "Open",
                "Gesloten"
              )
            }}
          "programma": >-
            {{ states("sensor.384090532720002735_001_active_program") }}
          "Verbonden": >-
            {{
              iif(
                states("binary_sensor.384090532720002735_001_connected") == "on",
                "Verbonden",
                "Verbroken"
              )
            }}
          "voortgang": >-
            {{
              iif(
                states("sensor.384090532720002735_001_bsh_common_option_programprogress") != "unavailable",
                states("sensor.384090532720002735_001_bsh_common_option_programprogress") ~ "%",
                "unavailable"
              )
            }}

automation:
  - id: home_connect_conversation_remaining_time
    alias: "Spraakassistent: Wanneer is de machine klaar"
    mode: single
    triggers:
      - trigger: conversation
        command:
          - Wanneer is de {machine} klaar
    actions:
      - alias: Set repsonse
        set_conversation_response: >-
          {% if trigger.slots.machine == "vaatwasser" and states("sensor.vaatwasser_resterende_minuten") != "unavailable" %}
            over {{ states("sensor.vaatwasser_resterende_minuten") }}
          {% elif trigger.slots.machine == "wasmachine" and states("sensor.wasmachine_resterende_minuten") != "unavailable" %}
            over {{ states("sensor.wasmachine_resterende_minuten") }}
          {% elif trigger.slots.machine == "oven" and states("sensor.oven_resterende_minuten") != "unavailable" %}
            over {{ states("sensor.oven_resterende_minuten") }}
          {% else %}
            Ik weet het niet, staat de {{ trigger.slots.machine }} wel aan?
          {% endif %}
