  
input_boolean:
  guest_mode:
    name: Guest Mode
    initial: off
    icon: mdi:account-check
  vacation_mode:
    name: Vacation Mode
    initial: off
    icon: mdi:beach

group:
  residents:
    name: Residents
    icon: mdi:human-greeting
    entities:
      - person.sander
  
automation:
  - id: vacation_mode_on
    alias: Vakantie modus activeren bij langere afwezigheid
    initial_state: on
    mode: single
    trigger:
      - platform: state
        entity_id: group.residents
        to: not_home
        for: '24:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.vacation_mode

  - id: vacation_mode_off
    alias: Automatisch vakantie modus deactiveren bij aanwezigheid
    initial_state: on
    mode: single
    trigger:
      - platform: state
        entity_id: group.residents
        to: home
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.vacation_mode
