home_connect:
  client_id: !secret home_connect_client_id
  client_secret: !secret home_connect_client_secret

input_datetime:
  dishwasher_daily_start:
    name: Vaatwasser start
    has_date: false
    has_time: true

template:
  - sensor:
      - name: Wasmachine programma
        icon: mdi:washing-machine
        state: >-
          {% set prefix = "Wasmachine Program " %}
          {% set program = namespace(name = "unavailable") %}
          {% for switch in states.switch -%}
            {%- if switch.name.startswith(prefix) and switch.state == "on" %}
              {% set program.name = switch.name.split(prefix)[1] %}
            {%- endif %}
          {%- endfor %}
          {{ program.name }}

      - name: Vaatwasser programma
        icon: mdi:dishwasher
        state: >-
          {% set prefix = "Vaatwasser Program " %}
          {% set program = namespace(name = "unavailable") %}
          {% for switch in states.switch -%}
            {%- if switch.name.startswith(prefix) and switch.state == "on" %}
              {% set program.name = switch.name.split(prefix)[1] %}
            {%- endif %}
          {%- endfor %}
          {{ program.name }}

      - name: Wasmachine resterende tijd
        icon: mdi:clock
        state: >-
          {% if is_state("sensor.wasmachine_remaining_program_time", "unavailable") or is_state("switch.wasmachine_power", "off") -%}
            unavailable
          {%- else -%}
            {% set seconds = as_timestamp(states("sensor.wasmachine_remaining_program_time")) - as_timestamp(utcnow()) | int  %}
            {% set minutes = ((seconds % 3600) / 60) | int %}
            {% set hours = (seconds / 3600) | int %}

            {%- if seconds <= 0 -%}
              Klaar
            {%- elif seconds < 60 -%}
              {{ seconds }} seconden
            {%- else -%}
              {%- if hours > 0 -%}
                {%- if hours == 1 -%}
                  1 uur
                {%- else -%}
                  {{ hours }} uur
                {%- endif -%}
              {%- endif -%}
              {%- if minutes > 0 -%}
                {%- if hours > 0 -%}
                  {{ ", " }}
                {%- endif -%}
                {%- if minutes == 1 -%}
                  1 minuut
                {%- else -%}
                  {{ minutes }} minuten
                {%- endif -%}
              {%- endif -%}
            {%- endif -%}
          {%- endif %}

      - name: Vaatwasser resterende tijd
        icon: mdi:clock
        state: >-
          {% if is_state("sensor.vaatwasser_remaining_program_time", "unavailable") or is_state("switch.vaatwasser_power", "off") -%}
            unavailable
          {%- else -%}
            {% set seconds = as_timestamp(states("sensor.vaatwasser_remaining_program_time")) - as_timestamp(utcnow()) | int  %}
            {% set minutes = ((seconds % 3600) / 60) | int %}
            {% set hours = (seconds / 3600) | int %}

            {%- if seconds <= 0 -%}
              Klaar
            {%- elif seconds < 60 -%}
              {{ seconds }} seconden
            {%- else -%}
              {%- if hours > 0 -%}
                {%- if hours == 1 -%}
                  1 uur
                {%- else -%}
                  {{ hours }} uur
                {%- endif -%}
              {%- endif -%}
              {%- if minutes > 0 -%}
                {%- if hours > 0 -%}
                  {{ ", " }}
                {%- endif -%}
                {%- if minutes == 1 -%}
                  1 minuut
                {%- else -%}
                  {{ minutes }} minuten
                {%- endif -%}
              {%- endif -%}
            {%- endif -%}
          {%- endif %}

      - name: Wasmachine resterende minuten
        icon: mdi:clock
        state: >-
          {% if is_state("sensor.wasmachine_remaining_program_time", "unavailable") or is_state("switch.wasmachine_power", "off") -%}
            unavailable
          {%- else -%}
            {% set seconds = as_timestamp(states("sensor.wasmachine_remaining_program_time")) - as_timestamp(utcnow()) | int  %}
            {% set minutes = (seconds / 60) | round(0, "ceil") %}

            {%- if minutes <= 0 -%}
              Klaar
            {%- elif minutes == 1 -%}
              1 minuut
            {%- else -%}
              {{ minutes }} minuten
            {%- endif -%}
          {%- endif %}

      - name: Vaatwasser resterende minuten
        icon: mdi:clock
        state: >-
          {% if is_state("sensor.vaatwasser_remaining_program_time", "unavailable") or is_state("switch.vaatwasser_power", "off") -%}
            unavailable
          {%- else -%}
            {% set seconds = as_timestamp(states("sensor.vaatwasser_remaining_program_time")) - as_timestamp(utcnow()) | int  %}
            {% set minutes = (seconds / 60) | round(0, "ceil") %}

            {%- if minutes <= 0 -%}
              Klaar
            {%- elif minutes == 1 -%}
              1 minuut
            {%- else -%}
              {{ minutes }} minuten
            {%- endif -%}
          {%- endif %}

automation:
  - id: dishwasher_auto_daily_start
    alias: Vaatwasser dagelijks starten
    mode: single
    trigger:
      platform: time
      at: input_datetime.dishwasher_daily_start
    condition:
      - condition: state
        entity_id: binary_sensor.vaatwasser_remote_start
        state: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.vaatwasser_program_auto2

  - id: dishwasher_set_daily_start_time
    alias: Vaatwasser tijd dagelijks aanpassen
    mode: single
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        at: "12:00:00"
    action:
      - variables:
          weekday_time: "04:30"
          weekend_time: "07:30"
          schedule_time: >
            {% set weekday = now().isoweekday() %}
            {% set hour = now().hour %}
            
            {% if hour < 4 %}
              {% if weekday in [6, 7] %}
                {{ weekend_time }}
              {% else %}
                {{ weekday_time }}
              {% endif %}
            {% else %}
              {% if weekday in [5, 6] %}
                {{ weekend_time }}
              {% else %}
                {{ weekday_time }}
              {% endif %}
            {% endif %}

      - service: input_datetime.set_datetime
        data:
          entity_id: input_datetime.dishwasher_daily_start
          time: "{{ schedule_time }}"
