sensor:
  - platform: home_connect
    refresh_token: !secret home_connect_refresh_token

group:
  vaatwasser:
    name: Vaatwasser
    entities:
      - sensor.bosch_sbv88tx36e_state
      - sensor.bosch_sbv88tx36e_door
      - sensor.bosch_sbv88tx36e_program
      - sensor.bosch_sbv88tx36e_elapsed
      - sensor.bosch_sbv88tx36e_remaining

  wasmachine:
    name: Wasmachine
    entities:
      - sensor.bosch_wawh2643nl_state
      - sensor.bosch_wawh2643nl_door 
      - sensor.bosch_wawh2643nl_program
      - sensor.bosch_wawh2643nl_elapsed
      - sensor.bosch_wawh2643nl_remaining
