homeassistant:
  customize:
    light.gekleurde_licht:
      icon: mdi:led-strip-variant
    light.bedlampje_links:
      icon: mdi:desk-lamp
    light.bedlampje_rechts:
      icon: mdi:desk-lamp
    light.bedlampen:
      icon: mdi:desk-lamp

light:
  - platform: group
    name: Bedlampen
    entities:
      - light.bedlampje_links
      - light.bedlampje_rechts

script:
  eettafel_on:
    alias: Eettafel lampen aan animatie
    variables:
      delay_ms: 100
      brightness: 140
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.eettafel_hanglamp_5
          brightness: '{{ brightness }}'
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_on
        data:
          entity_id: light.eettafel_hanglamp_4
          brightness: '{{ brightness }}'
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_on
        data:
          entity_id: light.eettafel_hanglamp_3
          brightness: '{{ brightness }}'
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_on
        data:
          entity_id: light.eettafel_hanglamp_2
          brightness: '{{ brightness }}'
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_on
        data:
          entity_id: light.eettafel_hanglamp_1
          brightness: '{{ brightness }}'

  eettafel_off:
    alias: Eettafel lampen uit animatie
    variables:
      delay_ms: 100
    sequence:
      - service: light.turn_off
        entity_id: light.eettafel_hanglamp_1
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_off
        entity_id: light.eettafel_hanglamp_2
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_off
        entity_id: light.eettafel_hanglamp_3
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_off
        entity_id: light.eettafel_hanglamp_4
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_off
        entity_id: light.eettafel_hanglamp_5
  
switch:
  - platform: template
    switches:
      eettafellamp:
        friendly_name: Eettafel
        icon_template: mdi:vanity-light
        value_template: >
          {{ is_state('light.eettafel', 'on') }}
        turn_on:
          service: script.eettafel_on
        turn_off:
          service: script.eettafel_off
