homeassistant:
  customize:
    light.hue_smart_plug_1:
      icon: mdi:led-strip-variant
    light.hue_filament_bulb_1_4:
      icon: mdi:desk-lamp
    light.hue_filament_bulb_1_3:
      icon: mdi:desk-lamp

group:
  achtertuin_lampen:
    name: Achtertuin
    icon: mdi:coach-lamp
    entities:
      - light.achtertuin_lamp_1
      - light.achtertuin_lamp_2

  slaapkamer_plafond_lamp:
    name: Slaapkamer plafond
    icon: mdi:ceiling-light
    entities:
      - light.slaapkamer_lamp_1
      - light.slaapkamer_lamp_2

  logeerkamer_plafond_lamp:
    name: Logeerkamer plafond
    icon: mdi:ceiling-light
    entities:
      - light.logeerkamer_lamp
      - light.hue_color_lamp_1_3

  kledingkamer_plafond_lamp:
    name: Kledingkamer plafond
    icon: mdi:ceiling-light
    entities:
      - light.hue_color_spot_2
      - light.hue_color_spot_3
      - light.hue_color_spot_1
      - light.hue_color_spot_4

  zolder_plafond_lamp:
    name: Zolder plafond
    icon: mdi:ceiling-light
    entities:
      - light.zolder_lamp
      - light.hue_color_lamp_1_4

script:
  eettafel_on:
    alias: Eettafel lampen aan animatie
    sequence:
      - service: light.turn_on
        entity_id: light.hue_filament_bulb_3 #5
      - delay:
          milliseconds: 100
      - service: light.turn_on
        entity_id: light.hue_filament_bulb_4 #4
      - delay:
          milliseconds: 100
      - service: light.turn_on
        entity_id: light.hue_filament_bulb_1 #3
      - delay:
          milliseconds: 100
      - service: light.turn_on
        entity_id: light.hue_filament_bulb_5 #2
      - delay:
          milliseconds: 100
      - service: light.turn_on
        entity_id: light.hue_filament_bulb_2 #1

  eettafel_off:
    alias: Eettafel lampen uit animatie
    sequence:
      - service: light.turn_off
        entity_id: light.hue_filament_bulb_2 #1
      - delay:
          milliseconds: 100
      - service: light.turn_off
        entity_id: light.hue_filament_bulb_5 #2
      - delay:
          milliseconds: 100
      - service: light.turn_off
        entity_id: light.hue_filament_bulb_1 #3
      - delay:
          milliseconds: 100
      - service: light.turn_off
        entity_id: light.hue_filament_bulb_4 #4
      - delay:
          milliseconds: 100
      - service: light.turn_off
        entity_id: light.hue_filament_bulb_3 #5
  
switch:
  - platform: template
    switches:
      eettafellamp:
        friendly_name: Eettafel
        icon_template: mdi:vanity-light
        value_template: "{{ is_state('light.eettafel', 'on') }}"
        turn_on:
          service: script.eettafel_on
        turn_off:
          service: script.eettafel_off
