homeassistant:
  customize:
    light.hue_smart_plug_1:
      icon: mdi:led-strip-variant
    light.hue_filament_bulb_1_4:
      icon: mdi:desk-lamp
    light.hue_filament_bulb_1_3:
      icon: mdi:desk-lamp
    light.bedlampen:
      icon: mdi:desk-lamp

light:
  - platform: group
    name: Bedlampen
    entities:
      - light.hue_filament_bulb_1_4
      - light.hue_filament_bulb_1_3

script:
  eettafel_on:
    alias: Eettafel lampen aan animatie
    variables:
      delay_ms: 100
      brightness: 140
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.hue_filament_bulb_3 #5
          brightness: '{{ brightness }}'
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_on
        data:
          entity_id: light.hue_filament_bulb_4 #4
          brightness: '{{ brightness }}'
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_on
        data:
          entity_id: light.hue_filament_bulb_1 #3
          brightness: '{{ brightness }}'
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_on
        data:
          entity_id: light.hue_filament_bulb_5 #2
          brightness: '{{ brightness }}'
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_on
        data:
          entity_id: light.hue_filament_bulb_2 #1
          brightness: '{{ brightness }}'

  eettafel_off:
    alias: Eettafel lampen uit animatie
    variables:
      delay_ms: 100
    sequence:
      - service: light.turn_off
        entity_id: light.hue_filament_bulb_2 #1
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_off
        entity_id: light.hue_filament_bulb_5 #2
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_off
        entity_id: light.hue_filament_bulb_1 #3
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_off
        entity_id: light.hue_filament_bulb_4 #4
      - delay:
          milliseconds: '{{ delay_ms }}'
      - service: light.turn_off
        entity_id: light.hue_filament_bulb_3 #5
  
switch:
  - platform: template
    switches:
      eettafellamp:
        friendly_name: Eettafel
        icon_template: mdi:vanity-light
        value_template: >
          {{ is_state('light.eettafel', 'on') }}
        turn_on:
          service: script.eettafel_on
        turn_off:
          service: script.eettafel_off
