command_line:
  - sensor:
      name: Leeghwaterbad Beschikbare tickets
      unique_id: leeghwaterbad_beschikbare_tickets
      icon: mdi:playlist-check
      scan_interval: 10800
      command: !secret leeghwaterbad_command # "python custom_scripts/leeghwaterbad.py 'email' 'password'"
      command_timeout: 120
      value_template: "{{ value_json.abonnement.beschikbaar }}"
      json_attributes_path: "$.abonnement"
      json_attributes:
        - totaal
        - procent
  - sensor:
      name: Leeghwaterbad Verloopdatum
      unique_id: leeghwaterbad_verloopdatum
      icon: mdi:calendar-sync
      scan_interval: 10800
      command: !secret leeghwaterbad_command # "python custom_scripts/leeghwaterbad.py 'email' 'password'"
      command_timeout: 120
      value_template: "{{ value_json.abonnement.verloopdatum }}"
      device_class: timestamp
      availability: >-
        {{ not is_state("sensor.leeghwaterbad_verloopdatum", "1970-01-01T00:00:00+00:00") }}
  - sensor:
      name: Leeghwaterbad Volgende bestelling
      unique_id: leeghwaterbad_volgende_bestelling
      icon: mdi:swim
      scan_interval: 10800
      command: !secret leeghwaterbad_command # "python custom_scripts/leeghwaterbad.py 'email' 'password'"
      command_timeout: 120
      value_template: "{{ value_json.bestelling.volgende }}"
      json_attributes_path: "$.bestelling"
      json_attributes:
        - product
        - aantal
        - ordernummer
        - ticket
      device_class: timestamp
      availability: >-
        {{ not is_state("sensor.leeghwaterbad_volgende_bestelling", "1970-01-01T00:00:00+00:00") }}

automation:
  - id: notification_leeghwaterbad_ticket
    alias: "Notificatie: Leeghwaterbad ticket"
    mode: single
    triggers:
      - trigger: state
        entity_id: person.sander
        to: Leeghwaterbad
    conditions:
      - condition: template
        value_template: >-
          {{
            0 <= as_timestamp(states("sensor.leeghwaterbad_volgende_bestelling"), 0) - as_timestamp(now()) <= 60 * 60
          }}
    actions:
      - action: notify.sander
        data:
          title: 🏊 Veel plezier met zwemmen!
          message: >-
            Klik voor de tickets
          data:
            tag: leeghwaterbad
            image: >-
              {{ state_attr("sensor.leeghwaterbad_volgende_bestelling", "ticket")}}
            url: >-
              {{ state_attr("sensor.leeghwaterbad_volgende_bestelling", "ticket")}}
