sensor:
  - platform: template
    sensors:
      mbp_menu_bar_text:
        friendly_name: Menu bar text
        icon_template: mdi:laptop
        value_template: >
          {%- if states("sensor.count_lights_on") | int > 0 -%}
            {{ states("sensor.count_lights_on") }}💡 
          {%- endif -%}
          {%- if states("sensor.count_doors_open") | int > 0 -%}
            {{ states("sensor.count_doors_open") }}🚪 
          {%- endif -%}
          {%- if states("sensor.count_windows_open") | int > 0 -%}
            {{ states("sensor.count_windows_open") }}🪟 
          {%- endif -%}
          {%- if states("sensor.count_media_players_on") | int > 0 -%}
            {{ states("sensor.count_media_players_on") }}📺 
          {%- endif -%}
