sensor:
  - platform: moon

automation:
  - id: full_moon
    alias: Volle maan bericht
    description: Berichtje bij volle maan
    initial_state: on
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.moon
        to: Full Moon
    action:
      - service: notify.telegram_huisgroep
        data:
          title: 🌕 Maan
          message: >-
            {{
              [
                "Het is volle maan vanavond!",
                "Wil je een volle maan zien? Dat kan vanavond",
                "Een volle maan!",
              ] | random
            }}  
