automation:
  - id: notification_ip_changed
    alias: "Notificatie: Externe IP veranderd"
    mode: single
    trigger:
      platform: state
      entity_id: sensor.myip
    condition:
      - condition: template
        value_template: >-
          {{ trigger.to_state.state not in [trigger.from_state.state, "unknown", "unavailable"] }}
    action:
      - service: notify.sander
        data:
          title: 🌍 Externe IP gewijzigd
          message: >-
            Nieuwe ip: {{ states('sensor.myip') }}, check of de DDNS update gelukt is.
          data:
            group: ddns
            url: /dashboard-systems/internet
