automation:
  - id: notification_ip_changed
    alias: "Notificatie: Externe IP veranderd"
    mode: single
    triggers:
      - trigger: state
        entity_id: sensor.myip
    conditions:
      - condition: template
        value_template: >-
          {{ trigger.to_state.state not in [trigger.from_state.state, "unknown", "unavailable"] }}
    actions:
      - alias: Send the notification
        action: notify.discord
        data:
          message: ""
          target: !secret discord_monitoring
          data:
            embed:
              color: 16753920 # Orange
              title: 🌍 Externe IP gewijzigd
              description: |
                Nieuwe ip: {{ states('sensor.myip') }}
                Check of de DDNS update gelukt is
