sensor:
  - platform: rest
    name: Bushalte Orinocostraat
    scan_interval: 300 # 60 * 5
    resource: https://ovzoeker.nl/api/arrivals/2433780
    device_class: timestamp
    value_template: >-
      {% if value_json.arrivals | length > 0 %}
        {% set timestamp = value_json.arrivals[0].ts | default(0) | int %}
        {% set punctuality = value_json.arrivals[0].punctuality | default(0) | int %}
        {{ (timestamp + punctuality) | timestamp_local }}
      {% else %}
        unavailable
      {% endif %}
    json_attributes:
      - arrivals
      - stop
