sensor:
  - platform: rest
    name: Bushalte Orinocostraat
    scan_interval: 300 # 60 * 5
    resource: https://ovzoeker.nl/api/arrivals/2433780
    device_class: timestamp
    value_template: >-
      {% set key = 0 %}
      {% set time = "unavailable" %}
      {%- if value_json.arrivals | length > key -%}
        {%- set timestamp = value_json.arrivals[key].ts | default(0) | int -%}
        {%- set punctuality = value_json.arrivals[key].punctuality | default(0) | int -%}
        {%- set time = (timestamp + punctuality)| timestamp_local -%}
      {%- endif -%}
      {{ time }}
    json_attributes:
      - arrivals
      - stop
