sensor:
  - platform: rest
    name: Bushalte Orinocostraat
    scan_interval: 300 # 60 * 5
    resource: https://ovzoeker.nl/api/arrivals/2424233
    device_class: timestamp
    value_template: >-
      {% set timestamp = value_json.arrivals[0].ts | default(0) | int %}
      {% set punctuality = value_json.arrivals[0].punctuality | default(0) | int %}
      {{ (timestamp + punctuality) | timestamp_local | replace(" ", "T") }}
    json_attributes:
      - arrivals
      - stop
