sensor:
  - platform: p2000
    name: P2000 Ambulance
    icon: mdi:ambulance
    regios: 11
    disciplines: Ambulancediensten
    scan_interval: 60
    radius: 5000
    nolocation: True

  - platform: p2000
    name: P2000 Brandweer
    icon: mdi:fire-truck
    regios: 11
    disciplines: Brandweerdiensten
    scan_interval: 60
    radius: 5000
    nolocation: True

  - platform: p2000
    name: P2000 Dichtbij
    icon: mdi:alert
    regios: 11
    # disciplines: Ambulancediensten,Brandweerdiensten,Politiediensten
    scan_interval: 60
    radius: 250
    nolocation: False

  - platform: p2000
    name: P2000 Politie
    icon: mdi:car-emergency
    regios: 11
    disciplines: Politiediensten
    scan_interval: 60
    radius: 5000
    nolocation: True

  - platform: p2000
    name: P2000 Lifeliner 1
    icon: mdi:helicopter
    regios: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
    capcodes: 0120901
    scan_interval: 60
    nolocation: True

automation:
  - id: notification_p2000
    alias: "Notificatie: P200 bericht in de buurt"
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.p2000_dichtbij
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
    action:
      - alias: Sent a notification with url
        service: notify.all_phones_and_tv
        data:
          title: >-
            {% set state = state_attr("sensor.p2000_dichtbij", "discipline") | lower %}
            {% if "ambulance" in state %} 🚑
            {% elif "brandweer" in state %} 🚒
            {% elif "politie" in state %} 🚓
            {% else %}🚨 {% endif %}
            P2000 melding
          message: >-
            {{ states("sensor.p2000_dichtbij") }}
          data:
            group: p2000
            push:
              interruption-level: v
            action_data:
              latitude: "{{ state_attr('sensor.p2000_dichtbij', 'latitude') }}"
              longitude: "{{ state_attr('sensor.p2000_dichtbij', 'longitude') }}"
              shows_user_location: true
            url: >-
              https://www.google.com/maps/search/?api=1&query={{ state_attr("sensor.p2000_dichtbij", "latitude") }},{{ state_attr("sensor.p2000_dichtbij", "longitude") }}
