homeassistant:
  customize:
    script.play_chromecast_radio:
      friendly_name: Play
      icon: mdi:play
    script.stop_chromecast_radio:
      friendly_name: Stop
      icon: mdi:stop

input_select:
  chromecast_radio_speakers:
    name: 'Select Speakers'
    options:
      - Huiskamer
      - Zolder
      - All
    initial: Huiskamer
    icon: mdi:speaker-wireless

input_number:
  volume_radio:
    name: Volume
    icon: mdi:volume-high
    initial: 4
    min: 0
    max: 20
    step: 1

script:
  play_chromecast_radio:
    description: 'Play radio streams on a Chromecast device'
    fields:
      stream:
        description: 'The http stream to play'
        example: 'https://icecast-qmusicnl-cdp.triple-it.nl/Qmusic_nl_live_96.mp3'
      content_type:
        description: 'The stream content type'
        example: 'audio/mp4'
    alias: Cast Selected Radio on Chromecast Speakers
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: >
            {% if is_state("input_select.chromecast_radio_speakers", "Huiskamer") %} media_player.lg_soundbar
            {% elif is_state("input_select.chromecast_radio_speakers", "Zolder") %} media_player.zolder
            {% elif is_state("input_select.chromecast_radio_speakers", "All") %} media_player.home_group
            {% endif %}
          volume_level: '{{ states.input_number.volume_radio.state | float * 0.025 }}' 
      - service: media_player.play_media
        data_template:
          entity_id: >
            {% if is_state("input_select.chromecast_radio_speakers", "Huiskamer") %} media_player.lg_soundbar
            {% elif is_state("input_select.chromecast_radio_speakers", "Zolder") %} media_player.zolder
            {% elif is_state("input_select.chromecast_radio_speakers", "All") %} media_player.home_group
            {% endif %}
          media_content_id: '{{ stream }}'
          media_content_type: '{{ content_type }}'
  
  stop_chromecast_radio:
    alias: Stop Playing Radio on Chromecast 
    sequence:
      - service: media_player.turn_off
        data_template:
          entity_id: >
            {% if is_state("input_select.chromecast_radio_speakers", "Huiskamer") %} media_player.lg_soundbar
            {% elif is_state("input_select.chromecast_radio_speakers", "Zolder") %} media_player.zolder
            {% elif is_state("input_select.chromecast_radio_speakers", "All") %} media_player.home_group
            {% endif %}
