rdw:
  - plate: 82ZXJ2
    name: golf_7
    binary_sensors:
      - insured
    sensors:
      - expdate
      - recall

homeassistant:
  customize:
    sensor.golf_7_expdate:
      friendly_name: "APK Vervaldatum"
    binary_sensor.golf_7_insured:
      friendly_name: "Verzekeringsstatus"
    sensor.golf_7_recall:
      friendly_name: "Terugroepstatus"
