recorder:
  db_url: !secret mariadb_connection
  purge_keep_days: 5
  exclude:
    entities:
      # Time
      - sensor.time
      - sensor.date
      - sensor.date_time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.time_date
      - sensor.time_utc
      - sensor.internet_time
      - sensor.time_of_day
      - sensor.day_or_night

      # Uptime
      - sensor.uptime
      - sensor.host_uptime
      - sensor.runtime

      #DSMR
      - sensor.dsmr_reading_timestamp

      # Adding items here you probably also want to add to logbook.yaml

sensor:
  - platform: sql
    db_url: !secret mariadb_connection
    queries:
      - name: MariaDB size
        query: >
          SELECT 
            table_schema, 
            ROUND(SUM(data_length + index_length) / 1024 / 1024, 0) AS "size" 
          FROM information_schema.TABLES
          WHERE table_schema="homeassistant"
          GROUP BY table_schema
        column: 'size'
        unit_of_measurement: MB
