sabnzbd:
  api_key: !secret sab_api_key
  host: sabnzbd
  name: sab
  port: 8080
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size

homeassistant:
  customize:
    sensor.sab_status:
      friendly_name: Status
      icon: "mdi:eye"
    sensor.sab_speed:
      friendly_name: Speed
      icon: "mdi:speedometer"
    sensor.sab_queue_count:
      friendly_name: Queue count
      icon: "mdi:tray-full"
    sensor.sab_queue:
      friendly_name: Queue
      icon: "mdi:tray-alert"
    sensor.sab_disk:
      friendly_name: Disk size
      icon: "mdi:harddisk"
    sensor.sab_disk_free:
      friendly_name: Disk free
      icon: "mdi:harddisk"
    sensor.sab_left:
      friendly_name: Left
      icon: "mdi:eye"
    sensor.sab_daily_total:
      friendly_name: Daily total
      icon: "mdi:chart-bar"
    sensor.sab_weekly_total:
      friendly_name: Weekly total
      icon: "mdi:chart-bar"
    sensor.sab_monthly_total:
      friendly_name: Monthly total
      icon: "mdi:chart-bar"
    sensor.sab_total:
      friendly_name: Total
      icon: "mdi:chart-bar"
