# Slaapkamer rolluik
cover:
  - platform: mqtt
    name: "Slaapkamer rolluik"
    state_topic: "shellies/shellyswitch25-E098068D1F4A/roller/0"
    command_topic: "shellies/shellyswitch25-E098068D1F4A/roller/0/command"
    position_topic: "shellies/shellyswitch25-E098068D1F4A/roller/0/pos"
    set_position_topic: "shellies/shellyswitch25-E098068D1F4A/roller/0/command/pos"
    #availability_topic: "shellies/shellyswitch25-E098068D1F4A/online"
    payload_available: "true"
    payload_not_available: "false"
    qos: 1
    retain: false
    payload_open: "open"
    payload_close: "close"
    payload_stop: "stop"
    position_open: 100
    position_closed: 0
    optimistic: false

sensor:
  - platform: mqtt
    name: "Slaapkamer rolluik Shelly temperatuur"
    state_topic: "shellies/shellyswitch25-E098068D1F4A/temperature"
    unit_of_measurement: '°C'
    device_class: temperature
        
automation:
    - alias: 'Rolluik dicht avond'
      trigger:
          platform: time
          at: "22:00:00"
      condition:
        - condition: template
          value_template: "{{ not is_state('cover.slaapkamer_rolluik', 'closed') }}"
        - condition: template
          value_template: "{{ is_state('binary_sensor.slaapkamerraam_contact', 'off') }}"
      action:
          service: cover.close_cover
          data:
              entity_id: cover.slaapkamer_rolluik
