tahoma:
  username: !secret somfy_username
  password: !secret somfy_password

homeassistant:
  customize:
    binary_sensor.zonnescherm_contact_contact:
      device_class: shade # This shouldn't be a door.
    cover.zonnescherm:
      icon: mdi:storefront-outline
