telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_house_group
      - !secret telegram_sander

automation:
  - id: telegram_commands
    alias: Telegram commandos
    description: Telegram commandos
    mode: parallel
    trigger:
      - platform: event
        event_type: telegram_command
    action:
      - variables:
          chat_id: >-
            {{ trigger.event.data["chat_id"] }}
          command: >-
            {{ trigger.event.data["command"] }}

      - choose:
          - alias: Start
            conditions:
              - "{{ command == '/start' }}"
            sequence:
              - service: telegram_bot.send_message
                data:
                  target: "{{ chat_id }}"
                  keyboard:
                    - /meterstanden
                    - /wie_thuis
                    - /weer
                    - /ping
                  message: >-
                    {{ 
                      [
                        "Hi, Ik ben je Home Assistant... Waar kan ik je mee helpen?",
                        "Wat kan ik voor je doen?"
                      ] | random 
                    }}

          - alias: Ping
            conditions:
              - "{{ command == '/ping' }}"
            sequence:
              - service: telegram_bot.send_message
                data:
                  target: "{{ chat_id }}"
                  message: >-
                    {{ now().strftime("%Y-%m-%d %H:%M:%S") }} Pong

          - alias: Meterstanden
            conditions:
              - "{{ command == '/meterstanden' }}"
            sequence:
              - service: telegram_bot.send_message
                data:
                  target: "{{ chat_id }}"
                  parse_mode: markdown
                  message: |-
                    *Stroom:*
                    Laagtarief: {{ states("sensor.dsmr_reading_electricity_delivered_1") }} kWh
                    Normaaltarief: {{ states("sensor.dsmr_reading_electricity_delivered_2") }} kWh

                    *Stadsverwarming:*
                    Energie: {{ states("sensor.kamstrup_403_heat_energy_e1") }} GJ
                    Volume: {{ states("sensor.kamstrup_403_volume") }} m³

                    *Water:*
                    Verbruik: {{ states("sensor.watermeter_totaal") }} m³

          - alias: Wie is er thuis
            conditions:
              - "{{ command == '/wie_thuis' }}"
            sequence:
              - service: telegram_bot.send_message
                data:
                  target: "{{ chat_id }}"
                  parse_mode: markdown
                  message: |-
                    Op dit moment thuis: 
                    {{ 
                      states.person 
                        | selectattr("state", "eq", "home")
                        | map(attribute="attributes.friendly_name")
                        | join(", ")
                        | default("Niemand")
                    }}

          - alias: Weer
            conditions:
              - "{{ command == '/weer' }}"
            sequence:
              - service: telegram_bot.send_message
                data:
                  target: "{{ chat_id }}"
                  parse_mode: markdown
                  message: |-
                    🌤️ *Weer thuis*:
                    
                    *Temperatuur*:               {{ state_attr("weather.knmi_purmerend", "temperature") }} °C
                    *Gevoelstemperatuur*: {{ states("sensor.knmi_purmerend_gevoelstemperatuur") }} °C
                    *Luchtvochtigheid*:       {{ state_attr("weather.knmi_purmerend", "humidity") }} %
                    *Luchtdruk*:                    {{ state_attr("weather.knmi_purmerend", "pressure") }} hPa

                    {{ state_attr("sensor.lokaal_weer_en_verkeer", "weatherDescription") }}

                    {% if is_state("binary_sensor.knmi_purmerend_waarschuwing", "on") %}
                    ⚠️ *Waarschuwing*
                    {{ state_attr("binary_sensor.knmi_purmerend_waarschuwing", "Waarschuwing") }}
                    {% endif %}
