template:
  - binary_sensor:
      - name: MacBook in thuis kantoor
        state: >-
          {{
            is_state("device_tracker.macbook_pro_van_sander", "home") and
            states("sensor.macbook_pro_van_sander_displays") not in ["unavailable"] and
            "DELL P2419H" in state_attr("sensor.macbook_pro_van_sander_displays", "Display Names")
          }}
      - name: MacBook in thuis kantoor en aan
        state: >-
          {{
            is_state("binary_sensor.macbook_in_thuis_kantoor", "on") and is_state("binary_sensor.macbook_pro_van_sander_active", "on")
          }}

automation:
  - id: mac_home_office_private
    alias: Thuiswerken, stop muziek bij vergadering of inactiviteit (prive)
    use_blueprint:
      path: golles/mac_home_office.yaml
      input:
        macbook_active_binary_sensor: binary_sensor.macbook_pro_van_sander_active
        macbook_audio_input_binary_sensor: binary_sensor.macbook_pro_van_sander_audio_input_in_use
        macbook_display_sensor: sensor.macbook_pro_van_sander_displays
        macbook_frontmost_app_sensor: sensor.macbook_pro_van_sander_frontmost_app
        macbook_device_tracker: device_tracker.macbook_pro_van_sander
        media_player: media_player.logeerkamer
        monitor_name: DELL P2419H
        apps:
          - Google Chrome
