sensor:
  - platform: time_date
    display_options:
      - time
      - date
      - date_time
      - date_time_utc
      - date_time_iso
      - time_date
      - time_utc
      - beat

template:
  - binary_sensor:
      - name: Zomertijd
        icon: >-
          {% if is_state("binary_sensor.zomertijd", "on") %}
            mdi:clock-time-three-outline
          {% else %}
            mdi:clock-time-three
          {% endif %}
        state: >-
          {{ now().timetuple().tm_isdst == 1 }}

binary_sensor:
  - platform: tod
    name: Night
    after: "00:00"
    before: "06:00"

  - platform: tod
    name: Morning
    after: "06:00"
    before: "12:00"

  - platform: tod
    name: Afternoon
    after: "12:00"
    before: "18:00"

  - platform: tod
    name: Evening
    after: "18:00"
    before: "00:00"

  - platform: tod
    name: Zon op
    after: sunrise
    before: sunset
