sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

  - platform: template
    sensors:
      time_of_day:
        value_template: >-
          {% set hour = strptime(states('sensor.time'), '%H:%M').hour %}
          {% if hour in range(0, 12) %} Morning
          {% elif hour in range(12, 18) %} Afternoon
          {% else %} Evening
          {% endif %}

      day_or_night:
        value_template: >-
          {% set hour = strptime(states('sensor.time'), '%H:%M').hour %}
          {% if hour in range(6, 18) %} Day
          {% else %} Night
          {% endif %}
    