automation:
  - id: ups_state_change
    alias: UPS status verandering
    mode: single
    triggers:
      - trigger: state
        entity_id: sensor.apc_back_ups_bx950mi_status
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.apc_back_ups_bx950mi_status
            state: unavailable
          - condition: state
            entity_id: sensor.apc_back_ups_bx950mi_self_test_result
            state: In progress
    actions:
      - alias: Sent a notification with the state
        action: notify.sander
        data:
          title: UPS status
          message: >-
            {{ states("sensor.apc_back_ups_bx950mi_status") }}
          data:
            group: ups
            url: /lovelace/hal
