switch:
  - platform: template
    switches:
      ups_beeper:
        friendly_name: UPS Beeper
        icon_template: >
          {% if is_state("sensor.ups_pieperstatus", "enabled") %}
            mdi:volume-high
          {% else %}
            mdi:volume-off
          {% endif %}
        value_template: >
          {{ is_state("sensor.ups_pieperstatus", "enabled") }}
        turn_on:
          type: beeper_enable
          device_id: b19f3ccae50bad3167a884a6fdff5e4b
          domain: nut
        turn_off:
          type: beeper_disable
          device_id: b19f3ccae50bad3167a884a6fdff5e4b
          domain: nut

automation:
  - id: ups_state_change
    alias: UPS status verandering
    mode: single
    triggers:
      - trigger: state
        entity_id: sensor.ups_status
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.ups_resultaat_zelftest
            state: In progress
      - condition: template
        value_template: >
          {{
            trigger.from_state.state not in ["unavailable", "Online", "Online Battery Charging"] and
            trigger.to_state.state not in ["unavailable", "Online", "Online Battery Charging"]
          }}
    actions:
      - alias: Sent a notification with the state
        action: notify.sander
        data:
          title: UPS status
          message: >-
            {{ states("sensor.ups_status") }}
          data:
            group: ups
            url: /lovelace/hal
