automation:
  - id: ups_state_change
    alias: UPS status verandering
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.apc_back_ups_bx950mi_status
    action:
      - alias: Sent a notification with the state
        service: notify.sander
        data:
          title: UPS status
          message: >-
            {{ states("sensor.apc_back_ups_bx950mi_status") }}
          data:
            group: ups
            url: /lovelace/meterkast
