sensor:
  - platform: uptime

  - platform: command_line
    name: runtime
    command: echo "$(($(date +%s) - $(date -d "$(head -n1 /config/home-assistant.log | cut -d' ' -f-2)" +%s)))"

  - platform: command_line
    name: host_uptime
    command: 'sed "s/\..*//" /proc/uptime'
  
homeassistant:
  customize:
    sensor.runtime:
      friendly_name: HA Uptime
      icon: mdi:clock
    sensor.host_uptime:
      friendly_name: Host uptime
      icon: mdi:clock