sensor:
  - platform: version
  - platform: version
    source: docker

automation:
  - id: notification_new_version
    alias: "Notificatie: Nieuwe versie beschikbaar"
    initial_state: on
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.updater
        attribute: newest_version
    action:
      - service: notify.telegram_sander
        data:
          message: |
            Versie *{{ state_attr("binary_sensor.updater", "newest_version") }}* is beschikbaar!
            De huidige versie is {{ states("sensor.current_version") }}.
            {{ state_attr("binary_sensor.updater", "release_notes") }}
