input_number:
  water_verbruik:
    name: Water verbruik
    icon: mdi:water-pump
    mode: box
    unit_of_measurement: m3
    initial: 0
    min: 0
    max: 99999999
    step: 1

automation:
  - id: increase_water_meter
    alias: 'Waterverbruik optellen'
    initial_state: on
    trigger:
      - platform: state
        entity_id: sensor.watermeter_usage
    condition:
      condition: numeric_state
      entity_id: sensor.watermeter_usage
      above: 0
    action:
      - service: input_number.increment
        data:
          entity_id: input_number.water_verbruik     

utility_meter:
  waterverbruik_per_dag:
    source: sensor.watermeter_usage
    cycle: daily    
  waterverbruik_per_uur:
    source: sensor.watermeter_usage
    cycle: hourly  
  waterverbruik_per_week:
    source: sensor.watermeter_usage
    cycle: weekly
  waterverbruik_per_maand:
    source: sensor.watermeter_usage
    cycle: monthly
  waterverbruik_per_kwartaal:
    source: sensor.watermeter_usage
    cycle: quarterly
  waterverbruik_per_jaar:
    source: sensor.watermeter_usage
    cycle: yearly    