binary_sensor:
  - platform: workday
    name: holiday
    country: NL
    workdays:
      - holiday
    excludes: []
    add_holidays:
      - "2021-02-05"
      - "2022-02-05"
      - "2023-02-05"
      - "2024-02-05"
      - "2025-02-05"

  - platform: workday
    name: workday
    country: NL
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun]
