homeassistant:
  customize:
    fan.air_purifier:
      icon: mdi:air-purifier

fan:
  - platform: xiaomi_miio_fan
    name: Ventilator
    host: !secret fan_ip
    token: !secret fan_token

sensor:
  - platform: template
    sensors:
      air_purifier_air_quality:
        friendly_name: Luchtkwaliteit
        value_template: >
          {% set aqi = states("sensor.mi_air_purifier_3_3h_pm2_5") | int %}
          {% if aqi == None %}
            Onbekend
          {% elif aqi < 12 %}
            Goed
          {%- elif aqi <= 35.4 -%}
            Matig
          {%- elif aqi <= 55.4 -%}
            Ongezond voor gevoelige groepen
          {%- elif aqi <= 150.4 -%}
            Ongezond
          {%- elif aqi <= 250.4 -%}
            Heel ongezond
          {%- elif aqi > 250.4 -%}
            Gevaarlijk
          {%- else -%}
            Onbekend
          {% endif %}
