homeassistant:
  customize:
    fan.air_purifier:
      icon: mdi:air-purifier

switch:
  - platform: template
    switches:
      air_purifier_led:
        friendly_name: Scherm
        value_template: >
          {{ is_state_attr("fan.air_purifier", "led", true) }}
        turn_on:
          service: xiaomi_miio.fan_set_led_on
          data:
            entity_id: fan.air_purifier
        turn_off:
          service: xiaomi_miio.fan_set_led_off
          data:
            entity_id: fan.air_purifier
        icon_template: mdi:lightbulb-outline

      air_purifier_child_lock:
        friendly_name: Kinderslot
        value_template: >
          {{ is_state_attr("fan.air_purifier", "child_lock", true) }}
        turn_on:
          service: xiaomi_miio.fan_set_child_lock_on
          data:
            entity_id: fan.air_purifier
        turn_off:
          service: xiaomi_miio.fan_set_child_lock_off
          data:
            entity_id: fan.air_purifier
        icon_template: mdi:lock-outline

sensor:
  - platform: template
    sensors:
      air_purifier_air_quality:
        friendly_name: Luchtkwaliteit
        value_template: >
          {% set aqi = state_attr("fan.air_purifier", "aqi") %}
          {% if aqi == None %}
            Onbekend
          {% elif aqi < 12 %}
            Goed
          {%- elif aqi <= 35.4 -%}
            Matig
          {%- elif aqi <= 55.4 -%}
            Ongezond voor gevoelige groepen
          {%- elif aqi <= 150.4 -%}
            Ongezond
          {%- elif aqi <= 250.4 -%}
            Heel ongezond
          {%- elif aqi > 250.4 -%}
            Gevaarlijk
          {%- else -%}
            Onbekend
          {% endif %}
