homeassistant:
  customize:
    fan.air_purifier:
      icon: mdi:air-purifier

fan:
  - platform: xiaomi_miio_fan
    name: Ventilator
    host: !secret fan_ip
    token: !secret fan_token

template:
  - sensor:
      - name: Woonkamer luchtkwaliteit
        state: >-
          {% from "aqi.jinja" import pm25 %}
          {{ pm25(states("sensor.mi_air_purifier_3_3h_pm2_5")) }}
