ziggonext:
  username: !secret ziggo_username
  password: !secret ziggo_password
  country_code: nl

sensor:
  - platform: rest
    name: Ziggo incidents
    scan_interval: 10800 # 60 * 60 * 3
    json_attributes:
      - callback
      - outages
      - announcements
    resource: !secret ziggo_incidents_url
    value_template: '{{ value_json.callback.timestamp }}'

switch:
  - platform: template
    switches:
      ziggo_decoder:
        friendly_name: Ziggo decoder
        icon_template: mdi:television
        value_template: "{{ not is_state('media_player.stb_arris_uhd', 'off') }}"
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.stb_arris_uhd
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.stb_arris_uhd
