sensor:
  - platform: rest
    name: Ziggo incidents
    scan_interval: 10800 # 60 * 60 * 3
    json_attributes:
      - outages
      - announcements
    resource: !secret ziggo_incidents_url
    value_template: >-
      {{ value_json.outages | count }}

automation:
  - id: notification_ziggo_incidents
    alias: "Notificatie: Ziggo incidenten"
    triggers:
      - trigger: state
        entity_id: sensor.ziggo_incidents
    condition:
      - condition: template
        value_template: >-
          {{
            state_attr("sensor.ziggo_incidents", "announcements") not in [None, []] and
            state_attr("sensor.ziggo_incidents", "outages") not in [None, []]
          }}
    actions:
      - alias: Send the notification
        action: notify.discord
        data:
          message: ""
          target: !secret discord_monitoring
          data:
            embed:
              author:
                name: Ziggo
                icon_url: https://cdn.cookielaw.org/logos/02f2e6bc-5994-41d3-9b96-f6ab724d56c8/018e1992-075b-7323-8b0b-39f426570b05/93e69452-69c0-4cca-a40f-90acd60ebb16/ZIGGO-logo-800x800.png
              color: 16026624 # Orange
              title: Storingen en onderhoud
              description: |
                {{ state_attr("sensor.ziggo_incidents", "outages") }}
                {{ state_attr("sensor.ziggo_incidents", "announcements") }}
